apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-service.fullname" . }}
  labels:
    {{- include "frontend-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- if .Values.ccrProxy.enabled }}
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "frontend-service.selectorLabels" . | nindent 4 }}
