name: Test triton inference CACI
description: Test triton inference CACI
inputs:
  repo:
    description: The registry URL
    required: true
  tag:
    description: The tag for the built image
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Login to Azure and refresh token
      uses: ./.github/actions/login-to-azure
      env:
        CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        TENANT_ID: ${{ env.AZURE_TENANT_ID }}
        SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Install az cleanroom extension
      shell: bash
      run: |
        oras pull ${{ inputs.repo }}/cli/cleanroom-whl:${{ inputs.tag }}
        az extension add --allow-preview true --source ./cleanroom-*-py2.py3-none-any.whl -y

    - name: Run collab scenario on caci
      shell: pwsh
      run: ./test/onebox/multi-party-collab/triton-inference-server/run-collab-aci.ps1 -registry acr -repo ${{ inputs.repo}} -tag ${{ inputs.tag }}

    - name: Upload generated
      uses: actions/upload-artifact@v4
      with:
          name: generated-triton-inference-caci
          path: ./test/onebox/multi-party-collab/triton-inference-server/generated
          overwrite: true
      if: ${{ !cancelled() }}

    - name: Delete resource groups
      if: success()
      shell: pwsh
      run: ./test/onebox/multi-party-collab/remove-resources.ps1 -tag "github_actions=multi-party-collab-${{ env.JOB_ID }}-${{ env.RUN_ID }}"