// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text.Json.Serialization;

namespace FrontendSvc.Models;

/// <summary>
/// Describes a dataset to be presented to a Spark application.
/// </summary>
public class SparkApplicationDatasetDescriptor
{
    /// <summary>
    /// Gets or sets the specification of the dataset to be presented to the Spark application.
    /// </summary>
    [JsonPropertyName("specification")]
    public required string Specification { get; set; }

    /// <summary>
    /// Gets or sets the name of the view to be generated by the Spark application for
    /// accessing the dataset.
    /// </summary>
    [JsonPropertyName("view")]
    public required string View { get; set; }
}
