# DO NOT EDIT. AUTO-GENERATED CODE.
# Please run tools/generate_models.ps1 to re-generate the file after editing openapi/query.yaml.


# generated by datamodel-codegen:
#   filename:  query.yaml

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class PreCondition(BaseModel):
    viewName: str = Field(
        ...,
        description="The name of the view of the loaded dataset on which the pre-condition is to be applied",
    )
    minRowCount: int = Field(
        ...,
        description="The minimum row count in the view of the dataset. If the row count is less than this value, the query will not be executed",
    )


class PostFilter(BaseModel):
    columnName: str
    value: int = Field(
        ...,
        description="The minimum value that a column must have in the row, to retain that row. All other rows are filtered out",
    )


class QuerySegment(BaseModel):
    executionSequence: int = Field(
        ...,
        description="The sequence in which this segment is to be executed. Segments with lower sequence number are executed before the higher ones. Segments with the same sequence will be executed in parallel.",
    )
    data: str
    preConditions: Optional[List[PreCondition]] = None
    postFilters: Optional[List[PostFilter]] = None


class Query(BaseModel):
    segments: List[QuerySegment]
