apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          taints:
            - key: "for-flex-node"
              value: "true"
              effect: "NoSchedule"
  - role: worker
    labels:
      apps: llama-3point1-8b-instruct
    extraMounts:
      - hostPath: <HOST_SHARED_DIR>
        containerPath: /shared
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cpu-cfs-quota: "false"
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cpu-cfs-quota: "false"
# https://kind.sigs.k8s.io/docs/user/local-registry/
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
