apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cpu-cfs-quota: "false"
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cpu-cfs-quota: "false"
# https://kind.sigs.k8s.io/docs/user/local-registry/
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
