name: "Blobfuse Data Integrity with CPK"
description: "Data integrity validation for blobfuse mount with Customer-Provided Keys (CPK)."

inputs:
  account_type:
    description: "Account type"
    required: true
  mount_dir:
    description: "Mount directory"
    required: true
  config_file:
    description: "Configuration file"
    required: true
  temp_dir:
    description: "Temporary directory"
    required: true
  mount_dir_source:
    description: "Source mount directory for data generation"
    required: true
  temp_dir_source:
    description: "Source mount temporary directory"
    required: true
  config_file_source:
    description: "Source configuration file"
    required: true

runs:
  using: "composite"
  steps:

    - name: Create config file for source mount
      shell: bash
      run: |
        blobfuse2 gen-test-config \
          --config-file=./test/blobfuse/testdata/config/block_cache.yaml \
          --container-name=${{ env.SOURCE_CONTAINER_NAME }} \
          --temp-path=${{ inputs.temp_dir_source }} \
          --output-file=${{ inputs.config_file_source }}
      env:
        STO_ACC_NAME: ${{ env.STORAGE_ACCOUNT }}
        ACCOUNT_TYPE: ${{ inputs.account_type }}
        ACCOUNT_ENDPOINT: ${{ env.STORAGE_ACCOUNT_ENDPOINT }}
        LOG_FILE_PATH: ${{ github.workspace }}/blobfuse2-source-logs.txt
        BLOCK_SIZE_MB: 16
        MEM_SIZE_MB: 2048
        DISK_SIZE_MB: 6144

    - name: Print config file for source mount
      shell: bash
      run: cat ${{ inputs.config_file_source }}

    - name: Blobfuse source mount
      uses: ./.github/actions/blobfuse-mount
      with:
        mount_dir: ${{ inputs.mount_dir_source }}
        temp_dir: ${{ inputs.temp_dir_source }}
        mountStep: |
          blobfuse2 mount \
            ${{ inputs.mount_dir_source }} \
            --config-file=${{ inputs.config_file_source }} \
            --default-working-dir=${{ github.workspace }}

    - name: Create config file for CPK mount
      shell: bash
      run: |
        blobfuse2 gen-test-config \
          --config-file=./test/blobfuse/testdata/config/block_cache_cpk.yaml \
          --container-name=${{ env.CONTAINER_NAME }} \
          --temp-path=${{ inputs.temp_dir }} \
          --output-file=${{ inputs.config_file }}
      env:
        STO_ACC_NAME: ${{ env.STORAGE_ACCOUNT }}
        ACCOUNT_TYPE: ${{ inputs.account_type }}
        ACCOUNT_ENDPOINT: ${{ env.STORAGE_ACCOUNT_ENDPOINT }}
        LOG_FILE_PATH: ${{ github.workspace }}/blobfuse2-logs.txt
        BLOCK_SIZE_MB: 16
        MEM_SIZE_MB: 2048
        DISK_SIZE_MB: 6144

    - name: Print config file for CPK mount
      shell: bash
      run: cat ${{ inputs.config_file }}

    - name: Upload config files
      uses: actions/upload-artifact@v4
      with:
        name: blobfuse-cpk-config
        path: |
          ${{ inputs.config_file }}
          ${{ inputs.config_file_source }}
        overwrite: true
      if: ${{ !cancelled() }}

    - name: Mount Blobfuse with CPK
      uses: ./.github/actions/blobfuse-mount
      with:
        mount_dir: ${{ inputs.mount_dir }}
        temp_dir: ${{ inputs.temp_dir }}
        mountStep: |
          blobfuse2 mount \
            ${{ inputs.mount_dir }} \
            --config-file=${{ inputs.config_file }} \
            --default-working-dir=${{ github.workspace }}

    - name: Generate files in source mount
      shell: bash
      run: |
        mkdir -p ${{ inputs.mount_dir_source }}/testData
        for i in {1,3,7,16,50,100,1024,20480,51200}; do echo $i; done | \
        parallel --will-cite -j 5 'head -c {}M < /dev/urandom > ${{ inputs.mount_dir_source }}/testData/testfile_{}'
        ls -lh ${{ inputs.mount_dir_source }}/testData/testfile_*

    - name: Upload test files to cse mount
      shell: bash
      run: |
        for i in {1,3,7,16,50,100,1024,20480,51200}; do echo $i; done | \
        parallel --will-cite -j 5 'cp ${{ inputs.mount_dir_source }}/testData/testfile_{} ${{ inputs.mount_dir }}/testfile_{}'
        ls -lh ${{ inputs.mount_dir }}/testfile_*

    - name: Unmount
      shell: bash
      run: |
        sudo blobfuse2 unmount ${{ inputs.mount_dir }}

    - name: Remount in read-only mode
      uses: ./.github/actions/blobfuse-mount
      with:
        mount_dir: ${{ inputs.mount_dir }}
        temp_dir: ${{ inputs.temp_dir }}
        mountStep: |
          blobfuse2 mount \
            ${{ inputs.mount_dir }} \
            --config-file=${{ inputs.config_file }} \
            --default-working-dir=${{ github.workspace }} \
            -o ro
        ro_mount: 'true'

    - name: Compare SHA256 checksums
      shell: bash
      run: |
        for i in {1,3,7,16,50,100,1024,20480,51200}; do
          local_sha256=$(sha256sum ${{ inputs.mount_dir_source }}/testData/testfile_$i | cut -d ' ' -f 1)
          remote_sha256=$(sha256sum ${{ inputs.mount_dir }}/testfile_$i | cut -d ' ' -f 1)
          if [ "$local_sha256" != "$remote_sha256" ]; then
          echo "SHA256 mismatch for file $i: $local_sha256 (local) vs $remote_sha256 (remote)"
          echo "Data integrity validation failed."
          exit 1
          fi
        done

    - name: Blobfuse logs
      shell: bash
      run: |
        cat ${{ github.workspace }}/blobfuse2-logs.txt
      continue-on-error: true
      if: always()

    - name: Upload blobfuse logs
      uses: actions/upload-artifact@v4
      with:
        name: blobfuse-cpk-logs
        path: |
          ${{ github.workspace }}/blobfuse2-logs.txt
          ${{ github.workspace }}/blobfuse2-source-logs.txt
        overwrite: true
      if: ${{ !cancelled() }}

    - name: Cleanup
      shell: bash
      run: |
        sudo blobfuse2 unmount all
      if: always()
      continue-on-error: true