name: governance-aci
services:
  cgs-client:
    image: $CGS_CLIENT_IMAGE
    ports:
      - "0:8080"
  cgs-ui:
    image: $CGS_UI_IMAGE
    ports:
      - "0:6300"
    environment:
      - cgsclientEndpoint=http://cgs-client:8080