name: Release CGS constitution
description: Release CGS constitution

inputs:
  tag:
    description: The tag
    required: true
  environment:
    description: The environment being released to
    required: true
  registry-name:
    description: The registry to which the images need to be pushed
    required: true
  client-id:
    description: The client ID to connect to the registry
    required: true
  tenant-id:
    description: The tenant ID of the registry
    required: true
  subscription-id:
    description: The subscription ID of the registry
    required: true
  needs-attestation:
    description: Whether the container needs attestation
    required: true

runs:
  using: composite
  steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}

    # The azure/docker-login action currently does not support authentication using
    # federated credentials - https://github.com/Azure/docker-login/issues/56. Hence,
    # resorting to a manual login.
    - shell: bash
      run: az acr login --name ${{ inputs.registry-name }}

    - name: Download constitution
      uses: actions/download-artifact@v4
      id: download-artefact
      with:
        name: cgs-constitution-${{ inputs.tag }}.json

    - shell: pwsh
      run: |
        $constitution_digest = cat constitution.json | jq -S -j | sha256sum | cut -d ' ' -f 1
        oras push ${{ inputs.registry-name }}.azurecr.io/${{ inputs.environment }}/azurecleanroom/cgs-constitution:"${{ inputs.tag }},$constitution_digest,latest" ./constitution.json `
          --annotation "cleanroom.version=${{ inputs.tag }}" `
          --annotation "constitution.js.digest=sha256:$constitution_digest"

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: cgs-constitution
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}