"""
Auto-generated statistics events file.
DO NOT EDIT THIS FILE MANUALLY - it is generated by generator.py
"""

import enum

from pydantic import BaseModel, Field

from .statistics_event import StatisticsEvent


class StatisticsEventType(enum.Enum):
    """Enum for statistics event types."""

    QUERY_STATISTICS = "QUERY_STATISTICS"


class QueryStatisticsData(BaseModel):
    duration_sec: float = Field(description="Duration Sec", default=0.0)
    num_rows_read: int = Field(description="Num Rows Read", default=0)
    num_rows_written: int = Field(description="Num Rows Written", default=0)


class StatisticsEventFactory:
    """Factory class for StatisticsEvent instances."""

    @staticmethod
    def QueryStatistics(
        duration_sec: float, num_rows_read: int, num_rows_written: int
    ) -> StatisticsEvent:
        """
        Create QUERY_STATISTICS statistics event.
        """
        import base64
        import json

        data = QueryStatisticsData(
            duration_sec=duration_sec,
            num_rows_read=num_rows_read,
            num_rows_written=num_rows_written,
        ).dict()
        data_json = json.dumps(data)
        data_base64 = base64.b64encode(data_json.encode("utf-8")).decode("utf-8")

        return StatisticsEvent(
            type=StatisticsEventType.QUERY_STATISTICS.value,
            data_base64=data_base64,
        )
