name: Test nginx hello CACI
description: Test nginx hello CACI
inputs:
  repo:
    description: The registry URL
    required: true
  tag:
    description: The tag for the built image
    required: true
runs:
  using: composite
  steps:
    - name: Login to Azure and refresh token
      uses: ./.github/actions/login-to-azure
      env:
        CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        TENANT_ID: ${{ env.AZURE_TENANT_ID }}
        SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Install az cleanroom extension
      shell: bash
      run: |
        oras pull ${{ inputs.repo }}/cli/cleanroom-whl:${{ inputs.tag }}
        az extension add --allow-preview true --source ./cleanroom-*-py2.py3-none-any.whl -y

    - name: Log in to Azure Container Registry
      if: ${{ !contains(inputs.repo, 'mcr.microsoft.com/azurecleanroom') }}
      shell: pwsh
      run: az acr login -n ${{ inputs.repo }}

    - name: Run collab scenario on caci
      if: ${{ !contains(inputs.repo, 'mcr.microsoft.com/azurecleanroom') }}
      shell: pwsh
      run: ./test/onebox/multi-party-collab/nginx-hello/run-collab-aci.ps1 -registry acr -repo ${{ inputs.repo }} -tag ${{ inputs.tag }}

    - name: Run collab scenario on caci
      if: ${{ contains(inputs.repo, 'mcr.microsoft.com/azurecleanroom') }}
      shell: pwsh
      run: ./test/onebox/multi-party-collab/nginx-hello/run-collab-aci.ps1 -registry mcr -repo ${{ inputs.repo }} -tag ${{ inputs.tag }} -NoBuild

    - name: Dump ccf-provider-client logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: docker logs ccf-provider-client-1

    - name: Dump ob-nginx-client logs
      if: ${{ !cancelled() }}
      shell: pwsh
      run: docker logs ob-nginx-client-cgs-client-1

    - name: Dump ccr-client-proxy logs
      if: ${{ !cancelled() }}
      shell: pwsh
      run: docker logs ccr-client-proxy

    - name: Upload configurations
      uses: actions/upload-artifact@v4
      with:
          name: configurations-nginx-hello-caci
          path: ./test/onebox/multi-party-collab/nginx-hello/generated/configurations
          overwrite: true
      if: ${{ !cancelled() }}

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results-nginx-hello-caci
        path: ./test/onebox/multi-party-collab/nginx-hello/generated/results
        overwrite: true
      if: ${{ !cancelled() }}

    - name: Upload deployments
      uses: actions/upload-artifact@v4
      with:
          name: deployments-nginx-hello-caci
          path: ./test/onebox/multi-party-collab/nginx-hello/generated/deployments
          overwrite: true
      if: ${{ !cancelled() }}

    - name: Upload ccf
      uses: actions/upload-artifact@v4
      with:
          name: ccf-nginx-hello-caci
          path: ./test/onebox/multi-party-collab/nginx-hello/generated/ccf
          overwrite: true
      if: ${{ !cancelled() }}

    - name: Delete resource groups
      if: success()
      shell: pwsh
      run: ./test/onebox/multi-party-collab/remove-resources.ps1 -tag "github_actions=multi-party-collab-${{ env.JOB_ID }}-${{ env.RUN_ID }}"