// Generated by Microsoft TypeSpec

import {
  ListMemberDocumentResponse,
  UserProposal,
} from "./all/cleanroom/governance.js";

export interface CheckExecutionStatusResult {
  status: string;
}

export interface CheckLoggingStatusResult {
  status: string;
}

export interface CheckTelemetryStatusResult {
  status: string;
}

export interface ConsentCheckExecutionResult {
  status: string;
}

export interface ConsentCheckLoggingResult {
  status: string;
}

export interface ConsentCheckTelemetryResult {
  status: string;
}

export interface GetResult {
  policy: unknown;
}

export interface ListDelegatesResult {
  delegates: unknown[];
}

export interface GetDelegateResult {
  policy: unknown;
}

export interface GetSpecResult {
  spec: unknown;
}

export interface GetInfoResult {
  info: unknown;
}

export interface GetTokenResult {
  token: string;
}

export interface GenerateEndorsedCertResult {
  certificate: string;
}

export interface ListResult {
  value: ListMemberDocumentResponse[];
}

export interface ListResult {
  value: unknown[];
}

export interface GetResult {
  identity: unknown;
}

export interface IsActiveResult {
  active: boolean;
}

export interface ListResult {
  value: unknown[];
}

export interface GetResult {
  invitation: unknown;
}

export interface ConsentCheckResult {
  status: string;
}

export interface CheckStatusResult {
  status: string;
}

export interface GetHistoricalResult {
  proposal: unknown;
}

export interface GetStatusResult {
  status: string;

  proposal: UserProposal;
}

export interface GetConfigurationResult {
  configuration: unknown;
}

export interface GetJwksResult {
  keys: unknown[];
}

export interface SetIssuerUrlRequestBody {
  issuerUrl: string;
}

export interface GetIssuerInfoResult {
  issuerUrl: string;

  proposalIds: string[];
}

export interface GetOptions {
  nextLink?: string;
}

export interface ListOptions {
  labels?: Record<string, string>;
}

export interface CheckStatusResult {
  status: string;
}
