#
# From https://github.com/kubeflow/spark-operator/blob/master/config/rbac/spark-application-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator-spark
  namespace: <NAMESPACE>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: <NAMESPACE>
  name: spark-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: <NAMESPACE>
subjects:
- kind: ServiceAccount
  name: spark-operator-spark
  namespace: <NAMESPACE>
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io