openapi: 3.1.0
info:
  title: FastAPI
  description: Local IDP API
  version: 0.1.0
paths:
  /ready:
    get:
      summary: Root
      operationId: root_ready_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /generatesigningkey:
    post:
      summary: Generatesigingkey
      operationId: generateSigingKey_generatesigningkey_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /getsigningkey:
    get:
      summary: Getsigningkey
      operationId: getSigningKey_getsigningkey_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /setissuerurl:
    post:
      summary: Setissuerurl
      operationId: setIssuerUrl_setissuerurl_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssuerUrl'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /oidc/.well-known/openid-configuration:
    get:
      summary: Getopenidconfig
      operationId: getOpenIdConfig_oidc__well_known_openid_configuration_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /oidc/keys:
    get:
      summary: Getjwks
      operationId: getJwks_oidc_keys_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /oauth/token:
    post:
      summary: Gettoken
      operationId: getToken_oauth_token_post
      parameters:
      - name: nbf
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Nbf
      - name: exp
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Exp
      - name: sub
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Sub
      - name: tid
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Tid
      - name: aud
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Aud
      - name: oid
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Oid
      - name: iss
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Iss
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    IssuerUrl:
      properties:
        url:
          type: string
          title: Url
      type: object
      required:
      - url
      title: IssuerUrl
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
