loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  storage:
    type: filesystem

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

  persistence:
    enabled: true
    storageClass:
    size: 20Gi


# Zero out replica counts of other deployment modes
test:
  enabled: false
lokiCanary:
  enabled : false

gateway:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
