name: Test query analytics CACI
description: Test query analytics CACI
inputs:
  repo:
    description: The registry URL
    required: true
  tag:
    description: The tag for the built image
    required: true
runs:
  using: composite
  steps:
    - name: Login to Azure and refresh token
      uses: ./.github/actions/login-to-azure
      env:
        CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        TENANT_ID: ${{ env.AZURE_TENANT_ID }}
        SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Install az cleanroom extension
      shell: bash
      run: |
        oras pull ${{ inputs.repo }}/cli/cleanroom-whl:${{ inputs.tag }}
        az extension add --allow-preview true --source ./cleanroom-*-py2.py3-none-any.whl -y

    - name: Log in to Azure Container Registry
      shell: pwsh
      run: |
        $pattern = '(.*?)(\.azurecr\.io.*)'
        if ("${{ inputs.repo }}" -match $pattern) {
            $acrName = $matches[1]
        } else {
            $acrName =  "${{ inputs.repo }}"
        }

        az acr login -n $acrName

    - name: Run collab scenario on caci
      if: ${{ !contains(inputs.repo, 'mcr.microsoft.com/azurecleanroom') }}
      shell: pwsh
      run: ./test/onebox/multi-party-collab/query-analytics/run-collab-aci.ps1 -registry acr -repo ${{ inputs.repo }} -tag ${{ inputs.tag }}

    - name: Run collab scenario on caci
      if: ${{ contains(inputs.repo, 'mcr.microsoft.com/azurecleanroom') }}
      shell: pwsh
      run: ./test/onebox/multi-party-collab/query-analytics/run-collab-aci.ps1 -registry mcr -repo ${{ inputs.repo }} -tag ${{ inputs.tag }} -NoBuild

    - name: Dump ccf-provider logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: docker compose -p ob-query-analytics-ccf-provider logs

    - name: Dump ob-nginx-client logs
      if: ${{ !cancelled() }}
      shell: pwsh
      run: docker logs ob-publisher-client-cgs-client-1

    - name: Upload generated
      uses: actions/upload-artifact@v4
      with:
          name: generated-query-analytics-caci
          path: ./test/onebox/multi-party-collab/query-analytics/generated
          overwrite: true
      if: ${{ !cancelled() }}

    - name: Delete resource groups
      if: success()
      shell: pwsh
      run: ./test/onebox/multi-party-collab/remove-resources.ps1 -tag "github_actions=multi-party-collab-${{ env.JOB_ID }}-${{ env.RUN_ID }}"