name: samples-governance-ccf
services:
  ccf:
    image: ${ccfImage}
    ports:
      - "0:8080"
    volumes:
      - ${cgs_sandbox_common}/${initialMemberName}_cert.pem:/app/member0_cert.pem
      - ${cgs_sandbox_common}/${initialMemberName}_enc_pubk.pem:/app/member0_enc_pubk.pem
    environment:
      - CCR_ATTESTATION_HOST=cvm-attestation-verifier
      - CCR_ATTESTATION_PORT=8901
  cvm-attestation-verifier:
    image: ${cvmAttestationVerifierImage}
    ports:
      - "8901:8901"
  recovery-agent:
    image: ${recoveryAgentImage}
    ports:
      - "0:9080"
    environment:
      - CCF_ENDPOINT=https://ccf:8080
      - CCF_ENDPOINT_SKIP_TLS_VERIFY=true
      - ASPNETCORE_URLS=http://+:9080
      - INSECURE_VIRTUAL_ENVIRONMENT=true
    volumes:
      - ${root_dir}/samples/reports/insecure-virtual:/app/insecure-virtual:ro
