// Generated by Microsoft TypeSpec

export const openApiDocument = {
  openapi: "3.0.0",
  info: { title: "Cleanroom Governance Service", version: "0.0.0" },
  tags: [],
  paths: {
    "/contracts": {
      get: {
        operationId: "Contracts_list",
        description: "List all contracts",
        parameters: [],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/ListContractsResponse" },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}": {
      put: {
        operationId: "Contracts_put",
        description: "Create or update a contract",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/PutContractRequest" },
            },
          },
        },
      },
      get: {
        operationId: "Contracts_get",
        description: "Get a contract by ID",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/GetContractResponse" },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/checkstatus/execution": {
      post: {
        operationId: "ContractRuntimeOptions_checkExecutionStatus",
        description: "Check contract execution status",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { status: { type: "string" } },
                  required: ["status"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/checkstatus/logging": {
      post: {
        operationId: "ContractRuntimeOptions_checkLoggingStatus",
        description: "Check contract logging status",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { status: { type: "string" } },
                  required: ["status"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/checkstatus/telemetry": {
      post: {
        operationId: "ContractRuntimeOptions_checkTelemetryStatus",
        description: "Check contract telemetry status",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { status: { type: "string" } },
                  required: ["status"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/consentcheck/execution": {
      post: {
        operationId: "ContractRuntimeOptions_consentCheckExecution",
        description: "Consent check for execution",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { status: { type: "string" } },
                  required: ["status"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/consentcheck/logging": {
      post: {
        operationId: "ContractRuntimeOptions_consentCheckLogging",
        description: "Consent check for logging",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { status: { type: "string" } },
                  required: ["status"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/consentcheck/telemetry": {
      post: {
        operationId: "ContractRuntimeOptions_consentCheckTelemetry",
        description: "Consent check for telemetry",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { status: { type: "string" } },
                  required: ["status"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/enable": {
      post: {
        operationId: "ContractRuntimeOptions_enable",
        description: "Enable a contract",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
      },
    },
    "/contracts/{contractId}/disable": {
      post: {
        operationId: "ContractRuntimeOptions_disable",
        description: "Disable a contract",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
      },
    },
    "/contracts/{contractId}/events": {
      get: {
        operationId: "Events_get",
        description: "Get events for a contract",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
          {
            name: "nextLink",
            in: "query",
            required: false,
            schema: { type: "string" },
            explode: false,
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/GetEventsResponse" },
              },
            },
          },
        },
      },
      put: {
        operationId: "Events_put",
        description: "Put an event",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/PutEventRequest" },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/secrets": {
      get: {
        operationId: "Secrets_list",
        description: "List all secrets for a contract",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/ListSecretsResponse" },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/secrets/{secretName}": {
      put: {
        operationId: "Secrets_put",
        description: "Create or update a secret",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
          {
            name: "secretName",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/PutSecretResponse" },
              },
            },
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                anyOf: [
                  { $ref: "#/components/schemas/PutSecretByMemberUserRequest" },
                  { $ref: "#/components/schemas/PutSecretByCleanRoomRequest" },
                ],
              },
            },
          },
        },
      },
      post: {
        operationId: "Secrets_get",
        description: "Get a secret",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
          {
            name: "secretName",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/GetSecretResponse" },
              },
            },
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/GetSecretRequest" },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/cleanroompolicy": {
      get: {
        operationId: "CleanRoomPolicy_get",
        description: "Get clean room policy for a contract",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { policy: {} },
                  required: ["policy"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/cleanroompolicy/delegates": {
      get: {
        operationId: "CleanRoomPolicy_listDelegates",
        description: "List delegate policies",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { delegates: { type: "array", items: {} } },
                  required: ["delegates"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/cleanroompolicy/delegates/{delegateType}/{delegateId}":
      {
        get: {
          operationId: "CleanRoomPolicy_getDelegate",
          description: "Get delegate clean room policy",
          parameters: [
            {
              name: "contractId",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
            {
              name: "delegateType",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
            {
              name: "delegateId",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
          ],
          responses: {
            "200": {
              description: "The request has succeeded.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: { policy: {} },
                    required: ["policy"],
                  },
                },
              },
            },
          },
        },
        post: {
          operationId: "CleanRoomPolicy_setDelegate",
          description: "Set delegate clean room policy",
          parameters: [
            {
              name: "contractId",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
            {
              name: "delegateType",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
            {
              name: "delegateId",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
          ],
          responses: {
            "204": {
              description:
                "There is no content to send for this request, but the headers may be useful. ",
            },
          },
          requestBody: {
            required: true,
            content: { "application/json": { schema: {} } },
          },
        },
      },
    "/contracts/{contractId}/deploymentspec": {
      get: {
        operationId: "Deployment_getSpec",
        description: "Get deployment specification",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { spec: {} },
                  required: ["spec"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/deploymentinfo": {
      get: {
        operationId: "Deployment_getInfo",
        description: "Get deployment information",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { info: {} },
                  required: ["info"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/oauth/token": {
      post: {
        operationId: "OAuth_getToken",
        description: "Get OAuth token",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { token: { type: "string" } },
                  required: ["token"],
                },
              },
            },
          },
        },
        requestBody: {
          required: true,
          content: { "application/json": { schema: {} } },
        },
      },
    },
    "/contracts/{contractId}/ca/generateSigningKey": {
      post: {
        operationId: "CertificateAuthority_generateSigningKey",
        description: "Generate CA signing key",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
      },
    },
    "/contracts/{contractId}/ca/generateEndorsedCert": {
      post: {
        operationId: "CertificateAuthority_generateEndorsedCert",
        description: "Generate endorsed certificate",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { certificate: { type: "string" } },
                  required: ["certificate"],
                },
              },
            },
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                $ref: "#/components/schemas/GenerateEndorsedCertRequest",
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/ca/info": {
      get: {
        operationId: "CertificateAuthority_getInfo",
        description: "Get CA information",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/CAInfo" },
              },
            },
          },
        },
      },
    },
    "/memberdocuments": {
      get: {
        operationId: "MemberDocuments_list",
        description: "List all member documents",
        parameters: [],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    value: {
                      type: "array",
                      items: {
                        $ref: "#/components/schemas/ListMemberDocumentResponse",
                      },
                    },
                  },
                  required: ["value"],
                },
              },
            },
          },
        },
      },
    },
    "/memberdocuments/{documentId}": {
      put: {
        operationId: "MemberDocuments_put",
        description: "Create or update a member document",
        parameters: [
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/PutMemberDocumentRequest" },
            },
          },
        },
      },
      get: {
        operationId: "MemberDocuments_get",
        description: "Get a member document",
        parameters: [
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/GetMemberDocumentResponse",
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/acceptedMemberDocuments/{documentId}": {
      post: {
        operationId: "AcceptedMemberDocuments_get",
        description: "Get accepted member document",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/GetAcceptedMemberDocumentResponse",
                },
              },
            },
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                $ref: "#/components/schemas/GetAcceptedMemberDocumentRequest",
              },
            },
          },
        },
      },
    },
    "/users/identities": {
      get: {
        operationId: "UserIdentities_list",
        description: "List all user identities",
        parameters: [],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { value: { type: "array", items: {} } },
                  required: ["value"],
                },
              },
            },
          },
        },
      },
    },
    "/users/identities/{identityId}": {
      get: {
        operationId: "UserIdentities_get",
        description: "Get a user identity",
        parameters: [
          {
            name: "identityId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { identity: {} },
                  required: ["identity"],
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/users/isactive": {
      post: {
        operationId: "ContractUsers_isActive",
        description: "Check if user is active",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { active: { type: "boolean" } },
                  required: ["active"],
                },
              },
            },
          },
        },
      },
    },
    "/users/invitations": {
      get: {
        operationId: "UserInvitations_list",
        description: "List all user invitations",
        parameters: [],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { value: { type: "array", items: {} } },
                  required: ["value"],
                },
              },
            },
          },
        },
      },
    },
    "/users/invitations/{invitationId}": {
      get: {
        operationId: "UserInvitations_get",
        description: "Get a user invitation",
        parameters: [
          {
            name: "invitationId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { invitation: {} },
                  required: ["invitation"],
                },
              },
            },
          },
        },
      },
    },
    "/users/invitations/{invitationId}/accept": {
      post: {
        operationId: "UserInvitations_accept",
        description: "Accept a user invitation",
        parameters: [
          {
            name: "invitationId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
      },
    },
    "/userdocuments": {
      get: {
        operationId: "UserDocuments_list",
        description: "List all user documents",
        parameters: [
          {
            name: "labels",
            in: "query",
            required: false,
            schema: {
              type: "object",
              additionalProperties: { type: "string" },
            },
            explode: false,
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/ListUserDocumentsResponse",
                },
              },
            },
          },
        },
      },
    },
    "/userdocuments/{documentId}": {
      put: {
        operationId: "UserDocuments_put",
        description: "Create or update a user document",
        parameters: [
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/PutUserDocumentRequest" },
            },
          },
        },
      },
      get: {
        operationId: "UserDocuments_get",
        description: "Get a user document",
        parameters: [
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/GetUserDocumentResponse",
                },
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/acceptedUserDocuments/{documentId}": {
      post: {
        operationId: "AcceptedUserDocuments_get",
        description: "Get accepted user document",
        parameters: [
          {
            name: "contractId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/GetAcceptedUserDocumentResponse",
                },
              },
            },
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                $ref: "#/components/schemas/GetAcceptedUserDocumentRequest",
              },
            },
          },
        },
      },
    },
    "/contracts/{contractId}/userdocuments/{documentId}/consentcheck/{option}":
      {
        post: {
          operationId: "UserDocumentRuntimeOptionsConsent_consentCheck",
          description: "Consent check for user document runtime option",
          parameters: [
            {
              name: "contractId",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
            {
              name: "documentId",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
            {
              name: "option",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
          ],
          responses: {
            "200": {
              description: "The request has succeeded.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: { status: { type: "string" } },
                    required: ["status"],
                  },
                },
              },
            },
          },
        },
      },
    "/userdocuments/{documentId}/checkstatus/{option}": {
      post: {
        operationId: "UserDocumentRuntimeOptions_checkStatus",
        description: "Check user document runtime option status",
        parameters: [
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
          {
            name: "option",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { status: { type: "string" } },
                  required: ["status"],
                },
              },
            },
          },
        },
      },
    },
    "/userdocuments/{documentId}/runtimeoptions/{option}/enable": {
      post: {
        operationId: "UserDocumentRuntimeOptions_enable",
        description: "Enable user document runtime option",
        parameters: [
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
          {
            name: "option",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
      },
    },
    "/userdocuments/{documentId}/runtimeoptions/{option}/disable": {
      post: {
        operationId: "UserDocumentRuntimeOptions_disable",
        description: "Disable user document runtime option",
        parameters: [
          {
            name: "documentId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
          {
            name: "option",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
      },
    },
    "/proposals/{proposalId}/historical": {
      get: {
        operationId: "Proposals_getHistorical",
        description: "Get proposal historical data",
        parameters: [
          {
            name: "proposalId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { proposal: {} },
                  required: ["proposal"],
                },
              },
            },
          },
        },
      },
    },
    "/users/proposals/{proposalId}": {
      get: {
        operationId: "UserProposals_get",
        description: "Get a user proposal",
        parameters: [
          {
            name: "proposalId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/GetUserProposalResponse",
                },
              },
            },
          },
        },
      },
      put: {
        operationId: "UserProposals_put",
        description: "Create or update a user proposal",
        parameters: [
          {
            name: "proposalId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/CreateUserProposalResponse",
                },
              },
            },
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                $ref: "#/components/schemas/CreateUserProposalRequest",
              },
            },
          },
        },
      },
    },
    "/users/proposals/{proposalId}/status": {
      get: {
        operationId: "UserProposals_getStatus",
        description: "Get user proposal status",
        parameters: [
          {
            name: "proposalId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    status: { type: "string" },
                    proposal: { $ref: "#/components/schemas/UserProposal" },
                  },
                  required: ["status", "proposal"],
                },
              },
            },
          },
        },
      },
    },
    "/users/proposals/{proposalId}/withdraw": {
      post: {
        operationId: "UserProposals_withdraw",
        description: "Withdraw a user proposal",
        parameters: [
          {
            name: "proposalId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
      },
    },
    "/users/proposals/{proposalId}/ballots/submit": {
      post: {
        operationId: "UserProposals_submitBallot",
        description: "Submit ballot for user proposal",
        parameters: [
          {
            name: "proposalId",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                $ref: "#/components/schemas/SubmitUserProposalBallotRequest",
              },
            },
          },
        },
      },
    },
    "/oidc/.well-known/openid-configuration": {
      get: {
        operationId: "Oidc_getConfiguration",
        description: "Get OIDC configuration",
        parameters: [],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { configuration: {} },
                  required: ["configuration"],
                },
              },
            },
          },
        },
      },
    },
    "/oidc/keys": {
      get: {
        operationId: "Oidc_getJwks",
        description: "Get JWKS (JSON Web Key Set)",
        parameters: [],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { keys: { type: "array", items: {} } },
                  required: ["keys"],
                },
              },
            },
          },
        },
      },
    },
    "/oidc/generateSigningKey": {
      post: {
        operationId: "Oidc_generateSigningKey",
        description: "Generate OIDC signing key",
        parameters: [],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
      },
    },
    "/oidc/setIssuerUrl": {
      post: {
        operationId: "Oidc_setIssuerUrl",
        description: "Set OIDC issuer URL",
        parameters: [],
        responses: {
          "204": {
            description:
              "There is no content to send for this request, but the headers may be useful. ",
          },
        },
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { issuerUrl: { type: "string" } },
                required: ["issuerUrl"],
              },
            },
          },
        },
      },
    },
    "/oidc/issuerInfo": {
      get: {
        operationId: "Oidc_getIssuerInfo",
        description: "Get OIDC issuer information",
        parameters: [],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    issuerUrl: { type: "string" },
                    proposalIds: { type: "array", items: { type: "string" } },
                  },
                  required: ["issuerUrl", "proposalIds"],
                },
              },
            },
          },
        },
      },
    },
    "/runtimeoptions/checkstatus/{option}": {
      post: {
        operationId: "RuntimeOptions_checkStatus",
        description: "Check runtime option status",
        parameters: [
          {
            name: "option",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          "200": {
            description: "The request has succeeded.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { status: { type: "string" } },
                  required: ["status"],
                },
              },
            },
          },
        },
      },
    },
  },
  components: {
    schemas: {
      ListContractResponse: {
        type: "object",
        required: ["id"],
        properties: { id: { type: "string", description: "Contract ID" } },
        description: "List contract response",
      },
      ListContractsResponse: {
        type: "object",
        required: ["value"],
        properties: {
          value: {
            type: "array",
            items: { $ref: "#/components/schemas/ListContractResponse" },
            description: "Array of contracts",
          },
        },
        description: "List contracts response",
      },
      PutContractRequest: {
        type: "object",
        required: ["version", "data"],
        properties: {
          version: { type: "string", description: "Contract version" },
          data: { description: "Contract data" },
        },
        description: "Put contract request",
      },
      MemberVote: {
        type: "object",
        required: ["memberId", "vote"],
        properties: {
          memberId: { type: "string", description: "Member ID" },
          vote: { type: "boolean", description: "Vote value" },
        },
        description: "Member vote",
      },
      GetContractResponse: {
        type: "object",
        required: ["id", "version", "data", "state", "proposalId"],
        properties: {
          id: { type: "string", description: "Contract ID" },
          version: { type: "string", description: "Contract version" },
          data: { description: "Contract data" },
          state: { type: "string", description: "Contract state" },
          proposalId: { type: "string", description: "Proposal ID" },
          finalVotes: {
            type: "array",
            items: { $ref: "#/components/schemas/MemberVote" },
            description: "Final votes",
          },
        },
        description: "Get contract response",
      },
      Event: {
        type: "object",
        required: [
          "timestamp",
          "timestamp_iso",
          "scope",
          "id",
          "seqno",
          "data",
        ],
        properties: {
          timestamp: { type: "string", description: "Event timestamp" },
          timestamp_iso: {
            type: "string",
            description: "Event timestamp ISO format",
          },
          scope: { type: "string", description: "Event scope" },
          id: { type: "string", description: "Event ID" },
          seqno: {
            type: "integer",
            format: "int32",
            description: "Sequence number",
          },
          data: { description: "Event data" },
        },
        description: "Event",
      },
      GetEventsResponse: {
        type: "object",
        required: ["value"],
        properties: {
          nextLink: { type: "string", description: "Next link for pagination" },
          value: {
            type: "array",
            items: { $ref: "#/components/schemas/Event" },
            description: "Array of events",
          },
        },
        description: "Get events response",
      },
      SnpEvidence: {
        type: "object",
        required: ["evidence", "endorsements", "uvm_endorsements"],
        properties: {
          evidence: { type: "string", description: "Base64 encoded evidence" },
          endorsements: {
            type: "string",
            description: "Base64 encoded endorsements",
          },
          uvm_endorsements: {
            type: "string",
            description: "Base64 encoded UVM endorsements",
          },
          endorsed_tcb: { type: "string", description: "Endorsed TCB version" },
        },
        description: "SNP attestation evidence",
      },
      Sign: {
        type: "object",
        required: ["signature", "publicKey"],
        properties: {
          signature: { type: "string", description: "Signature value" },
          publicKey: { type: "string", description: "PEM encoded public key" },
        },
        description: "Digital signature information",
      },
      PutEventRequest: {
        type: "object",
        required: ["timestamp", "attestation", "sign", "data"],
        properties: {
          timestamp: { type: "string", description: "Event timestamp" },
          attestation: {
            allOf: [{ $ref: "#/components/schemas/SnpEvidence" }],
            description: "Attestation evidence",
          },
          sign: {
            allOf: [{ $ref: "#/components/schemas/Sign" }],
            description: "Signature",
          },
          data: { description: "Event data" },
        },
        description: "Put event request",
      },
      ListSecretResponse: {
        type: "object",
        required: ["secretId"],
        properties: { secretId: { type: "string", description: "Secret ID" } },
        description: "List secret response",
      },
      ListSecretsResponse: {
        type: "object",
        required: ["value"],
        properties: {
          value: {
            type: "array",
            items: { $ref: "#/components/schemas/ListSecretResponse" },
            description: "Array of secrets",
          },
        },
        description: "List secrets response",
      },
      PutSecretResponse: {
        type: "object",
        required: ["secretId"],
        properties: { secretId: { type: "string", description: "Secret ID" } },
        description: "Put secret response",
      },
      PutSecretByMemberUserRequest: {
        type: "object",
        required: ["value"],
        properties: { value: { type: "string", description: "Secret value" } },
        description: "Put secret by member/user request",
      },
      Encrypt: {
        type: "object",
        required: ["publicKey"],
        properties: {
          publicKey: { type: "string", description: "PEM encoded public key" },
        },
        description: "Encryption information",
      },
      PutSecretByCleanRoomRequest: {
        type: "object",
        required: ["attestation", "encrypt", "sign", "data"],
        properties: {
          attestation: {
            allOf: [{ $ref: "#/components/schemas/SnpEvidence" }],
            description: "Attestation evidence",
          },
          encrypt: {
            allOf: [{ $ref: "#/components/schemas/Encrypt" }],
            description: "Encryption info",
          },
          sign: {
            allOf: [{ $ref: "#/components/schemas/Sign" }],
            description: "Signature",
          },
          data: { type: "string", description: "Encrypted data" },
        },
        description: "Put secret by clean room request",
      },
      GetSecretResponse: {
        type: "object",
        required: ["value"],
        properties: { value: { type: "string", description: "Secret value" } },
        description: "Get secret response",
      },
      GetSecretRequest: {
        type: "object",
        required: ["attestation", "encrypt"],
        properties: {
          attestation: {
            allOf: [{ $ref: "#/components/schemas/SnpEvidence" }],
            description: "Attestation evidence",
          },
          encrypt: {
            allOf: [{ $ref: "#/components/schemas/Encrypt" }],
            description: "Encryption info",
          },
        },
        description: "Get secret request",
      },
      GenerateEndorsedCertRequest: {
        type: "object",
        required: ["attestation", "encrypt", "sign", "data"],
        properties: {
          attestation: {
            allOf: [{ $ref: "#/components/schemas/SnpEvidence" }],
            description: "Attestation evidence",
          },
          encrypt: {
            allOf: [{ $ref: "#/components/schemas/Encrypt" }],
            description: "Encryption info",
          },
          sign: {
            allOf: [{ $ref: "#/components/schemas/Sign" }],
            description: "Signature",
          },
          data: { type: "string", description: "Encrypted request data" },
        },
        description: "Generate endorsed cert request",
      },
      CAInfo: {
        type: "object",
        required: ["enabled", "proposalIds"],
        properties: {
          enabled: { type: "boolean", description: "CA enabled" },
          caCert: { type: "string", description: "CA certificate" },
          publicKey: { type: "string", description: "Public key" },
          proposalIds: {
            type: "array",
            items: { type: "string" },
            description: "Proposal IDs",
          },
        },
        description: "CA info",
      },
      ListMemberDocumentResponse: {
        type: "object",
        required: ["id"],
        properties: { id: { type: "string", description: "Document ID" } },
        description: "List member document response",
      },
      PutMemberDocumentRequest: {
        type: "object",
        required: ["version", "contractId", "data"],
        properties: {
          version: { type: "string", description: "Document version" },
          contractId: { type: "string", description: "Contract ID" },
          data: { description: "Document data" },
        },
        description: "Put member document request",
      },
      GetMemberDocumentResponse: {
        type: "object",
        required: [
          "id",
          "contractId",
          "version",
          "data",
          "state",
          "proposalId",
        ],
        properties: {
          id: { type: "string", description: "Document ID" },
          contractId: { type: "string", description: "Contract ID" },
          version: { type: "string", description: "Document version" },
          data: { description: "Document data" },
          state: { type: "string", description: "Document state" },
          proposalId: { type: "string", description: "Proposal ID" },
          finalVotes: {
            type: "array",
            items: { $ref: "#/components/schemas/MemberVote" },
            description: "Final votes",
          },
        },
        description: "Get member document response",
      },
      GetAcceptedMemberDocumentResponse: {
        type: "object",
        required: ["value"],
        properties: {
          value: {
            type: "string",
            description: "Encrypted GetDocumentResponse content",
          },
        },
        description: "Get accepted member document response",
      },
      GetAcceptedMemberDocumentRequest: {
        type: "object",
        required: ["attestation", "encrypt"],
        properties: {
          attestation: {
            allOf: [{ $ref: "#/components/schemas/SnpEvidence" }],
            description: "Attestation evidence",
          },
          encrypt: {
            allOf: [{ $ref: "#/components/schemas/Encrypt" }],
            description: "Encryption info",
          },
        },
        description: "Get accepted member document request",
      },
      ListUserDocumentResponse: {
        type: "object",
        required: ["id", "labels"],
        properties: {
          id: { type: "string", description: "Document ID" },
          labels: {
            type: "object",
            additionalProperties: { type: "string" },
            description: "Labels",
          },
        },
        description: "List user document response",
      },
      ListUserDocumentsResponse: {
        type: "object",
        required: ["value"],
        properties: {
          value: {
            type: "array",
            items: { $ref: "#/components/schemas/ListUserDocumentResponse" },
            description: "Array of user documents",
          },
        },
        description: "List user documents response",
      },
      UserProposalApprover: {
        type: "object",
        required: ["approverId", "approverIdType"],
        properties: {
          approverId: { type: "string", description: "Approver ID" },
          approverIdType: { type: "string", description: "Approver ID type" },
        },
        description: "User proposal approver",
      },
      PutUserDocumentRequest: {
        type: "object",
        required: ["version", "contractId", "data", "labels"],
        properties: {
          version: { type: "string", description: "Document version" },
          contractId: { type: "string", description: "Contract ID" },
          approvers: {
            type: "array",
            items: { $ref: "#/components/schemas/UserProposalApprover" },
            description: "Approvers",
          },
          data: { description: "Document data" },
          labels: {
            type: "object",
            additionalProperties: { type: "string" },
            description: "Labels",
          },
        },
        description: "Put user document request",
      },
      UserVote: {
        type: "object",
        required: ["approverId", "ballot"],
        properties: {
          approverId: { type: "string", description: "Approver ID" },
          ballot: { type: "string", description: "Ballot value" },
        },
        description: "User vote",
      },
      GetUserDocumentResponse: {
        type: "object",
        required: [
          "id",
          "contractId",
          "version",
          "data",
          "labels",
          "state",
          "proposalId",
          "proposerId",
        ],
        properties: {
          id: { type: "string", description: "Document ID" },
          contractId: { type: "string", description: "Contract ID" },
          version: { type: "string", description: "Document version" },
          approvers: {
            type: "array",
            items: { $ref: "#/components/schemas/UserProposalApprover" },
            description: "Approvers",
          },
          data: { description: "Document data" },
          labels: {
            type: "object",
            additionalProperties: { type: "string" },
            description: "Labels",
          },
          state: { type: "string", description: "Document state" },
          proposalId: { type: "string", description: "Proposal ID" },
          proposerId: { type: "string", description: "Proposer ID" },
          finalVotes: {
            type: "array",
            items: { $ref: "#/components/schemas/UserVote" },
            description: "Final votes",
          },
        },
        description: "Get user document response",
      },
      GetAcceptedUserDocumentResponse: {
        type: "object",
        required: ["value"],
        properties: {
          value: {
            type: "string",
            description: "Encrypted GetUserDocumentResponse content",
          },
        },
        description: "Get accepted user document response",
      },
      GetAcceptedUserDocumentRequest: {
        type: "object",
        required: ["attestation", "encrypt"],
        properties: {
          attestation: {
            allOf: [{ $ref: "#/components/schemas/SnpEvidence" }],
            description: "Attestation evidence",
          },
          encrypt: {
            allOf: [{ $ref: "#/components/schemas/Encrypt" }],
            description: "Encryption info",
          },
        },
        description: "Get accepted user document request",
      },
      GetUserProposalResponse: {
        type: "object",
        required: ["proposalId", "name", "approvers", "args"],
        properties: {
          proposalId: { type: "string", description: "Proposal ID" },
          name: { type: "string", description: "Proposal name" },
          approvers: {
            type: "array",
            items: { $ref: "#/components/schemas/UserProposalApprover" },
            description: "Approvers",
          },
          args: { description: "Proposal arguments" },
        },
        description: "Get user proposal response",
      },
      CreateUserProposalResponse: {
        type: "object",
        required: ["proposalId"],
        properties: {
          proposalId: { type: "string", description: "Proposal ID" },
        },
        description: "Create user proposal response",
      },
      CreateUserProposalRequest: {
        type: "object",
        required: ["name", "args"],
        properties: {
          name: { type: "string", description: "Proposal name" },
          approvers: {
            type: "array",
            items: { $ref: "#/components/schemas/UserProposalApprover" },
            description: "Approvers",
          },
          args: { description: "Proposal arguments" },
        },
        description: "Create user proposal request",
      },
      UserProposal: {
        type: "object",
        required: ["seqno", "proposalState", "proposalId"],
        properties: {
          seqno: {
            type: "integer",
            format: "int32",
            description: "Sequence number",
          },
          proposalState: { type: "string", description: "Proposal state" },
          proposalId: { type: "string", description: "Proposal ID" },
        },
        description: "User proposal",
      },
      SubmitUserProposalBallotRequest: {
        type: "object",
        required: ["ballot"],
        properties: { ballot: { type: "string", description: "Ballot value" } },
        description: "Submit user proposal ballot request",
      },
    },
  },
};
