// Generated by Microsoft TypeSpec

import * as http from "node:http";

import * as serverRaw from "./operations/server-raw.js";

import { parseHeaderValueParameters } from "../helpers/header.js";

import {
  Contracts,
  ContractRuntimeOptions,
  Events,
  Secrets,
  CleanRoomPolicy,
  Deployment,
  OAuth,
  CertificateAuthority,
  MemberDocuments,
  AcceptedMemberDocuments,
  UserIdentities,
  ContractUsers,
  UserInvitations,
  UserDocuments,
  AcceptedUserDocuments,
  UserDocumentRuntimeOptionsConsent,
  UserDocumentRuntimeOptions,
  Proposals,
  UserProposals,
  Oidc,
  RuntimeOptions,
} from "../models/all/cleanroom/governance.js";

import {
  RouterOptions,
  createPolicyChain,
  createPolicyChainForRoute,
  HttpContext,
} from "../helpers/router.js";

export interface GovernanceRouter {
  /**
   * Dispatches the request to the appropriate service based on the request path.
   *
   * This member function may be used directly as a handler for a Node HTTP server.
   *
   * @param request - The incoming HTTP request.
   * @param response - The outgoing HTTP response.
   */
  dispatch(request: http.IncomingMessage, response: http.ServerResponse): void;
}

export function createGovernanceRouter(
  contracts: Contracts,
  contractRuntimeOptions: ContractRuntimeOptions,
  events: Events,
  secrets: Secrets,
  cleanRoomPolicy: CleanRoomPolicy,
  deployment: Deployment,
  oAuth: OAuth,
  certificateAuthority: CertificateAuthority,
  memberDocuments: MemberDocuments,
  acceptedMemberDocuments: AcceptedMemberDocuments,
  userIdentities: UserIdentities,
  contractUsers: ContractUsers,
  userInvitations: UserInvitations,
  userDocuments: UserDocuments,
  acceptedUserDocuments: AcceptedUserDocuments,
  userDocumentRuntimeOptionsConsent: UserDocumentRuntimeOptionsConsent,
  userDocumentRuntimeOptions: UserDocumentRuntimeOptions,
  proposals: Proposals,
  userProposals: UserProposals,
  oidc: Oidc,
  runtimeOptions: RuntimeOptions,
  options: RouterOptions<{
    contracts: Contracts<HttpContext>;
    contractRuntimeOptions: ContractRuntimeOptions<HttpContext>;
    events: Events<HttpContext>;
    secrets: Secrets<HttpContext>;
    cleanRoomPolicy: CleanRoomPolicy<HttpContext>;
    deployment: Deployment<HttpContext>;
    oAuth: OAuth<HttpContext>;
    certificateAuthority: CertificateAuthority<HttpContext>;
    memberDocuments: MemberDocuments<HttpContext>;
    acceptedMemberDocuments: AcceptedMemberDocuments<HttpContext>;
    userIdentities: UserIdentities<HttpContext>;
    contractUsers: ContractUsers<HttpContext>;
    userInvitations: UserInvitations<HttpContext>;
    userDocuments: UserDocuments<HttpContext>;
    acceptedUserDocuments: AcceptedUserDocuments<HttpContext>;
    userDocumentRuntimeOptionsConsent: UserDocumentRuntimeOptionsConsent<HttpContext>;
    userDocumentRuntimeOptions: UserDocumentRuntimeOptions<HttpContext>;
    proposals: Proposals<HttpContext>;
    userProposals: UserProposals<HttpContext>;
    oidc: Oidc<HttpContext>;
    runtimeOptions: RuntimeOptions<HttpContext>;
  }> = {},
): GovernanceRouter {
  const __onRequestNotFound_254 =
    options.onRequestNotFound ??
    ((ctx) => {
      ctx.response.statusCode = 404;
      ctx.response.setHeader("Content-Type", "text/plain");
      ctx.response.end("Not Found");
    });

  const __onInvalidRequest_255 =
    options.onInvalidRequest ??
    ((ctx, route, error) => {
      ctx.response.statusCode = 400;
      ctx.response.setHeader("Content-Type", "application/json");
      ctx.response.end(JSON.stringify({ error }));
    });

  const __onInternalError_256 =
    options.onInternalError ??
    ((ctx, error) => {
      ctx.response.statusCode = 500;
      ctx.response.setHeader("Content-Type", "text/plain");
      ctx.response.end("Internal server error.");
    });

  const __routePolicies_257 = options.routePolicies ?? {};

  const __routeHandlers_258 = {
    contracts_list: createPolicyChainForRoute(
      "contractsListDispatch",
      __routePolicies_257,
      "contracts",
      "list",
      serverRaw.contracts_list,
    ),
    contracts_put: createPolicyChainForRoute(
      "contractsPutDispatch",
      __routePolicies_257,
      "contracts",
      "put",
      serverRaw.contracts_put,
    ),
    contracts_get: createPolicyChainForRoute(
      "contractsGetDispatch",
      __routePolicies_257,
      "contracts",
      "get",
      serverRaw.contracts_get,
    ),
    contract_runtime_options_check_execution_status: createPolicyChainForRoute(
      "contractRuntimeOptionsCheckExecutionStatusDispatch",
      __routePolicies_257,
      "contractRuntimeOptions",
      "checkExecutionStatus",
      serverRaw.contract_runtime_options_check_execution_status,
    ),
    contract_runtime_options_check_logging_status: createPolicyChainForRoute(
      "contractRuntimeOptionsCheckLoggingStatusDispatch",
      __routePolicies_257,
      "contractRuntimeOptions",
      "checkLoggingStatus",
      serverRaw.contract_runtime_options_check_logging_status,
    ),
    contract_runtime_options_check_telemetry_status: createPolicyChainForRoute(
      "contractRuntimeOptionsCheckTelemetryStatusDispatch",
      __routePolicies_257,
      "contractRuntimeOptions",
      "checkTelemetryStatus",
      serverRaw.contract_runtime_options_check_telemetry_status,
    ),
    contract_runtime_options_consent_check_execution: createPolicyChainForRoute(
      "contractRuntimeOptionsConsentCheckExecutionDispatch",
      __routePolicies_257,
      "contractRuntimeOptions",
      "consentCheckExecution",
      serverRaw.contract_runtime_options_consent_check_execution,
    ),
    contract_runtime_options_consent_check_logging: createPolicyChainForRoute(
      "contractRuntimeOptionsConsentCheckLoggingDispatch",
      __routePolicies_257,
      "contractRuntimeOptions",
      "consentCheckLogging",
      serverRaw.contract_runtime_options_consent_check_logging,
    ),
    contract_runtime_options_consent_check_telemetry: createPolicyChainForRoute(
      "contractRuntimeOptionsConsentCheckTelemetryDispatch",
      __routePolicies_257,
      "contractRuntimeOptions",
      "consentCheckTelemetry",
      serverRaw.contract_runtime_options_consent_check_telemetry,
    ),
    contract_runtime_options_enable: createPolicyChainForRoute(
      "contractRuntimeOptionsEnableDispatch",
      __routePolicies_257,
      "contractRuntimeOptions",
      "enable",
      serverRaw.contract_runtime_options_enable,
    ),
    contract_runtime_options_disable: createPolicyChainForRoute(
      "contractRuntimeOptionsDisableDispatch",
      __routePolicies_257,
      "contractRuntimeOptions",
      "disable",
      serverRaw.contract_runtime_options_disable,
    ),
    events_get: createPolicyChainForRoute(
      "eventsGetDispatch",
      __routePolicies_257,
      "events",
      "get",
      serverRaw.events_get,
    ),
    events_put: createPolicyChainForRoute(
      "eventsPutDispatch",
      __routePolicies_257,
      "events",
      "put",
      serverRaw.events_put,
    ),
    secrets_list: createPolicyChainForRoute(
      "secretsListDispatch",
      __routePolicies_257,
      "secrets",
      "list",
      serverRaw.secrets_list,
    ),
    secrets_put: createPolicyChainForRoute(
      "secretsPutDispatch",
      __routePolicies_257,
      "secrets",
      "put",
      serverRaw.secrets_put,
    ),
    secrets_get: createPolicyChainForRoute(
      "secretsGetDispatch",
      __routePolicies_257,
      "secrets",
      "get",
      serverRaw.secrets_get,
    ),
    clean_room_policy_get: createPolicyChainForRoute(
      "cleanRoomPolicyGetDispatch",
      __routePolicies_257,
      "cleanRoomPolicy",
      "get",
      serverRaw.clean_room_policy_get,
    ),
    clean_room_policy_list_delegates: createPolicyChainForRoute(
      "cleanRoomPolicyListDelegatesDispatch",
      __routePolicies_257,
      "cleanRoomPolicy",
      "listDelegates",
      serverRaw.clean_room_policy_list_delegates,
    ),
    clean_room_policy_get_delegate: createPolicyChainForRoute(
      "cleanRoomPolicyGetDelegateDispatch",
      __routePolicies_257,
      "cleanRoomPolicy",
      "getDelegate",
      serverRaw.clean_room_policy_get_delegate,
    ),
    clean_room_policy_set_delegate: createPolicyChainForRoute(
      "cleanRoomPolicySetDelegateDispatch",
      __routePolicies_257,
      "cleanRoomPolicy",
      "setDelegate",
      serverRaw.clean_room_policy_set_delegate,
    ),
    deployment_get_spec: createPolicyChainForRoute(
      "deploymentGetSpecDispatch",
      __routePolicies_257,
      "deployment",
      "getSpec",
      serverRaw.deployment_get_spec,
    ),
    deployment_get_info: createPolicyChainForRoute(
      "deploymentGetInfoDispatch",
      __routePolicies_257,
      "deployment",
      "getInfo",
      serverRaw.deployment_get_info,
    ),
    o_auth_get_token: createPolicyChainForRoute(
      "oAuthGetTokenDispatch",
      __routePolicies_257,
      "oAuth",
      "getToken",
      serverRaw.o_auth_get_token,
    ),
    certificate_authority_generate_signing_key: createPolicyChainForRoute(
      "certificateAuthorityGenerateSigningKeyDispatch",
      __routePolicies_257,
      "certificateAuthority",
      "generateSigningKey",
      serverRaw.certificate_authority_generate_signing_key,
    ),
    certificate_authority_generate_endorsed_cert: createPolicyChainForRoute(
      "certificateAuthorityGenerateEndorsedCertDispatch",
      __routePolicies_257,
      "certificateAuthority",
      "generateEndorsedCert",
      serverRaw.certificate_authority_generate_endorsed_cert,
    ),
    certificate_authority_get_info: createPolicyChainForRoute(
      "certificateAuthorityGetInfoDispatch",
      __routePolicies_257,
      "certificateAuthority",
      "getInfo",
      serverRaw.certificate_authority_get_info,
    ),
    member_documents_list: createPolicyChainForRoute(
      "memberDocumentsListDispatch",
      __routePolicies_257,
      "memberDocuments",
      "list",
      serverRaw.member_documents_list,
    ),
    member_documents_put: createPolicyChainForRoute(
      "memberDocumentsPutDispatch",
      __routePolicies_257,
      "memberDocuments",
      "put",
      serverRaw.member_documents_put,
    ),
    member_documents_get: createPolicyChainForRoute(
      "memberDocumentsGetDispatch",
      __routePolicies_257,
      "memberDocuments",
      "get",
      serverRaw.member_documents_get,
    ),
    accepted_member_documents_get: createPolicyChainForRoute(
      "acceptedMemberDocumentsGetDispatch",
      __routePolicies_257,
      "acceptedMemberDocuments",
      "get",
      serverRaw.accepted_member_documents_get,
    ),
    user_identities_list: createPolicyChainForRoute(
      "userIdentitiesListDispatch",
      __routePolicies_257,
      "userIdentities",
      "list",
      serverRaw.user_identities_list,
    ),
    user_identities_get: createPolicyChainForRoute(
      "userIdentitiesGetDispatch",
      __routePolicies_257,
      "userIdentities",
      "get",
      serverRaw.user_identities_get,
    ),
    contract_users_is_active: createPolicyChainForRoute(
      "contractUsersIsActiveDispatch",
      __routePolicies_257,
      "contractUsers",
      "isActive",
      serverRaw.contract_users_is_active,
    ),
    user_invitations_list: createPolicyChainForRoute(
      "userInvitationsListDispatch",
      __routePolicies_257,
      "userInvitations",
      "list",
      serverRaw.user_invitations_list,
    ),
    user_invitations_get: createPolicyChainForRoute(
      "userInvitationsGetDispatch",
      __routePolicies_257,
      "userInvitations",
      "get",
      serverRaw.user_invitations_get,
    ),
    user_invitations_accept: createPolicyChainForRoute(
      "userInvitationsAcceptDispatch",
      __routePolicies_257,
      "userInvitations",
      "accept",
      serverRaw.user_invitations_accept,
    ),
    user_documents_list: createPolicyChainForRoute(
      "userDocumentsListDispatch",
      __routePolicies_257,
      "userDocuments",
      "list",
      serverRaw.user_documents_list,
    ),
    user_documents_put: createPolicyChainForRoute(
      "userDocumentsPutDispatch",
      __routePolicies_257,
      "userDocuments",
      "put",
      serverRaw.user_documents_put,
    ),
    user_documents_get: createPolicyChainForRoute(
      "userDocumentsGetDispatch",
      __routePolicies_257,
      "userDocuments",
      "get",
      serverRaw.user_documents_get,
    ),
    accepted_user_documents_get: createPolicyChainForRoute(
      "acceptedUserDocumentsGetDispatch",
      __routePolicies_257,
      "acceptedUserDocuments",
      "get",
      serverRaw.accepted_user_documents_get,
    ),
    user_document_runtime_options_consent_consent_check:
      createPolicyChainForRoute(
        "userDocumentRuntimeOptionsConsentConsentCheckDispatch",
        __routePolicies_257,
        "userDocumentRuntimeOptionsConsent",
        "consentCheck",
        serverRaw.user_document_runtime_options_consent_consent_check,
      ),
    user_document_runtime_options_check_status: createPolicyChainForRoute(
      "userDocumentRuntimeOptionsCheckStatusDispatch",
      __routePolicies_257,
      "userDocumentRuntimeOptions",
      "checkStatus",
      serverRaw.user_document_runtime_options_check_status,
    ),
    user_document_runtime_options_enable: createPolicyChainForRoute(
      "userDocumentRuntimeOptionsEnableDispatch",
      __routePolicies_257,
      "userDocumentRuntimeOptions",
      "enable",
      serverRaw.user_document_runtime_options_enable,
    ),
    user_document_runtime_options_disable: createPolicyChainForRoute(
      "userDocumentRuntimeOptionsDisableDispatch",
      __routePolicies_257,
      "userDocumentRuntimeOptions",
      "disable",
      serverRaw.user_document_runtime_options_disable,
    ),
    proposals_get_historical: createPolicyChainForRoute(
      "proposalsGetHistoricalDispatch",
      __routePolicies_257,
      "proposals",
      "getHistorical",
      serverRaw.proposals_get_historical,
    ),
    user_proposals_get: createPolicyChainForRoute(
      "userProposalsGetDispatch",
      __routePolicies_257,
      "userProposals",
      "get",
      serverRaw.user_proposals_get,
    ),
    user_proposals_put: createPolicyChainForRoute(
      "userProposalsPutDispatch",
      __routePolicies_257,
      "userProposals",
      "put",
      serverRaw.user_proposals_put,
    ),
    user_proposals_get_status: createPolicyChainForRoute(
      "userProposalsGetStatusDispatch",
      __routePolicies_257,
      "userProposals",
      "getStatus",
      serverRaw.user_proposals_get_status,
    ),
    user_proposals_withdraw: createPolicyChainForRoute(
      "userProposalsWithdrawDispatch",
      __routePolicies_257,
      "userProposals",
      "withdraw",
      serverRaw.user_proposals_withdraw,
    ),
    user_proposals_submit_ballot: createPolicyChainForRoute(
      "userProposalsSubmitBallotDispatch",
      __routePolicies_257,
      "userProposals",
      "submitBallot",
      serverRaw.user_proposals_submit_ballot,
    ),
    oidc_get_configuration: createPolicyChainForRoute(
      "oidcGetConfigurationDispatch",
      __routePolicies_257,
      "oidc",
      "getConfiguration",
      serverRaw.oidc_get_configuration,
    ),
    oidc_get_jwks: createPolicyChainForRoute(
      "oidcGetJwksDispatch",
      __routePolicies_257,
      "oidc",
      "getJwks",
      serverRaw.oidc_get_jwks,
    ),
    oidc_generate_signing_key: createPolicyChainForRoute(
      "oidcGenerateSigningKeyDispatch",
      __routePolicies_257,
      "oidc",
      "generateSigningKey",
      serverRaw.oidc_generate_signing_key,
    ),
    oidc_set_issuer_url: createPolicyChainForRoute(
      "oidcSetIssuerUrlDispatch",
      __routePolicies_257,
      "oidc",
      "setIssuerUrl",
      serverRaw.oidc_set_issuer_url,
    ),
    oidc_get_issuer_info: createPolicyChainForRoute(
      "oidcGetIssuerInfoDispatch",
      __routePolicies_257,
      "oidc",
      "getIssuerInfo",
      serverRaw.oidc_get_issuer_info,
    ),
    runtime_options_check_status: createPolicyChainForRoute(
      "runtimeOptionsCheckStatusDispatch",
      __routePolicies_257,
      "runtimeOptions",
      "checkStatus",
      serverRaw.runtime_options_check_status,
    ),
  } as const;

  const dispatch = createPolicyChain(
    "GovernanceRouterDispatch",
    options.policies ?? [],
    async function (ctx, request, response) {
      const url = new URL(request.url!, `http://${request.headers.host}`);
      let path = url.pathname;

      if (path.length === 0) {
        return ctx.errorHandlers.onRequestNotFound(ctx);
      } else if (path.startsWith("/")) {
        path = path.slice(1);
        if (path.length === 0) {
          return ctx.errorHandlers.onRequestNotFound(ctx);
        } else if (path.startsWith("memberdocuments")) {
          path = path.slice(15);
          if (path.length === 0) {
            switch (request.method) {
              case "GET":
                return __routeHandlers_258.member_documents_list(
                  ctx,
                  memberDocuments,
                );
              default:
                return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("/")) {
            path = path.slice(1);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else {
              let __document_id_idx = path.indexOf("/");
              __document_id_idx =
                __document_id_idx === -1 ? path.length : __document_id_idx;
              const documentId = path.slice(0, __document_id_idx);
              path = path.slice(__document_id_idx);
              if (path.length === 0) {
                switch (request.method) {
                  case "PUT":
                    return __routeHandlers_258.member_documents_put(
                      ctx,
                      memberDocuments,
                      documentId,
                    );
                  case "GET":
                    return __routeHandlers_258.member_documents_get(
                      ctx,
                      memberDocuments,
                      documentId,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else {
                return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            }
          }
        } else if (path.startsWith("contracts")) {
          path = path.slice(9);
          if (path.length === 0) {
            switch (request.method) {
              case "GET":
                return __routeHandlers_258.contracts_list(ctx, contracts);
              default:
                return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("/")) {
            path = path.slice(1);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else {
              let __contract_id_idx = path.indexOf("/");
              __contract_id_idx =
                __contract_id_idx === -1 ? path.length : __contract_id_idx;
              const contractId = path.slice(0, __contract_id_idx);
              path = path.slice(__contract_id_idx);
              if (path.length === 0) {
                switch (request.method) {
                  case "PUT":
                    return __routeHandlers_258.contracts_put(
                      ctx,
                      contracts,
                      contractId,
                    );
                  case "GET":
                    return __routeHandlers_258.contracts_get(
                      ctx,
                      contracts,
                      contractId,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else if (path.startsWith("/")) {
                path = path.slice(1);
                if (path.length === 0) {
                  return ctx.errorHandlers.onRequestNotFound(ctx);
                } else if (path.startsWith("e")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("nable")) {
                    path = path.slice(5);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_258.contract_runtime_options_enable(
                            ctx,
                            contractRuntimeOptions,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("vents")) {
                    path = path.slice(5);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "GET":
                          return __routeHandlers_258.events_get(
                            ctx,
                            events,
                            contractId,
                          );
                        case "PUT":
                          return __routeHandlers_258.events_put(
                            ctx,
                            events,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  }
                } else if (path.startsWith("secrets")) {
                  path = path.slice(7);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "GET":
                        return __routeHandlers_258.secrets_list(
                          ctx,
                          secrets,
                          contractId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("/")) {
                    path = path.slice(1);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else {
                      let __secret_name_idx = path.indexOf("/");
                      __secret_name_idx =
                        __secret_name_idx === -1
                          ? path.length
                          : __secret_name_idx;
                      const secretName = path.slice(0, __secret_name_idx);
                      path = path.slice(__secret_name_idx);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "PUT":
                            return __routeHandlers_258.secrets_put(
                              ctx,
                              secrets,
                              contractId,
                              secretName,
                            );
                          case "POST":
                            return __routeHandlers_258.secrets_get(
                              ctx,
                              secrets,
                              contractId,
                              secretName,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  }
                } else if (path.startsWith("d")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("isable")) {
                    path = path.slice(6);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_258.contract_runtime_options_disable(
                            ctx,
                            contractRuntimeOptions,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("eployment")) {
                    path = path.slice(9);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else if (path.startsWith("spec")) {
                      path = path.slice(4);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "GET":
                            return __routeHandlers_258.deployment_get_spec(
                              ctx,
                              deployment,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("info")) {
                      path = path.slice(4);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "GET":
                            return __routeHandlers_258.deployment_get_info(
                              ctx,
                              deployment,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  }
                } else if (path.startsWith("oauth/token")) {
                  path = path.slice(11);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "POST":
                        return __routeHandlers_258.o_auth_get_token(
                          ctx,
                          oAuth,
                          contractId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("c")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("heckstatus/")) {
                    path = path.slice(11);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else if (path.startsWith("execution")) {
                      path = path.slice(9);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.contract_runtime_options_check_execution_status(
                              ctx,
                              contractRuntimeOptions,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("logging")) {
                      path = path.slice(7);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.contract_runtime_options_check_logging_status(
                              ctx,
                              contractRuntimeOptions,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("telemetry")) {
                      path = path.slice(9);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.contract_runtime_options_check_telemetry_status(
                              ctx,
                              contractRuntimeOptions,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  } else if (path.startsWith("onsentcheck/")) {
                    path = path.slice(12);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else if (path.startsWith("execution")) {
                      path = path.slice(9);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.contract_runtime_options_consent_check_execution(
                              ctx,
                              contractRuntimeOptions,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("logging")) {
                      path = path.slice(7);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.contract_runtime_options_consent_check_logging(
                              ctx,
                              contractRuntimeOptions,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("telemetry")) {
                      path = path.slice(9);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.contract_runtime_options_consent_check_telemetry(
                              ctx,
                              contractRuntimeOptions,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  } else if (path.startsWith("leanroompolicy")) {
                    path = path.slice(14);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "GET":
                          return __routeHandlers_258.clean_room_policy_get(
                            ctx,
                            cleanRoomPolicy,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("/delegates")) {
                      path = path.slice(10);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "GET":
                            return __routeHandlers_258.clean_room_policy_list_delegates(
                              ctx,
                              cleanRoomPolicy,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else if (path.startsWith("/")) {
                        path = path.slice(1);
                        if (path.length === 0) {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        } else {
                          let __delegate_type_idx = path.indexOf("/");
                          __delegate_type_idx =
                            __delegate_type_idx === -1
                              ? path.length
                              : __delegate_type_idx;
                          const delegateType = path.slice(
                            0,
                            __delegate_type_idx,
                          );
                          path = path.slice(__delegate_type_idx);
                          if (path.length === 0) {
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                          } else if (path.startsWith("/")) {
                            path = path.slice(1);
                            if (path.length === 0) {
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                            } else {
                              let __delegate_id_idx = path.indexOf("/");
                              __delegate_id_idx =
                                __delegate_id_idx === -1
                                  ? path.length
                                  : __delegate_id_idx;
                              const delegateId = path.slice(
                                0,
                                __delegate_id_idx,
                              );
                              path = path.slice(__delegate_id_idx);
                              if (path.length === 0) {
                                switch (request.method) {
                                  case "GET":
                                    return __routeHandlers_258.clean_room_policy_get_delegate(
                                      ctx,
                                      cleanRoomPolicy,
                                      contractId,
                                      delegateType,
                                      delegateId,
                                    );
                                  case "POST":
                                    return __routeHandlers_258.clean_room_policy_set_delegate(
                                      ctx,
                                      cleanRoomPolicy,
                                      contractId,
                                      delegateType,
                                      delegateId,
                                    );
                                  default:
                                    return ctx.errorHandlers.onRequestNotFound(
                                      ctx,
                                    );
                                }
                              } else {
                                return ctx.errorHandlers.onRequestNotFound(ctx);
                              }
                            }
                          }
                        }
                      }
                    }
                  } else if (path.startsWith("a/")) {
                    path = path.slice(2);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else if (path.startsWith("generate")) {
                      path = path.slice(8);
                      if (path.length === 0) {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      } else if (path.startsWith("SigningKey")) {
                        path = path.slice(10);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_258.certificate_authority_generate_signing_key(
                                ctx,
                                certificateAuthority,
                                contractId,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else if (path.startsWith("EndorsedCert")) {
                        path = path.slice(12);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_258.certificate_authority_generate_endorsed_cert(
                                ctx,
                                certificateAuthority,
                                contractId,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      }
                    } else if (path.startsWith("info")) {
                      path = path.slice(4);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "GET":
                            return __routeHandlers_258.certificate_authority_get_info(
                              ctx,
                              certificateAuthority,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  }
                } else if (path.startsWith("accepted")) {
                  path = path.slice(8);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("MemberDocuments/")) {
                    path = path.slice(16);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else {
                      let __document_id_idx = path.indexOf("/");
                      __document_id_idx =
                        __document_id_idx === -1
                          ? path.length
                          : __document_id_idx;
                      const documentId = path.slice(0, __document_id_idx);
                      path = path.slice(__document_id_idx);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.accepted_member_documents_get(
                              ctx,
                              acceptedMemberDocuments,
                              contractId,
                              documentId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  } else if (path.startsWith("UserDocuments/")) {
                    path = path.slice(14);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else {
                      let __document_id_idx = path.indexOf("/");
                      __document_id_idx =
                        __document_id_idx === -1
                          ? path.length
                          : __document_id_idx;
                      const documentId = path.slice(0, __document_id_idx);
                      path = path.slice(__document_id_idx);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.accepted_user_documents_get(
                              ctx,
                              acceptedUserDocuments,
                              contractId,
                              documentId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  }
                } else if (path.startsWith("user")) {
                  path = path.slice(4);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("s/isactive")) {
                    path = path.slice(10);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_258.contract_users_is_active(
                            ctx,
                            contractUsers,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("documents/")) {
                    path = path.slice(10);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else {
                      let __document_id_idx = path.indexOf("/");
                      __document_id_idx =
                        __document_id_idx === -1
                          ? path.length
                          : __document_id_idx;
                      const documentId = path.slice(0, __document_id_idx);
                      path = path.slice(__document_id_idx);
                      if (path.length === 0) {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      } else if (path.startsWith("/consentcheck/")) {
                        path = path.slice(14);
                        if (path.length === 0) {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        } else {
                          let __option_idx = path.indexOf("/");
                          __option_idx =
                            __option_idx === -1 ? path.length : __option_idx;
                          const option = path.slice(0, __option_idx);
                          path = path.slice(__option_idx);
                          if (path.length === 0) {
                            switch (request.method) {
                              case "POST":
                                return __routeHandlers_258.user_document_runtime_options_consent_consent_check(
                                  ctx,
                                  userDocumentRuntimeOptionsConsent,
                                  contractId,
                                  documentId,
                                  option,
                                );
                              default:
                                return ctx.errorHandlers.onRequestNotFound(ctx);
                            }
                          } else {
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        } else if (path.startsWith("proposals/")) {
          path = path.slice(10);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else {
            let __proposal_id_idx = path.indexOf("/");
            __proposal_id_idx =
              __proposal_id_idx === -1 ? path.length : __proposal_id_idx;
            const proposalId = path.slice(0, __proposal_id_idx);
            path = path.slice(__proposal_id_idx);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else if (path.startsWith("/historical")) {
              path = path.slice(11);
              if (path.length === 0) {
                switch (request.method) {
                  case "GET":
                    return __routeHandlers_258.proposals_get_historical(
                      ctx,
                      proposals,
                      proposalId,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else {
                return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            }
          }
        } else if (path.startsWith("user")) {
          path = path.slice(4);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else if (path.startsWith("documents")) {
            path = path.slice(9);
            if (path.length === 0) {
              switch (request.method) {
                case "GET":
                  return __routeHandlers_258.user_documents_list(
                    ctx,
                    userDocuments,
                  );
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else if (path.startsWith("/")) {
              path = path.slice(1);
              if (path.length === 0) {
                return ctx.errorHandlers.onRequestNotFound(ctx);
              } else {
                let __document_id_idx = path.indexOf("/");
                __document_id_idx =
                  __document_id_idx === -1 ? path.length : __document_id_idx;
                const documentId = path.slice(0, __document_id_idx);
                path = path.slice(__document_id_idx);
                if (path.length === 0) {
                  switch (request.method) {
                    case "PUT":
                      return __routeHandlers_258.user_documents_put(
                        ctx,
                        userDocuments,
                        documentId,
                      );
                    case "GET":
                      return __routeHandlers_258.user_documents_get(
                        ctx,
                        userDocuments,
                        documentId,
                      );
                    default:
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("/")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("checkstatus/")) {
                    path = path.slice(12);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else {
                      let __option_idx = path.indexOf("/");
                      __option_idx =
                        __option_idx === -1 ? path.length : __option_idx;
                      const option = path.slice(0, __option_idx);
                      path = path.slice(__option_idx);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.user_document_runtime_options_check_status(
                              ctx,
                              userDocumentRuntimeOptions,
                              documentId,
                              option,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  } else if (path.startsWith("runtimeoptions/")) {
                    path = path.slice(15);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else {
                      let __option_idx = path.indexOf("/");
                      __option_idx =
                        __option_idx === -1 ? path.length : __option_idx;
                      const option = path.slice(0, __option_idx);
                      path = path.slice(__option_idx);
                      if (path.length === 0) {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      } else if (path.startsWith("/")) {
                        path = path.slice(1);
                        if (path.length === 0) {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        } else if (path.startsWith("enable")) {
                          path = path.slice(6);
                          if (path.length === 0) {
                            switch (request.method) {
                              case "POST":
                                return __routeHandlers_258.user_document_runtime_options_enable(
                                  ctx,
                                  userDocumentRuntimeOptions,
                                  documentId,
                                  option,
                                );
                              default:
                                return ctx.errorHandlers.onRequestNotFound(ctx);
                            }
                          } else {
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else if (path.startsWith("disable")) {
                          path = path.slice(7);
                          if (path.length === 0) {
                            switch (request.method) {
                              case "POST":
                                return __routeHandlers_258.user_document_runtime_options_disable(
                                  ctx,
                                  userDocumentRuntimeOptions,
                                  documentId,
                                  option,
                                );
                              default:
                                return ctx.errorHandlers.onRequestNotFound(ctx);
                            }
                          } else {
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          } else if (path.startsWith("s/")) {
            path = path.slice(2);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else if (path.startsWith("i")) {
              path = path.slice(1);
              if (path.length === 0) {
                return ctx.errorHandlers.onRequestNotFound(ctx);
              } else if (path.startsWith("dentities")) {
                path = path.slice(9);
                if (path.length === 0) {
                  switch (request.method) {
                    case "GET":
                      return __routeHandlers_258.user_identities_list(
                        ctx,
                        userIdentities,
                      );
                    default:
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("/")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else {
                    let __identity_id_idx = path.indexOf("/");
                    __identity_id_idx =
                      __identity_id_idx === -1
                        ? path.length
                        : __identity_id_idx;
                    const identityId = path.slice(0, __identity_id_idx);
                    path = path.slice(__identity_id_idx);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "GET":
                          return __routeHandlers_258.user_identities_get(
                            ctx,
                            userIdentities,
                            identityId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  }
                }
              } else if (path.startsWith("nvitations")) {
                path = path.slice(10);
                if (path.length === 0) {
                  switch (request.method) {
                    case "GET":
                      return __routeHandlers_258.user_invitations_list(
                        ctx,
                        userInvitations,
                      );
                    default:
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("/")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else {
                    let __invitation_id_idx = path.indexOf("/");
                    __invitation_id_idx =
                      __invitation_id_idx === -1
                        ? path.length
                        : __invitation_id_idx;
                    const invitationId = path.slice(0, __invitation_id_idx);
                    path = path.slice(__invitation_id_idx);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "GET":
                          return __routeHandlers_258.user_invitations_get(
                            ctx,
                            userInvitations,
                            invitationId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("/accept")) {
                      path = path.slice(7);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_258.user_invitations_accept(
                              ctx,
                              userInvitations,
                              invitationId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  }
                }
              }
            } else if (path.startsWith("proposals/")) {
              path = path.slice(10);
              if (path.length === 0) {
                return ctx.errorHandlers.onRequestNotFound(ctx);
              } else {
                let __proposal_id_idx = path.indexOf("/");
                __proposal_id_idx =
                  __proposal_id_idx === -1 ? path.length : __proposal_id_idx;
                const proposalId = path.slice(0, __proposal_id_idx);
                path = path.slice(__proposal_id_idx);
                if (path.length === 0) {
                  switch (request.method) {
                    case "GET":
                      return __routeHandlers_258.user_proposals_get(
                        ctx,
                        userProposals,
                        proposalId,
                      );
                    case "PUT":
                      return __routeHandlers_258.user_proposals_put(
                        ctx,
                        userProposals,
                        proposalId,
                      );
                    default:
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("/")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("status")) {
                    path = path.slice(6);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "GET":
                          return __routeHandlers_258.user_proposals_get_status(
                            ctx,
                            userProposals,
                            proposalId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("withdraw")) {
                    path = path.slice(8);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_258.user_proposals_withdraw(
                            ctx,
                            userProposals,
                            proposalId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("ballots/submit")) {
                    path = path.slice(14);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_258.user_proposals_submit_ballot(
                            ctx,
                            userProposals,
                            proposalId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  }
                }
              }
            }
          }
        } else if (path.startsWith("oidc/")) {
          path = path.slice(5);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else if (path.startsWith(".well-known/openid-configuration")) {
            path = path.slice(32);
            if (path.length === 0) {
              switch (request.method) {
                case "GET":
                  return __routeHandlers_258.oidc_get_configuration(ctx, oidc);
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("keys")) {
            path = path.slice(4);
            if (path.length === 0) {
              switch (request.method) {
                case "GET":
                  return __routeHandlers_258.oidc_get_jwks(ctx, oidc);
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("generateSigningKey")) {
            path = path.slice(18);
            if (path.length === 0) {
              switch (request.method) {
                case "POST":
                  return __routeHandlers_258.oidc_generate_signing_key(
                    ctx,
                    oidc,
                  );
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("setIssuerUrl")) {
            path = path.slice(12);
            if (path.length === 0) {
              switch (request.method) {
                case "POST":
                  return __routeHandlers_258.oidc_set_issuer_url(ctx, oidc);
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("issuerInfo")) {
            path = path.slice(10);
            if (path.length === 0) {
              switch (request.method) {
                case "GET":
                  return __routeHandlers_258.oidc_get_issuer_info(ctx, oidc);
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          }
        } else if (path.startsWith("runtimeoptions/checkstatus/")) {
          path = path.slice(27);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else {
            let __option_idx = path.indexOf("/");
            __option_idx = __option_idx === -1 ? path.length : __option_idx;
            const option = path.slice(0, __option_idx);
            path = path.slice(__option_idx);
            if (path.length === 0) {
              switch (request.method) {
                case "POST":
                  return __routeHandlers_258.runtime_options_check_status(
                    ctx,
                    runtimeOptions,
                    option,
                  );
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          }
        }
      }

      return ctx.errorHandlers.onRequestNotFound(ctx);
    },
  );

  const __errorHandlers_259 = {
    onRequestNotFound: __onRequestNotFound_254,
    onInvalidRequest: __onInvalidRequest_255,
    onInternalError: __onInternalError_256,
  };
  return {
    dispatch(request, response) {
      const ctx = { request, response, errorHandlers: __errorHandlers_259 };
      return dispatch(ctx, request, response).catch((e) =>
        __onInternalError_256(ctx, e),
      );
    },
  };
}
