// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Certificate Authority operations
    ///</summary>
    public interface ICertificateAuthority
    {
        Task<SigningKeyResponse> GenerateSigningKeyAsync(string contractId);
        Task<CaInfoResponse> GetInfoAsync(string contractId);
        Task<EncryptedResponse> GenerateEndorsedCertAsync(string contractId);

    }
}
