// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Clean Room Policy operations
    ///</summary>
    public interface ICleanRoomPolicy
    {
        Task<CleanRoomPolicyResponse> GetCleanRoomPolicyAsync(string contractId);
        Task<ProposalResponse> ProposeCleanRoomPolicyChangeAsync(string contractId, CleanRoomPolicyProposal proposal);
        Task<DelegatePolicyResponse> GetDelegatePolicyAsync(string contractId, string delegateType, string delegateId);
        Task<DelegatePoliciesListResponse> ListDelegatePoliciesAsync(string contractId);
        Task SetDelegatePolicyWithAttestationAsync(string delegateType, string delegateId, AttestedRequest request);

    }
}
