// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Contract Runtime Options operations
    ///</summary>
    public interface IContractRuntimeOptions
    {
        Task EnableExecutionAsync(string contractId);
        Task DisableExecutionAsync(string contractId);
        Task<ProposalResponse> ProposeEnableLoggingAsync(string contractId);
        Task<ProposalResponse> ProposeDisableLoggingAsync(string contractId);
        Task<ProposalResponse> ProposeEnableTelemetryAsync(string contractId);
        Task<ProposalResponse> ProposeDisableTelemetryAsync(string contractId);
        Task<RuntimeStatusResponse> CheckExecutionStatusAsync(string contractId);
        Task<RuntimeStatusResponse> CheckLoggingStatusAsync(string contractId);
        Task<RuntimeStatusResponse> CheckTelemetryStatusAsync(string contractId);
        Task<ConsentCheckResponse> CheckExecutionConsentAsync(string? contractId);
        Task<ConsentCheckResponse> CheckLoggingConsentAsync(string? contractId);
        Task<ConsentCheckResponse> CheckTelemetryConsentAsync(string? contractId);

    }
}
