// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Contract operations
    ///</summary>
    public interface IContracts
    {
        Task<ContractsListResponse> ListContractsAsync(string? state);
        Task<ContractResponse> GetContractAsync(string contractId);
        Task UpdateContractAsync(string contractId, PutContractRequest contract);
        Task<ProposalResponse> ProposeContractChangeAsync(string contractId, ContractProposal proposal);
        Task<VoteResponse> VoteAcceptContractAsync(string contractId, ProposalVote vote);
        Task<VoteResponse> VoteRejectContractAsync(string contractId, ProposalVote vote);
        Task<VoteResponse> VoteOnContractAsync(string contractId, CustomBallotVote vote);

    }
}
