// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;
using System.Text.Json.Nodes;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Contract Proposal operations
    ///</summary>
    public interface IContractProposals
    {
        Task<DeploymentProposalResponse> GetDeploymentProposalAsync(string contractId, string proposalType);
        Task<ProposalResponse> ProposeDeploymentAsync(string contractId, string proposalType, JsonNode proposal);

    }
}
