// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;
using System.Text.Json.Nodes;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Complete Governance Client interface Aggregates all governance operations
    /// for token-based authentication
    ///</summary>
    public interface IGovernanceClient
    {
        Task<ContractsListResponse> ListContractsAsync(string? state);
        Task<ContractResponse> GetContractAsync(string contractId);
        Task UpdateContractAsync(string contractId, PutContractRequest contract);
        Task<ProposalResponse> ProposeContractChangeAsync(string contractId, ContractProposal proposal);
        Task<VoteResponse> VoteAcceptContractAsync(string contractId, ProposalVote vote);
        Task<VoteResponse> VoteRejectContractAsync(string contractId, ProposalVote vote);
        Task<VoteResponse> VoteOnContractAsync(string contractId, CustomBallotVote vote);
        Task<SigningKeyResponse> GenerateSigningKeyAsync(string contractId);
        Task<CaInfoResponse> GetInfoAsync(string contractId);
        Task<EncryptedResponse> GenerateEndorsedCertAsync(string contractId);
        Task<CleanRoomPolicyResponse> GetCleanRoomPolicyAsync(string contractId);
        Task<ProposalResponse> ProposeCleanRoomPolicyChangeAsync(string contractId, CleanRoomPolicyProposal proposal);
        Task<DelegatePolicyResponse> GetDelegatePolicyAsync(string contractId, string delegateType, string delegateId);
        Task<DelegatePoliciesListResponse> ListDelegatePoliciesAsync(string contractId);
        Task SetDelegatePolicyWithAttestationAsync(string delegateType, string delegateId, AttestedRequest request);
        Task<DeploymentProposalResponse> GetDeploymentProposalAsync(string contractId, string proposalType);
        Task<ProposalResponse> ProposeDeploymentAsync(string contractId, string proposalType, JsonNode proposal);
        Task EnableExecutionAsync(string contractId);
        Task DisableExecutionAsync(string contractId);
        Task<ProposalResponse> ProposeEnableLoggingAsync(string contractId);
        Task<ProposalResponse> ProposeDisableLoggingAsync(string contractId);
        Task<ProposalResponse> ProposeEnableTelemetryAsync(string contractId);
        Task<ProposalResponse> ProposeDisableTelemetryAsync(string contractId);
        Task<RuntimeStatusResponse> CheckExecutionStatusAsync(string contractId);
        Task<RuntimeStatusResponse> CheckLoggingStatusAsync(string contractId);
        Task<RuntimeStatusResponse> CheckTelemetryStatusAsync(string contractId);
        Task<ConsentCheckResponse> CheckExecutionConsentAsync(string? contractId);
        Task<ConsentCheckResponse> CheckLoggingConsentAsync(string? contractId);
        Task<ConsentCheckResponse> CheckTelemetryConsentAsync(string? contractId);
        Task<EventsResponse> GetEventsAsync(string contractId, string? id, string? scope, long? fromSeqno, long? toSeqno, int? maxSeqnoPerPage);
        Task StoreEventAsync(string? id, string? scope, AttestedEventRequest eventName);
        Task<MemberDocumentsList> ListMemberDocumentsAsync();
        Task<GetMemberDocumentResponse> GetMemberDocumentAsync(string documentId);
        Task UpdateMemberDocumentAsync(string documentId, DocumentData document);
        Task<ProposalResponse> ProposeMemberDocumentChangeAsync(string documentId, DocumentProposal proposal);
        Task<VoteResponse> VoteAcceptMemberDocumentAsync(string documentId, ProposalVote vote);
        Task<VoteResponse> VoteRejectMemberDocumentAsync(string documentId, ProposalVote vote);
        Task<VoteResponse> VoteOnMemberDocumentAsync(string documentId, CustomBallotVote vote);
        Task<EncryptedResponse> GetMemberDocumentWithAttestationAsync(string documentId);
        Task<MembersResponse> ListMembersAsync();
        Task<StateDigestResponse> UpdateStateDigestAsync();
        Task<string> AcknowledgeStateDigestAsync();
        Task<NetworkInfoResponse> ShowNetworkAsync();
        Task CheckAppReadyAsync();
        Task CheckGovReadyAsync();
        Task<TokenSubjectPolicyResponse> GetTokenSubjectPolicyAsync(string contractId, string subjectName);
        Task<EncryptedResponse> GetTokenWithAttestationAsync(string sub, string tenantId, string aud, string? iss);
        Task<SigningKeyResponse> GenerateIssuerSigningKeyAsync();
        Task SetIssuerUrlAsync(IssuerUrlConfig config);
        Task<IssuerInfoResponse> GetIssuerInfoAsync();
        Task<ProposalsListResponse> ListProposalsAsync();
        Task<ProposalDetailsResponse> GetProposalAsync(string proposalId);
        Task<VotesListResponse> GetProposalVotesAsync(string proposalId);
        Task<ProposalHistoricalResponse> GetProposalHistoricalAsync(string proposalId, string? queryString);
        Task<ProposalActionsResponse> GetProposalActionsAsync(string proposalId);
        Task<WithdrawResponse> WithdrawProposalAsync(string proposalId);
        Task<ProposalResponse> CreateProposalAsync(CreateProposalRequest proposal);
        Task<VoteResponse> VoteAcceptProposalAsync(string proposalId);
        Task<VoteResponse> VoteRejectProposalAsync(string proposalId);
        Task<VoteResponse> VoteOnProposalAsync(string proposalId, CustomBallot vote);
        Task<ProposalResponse> ProposeRuntimeOptionAsync(string option, string action);
        Task<RuntimeOptionStatusResponse> CheckRuntimeOptionStatusAsync(string option);
        Task<SecretsListResponse> ListSecretsAsync(string contractId);
        Task<SecretStoreResponse> StoreSecretAsync(string contractId, string secretName, SecretData secret);
        Task<SecretPolicyResponse> GetSecretPolicyAsync(string contractId, string secretId);
        Task<EncryptedResponse> GetSecretWithAttestationAsync(string secretId);
        Task<SecretStoreResponse> StoreSecretWithAttestationAsync(string secretName, AttestedRequest request);
        Task SetSecretPolicyWithAttestationAsync(string secretId, AttestedRequest request);
        Task<CheckUpdateResponse> CheckUpdatesAsync();
        Task<UserDocumentsListResponse> ListUserDocumentsAsync(string? labelSelector);
        Task<UserDocumentResponse> GetUserDocumentAsync(string documentId);
        Task UpdateUserDocumentAsync(string documentId, PutUserDocumentRequest document);
        Task<ProposalResponse> ProposeUserDocumentChangeAsync(string documentId, UserDocumentProposal proposal);
        Task<VoteResponse> VoteAcceptUserDocumentAsync(string documentId, ProposalVote vote);
        Task<VoteResponse> VoteRejectUserDocumentAsync(string documentId, ProposalVote vote);
        Task<VoteResponse> VoteOnUserDocumentAsync(string documentId, CustomBallotVote vote);
        Task EnableUserDocumentRuntimeOptionAsync(string documentId, string runtimeOption);
        Task DisableUserDocumentRuntimeOptionAsync(string documentId, string runtimeOption);
        Task<RuntimeOptionStatusResponse> CheckUserDocumentRuntimeOptionStatusAsync(string documentId, string runtimeOption);
        Task<EncryptedResponse> GetUserDocumentWithAttestationAsync(string documentId);
        Task<ConsentCheckResponse> CheckUserDocumentExecutionConsentAsync(string documentId);
        Task<ConsentCheckResponse> CheckUserDocumentTelemetryConsentAsync(string documentId);
        Task<UserIdentitiesResponse> ListUserIdentitiesAsync();
        Task<UserIdentityResponse> GetUserIdentityAsync(string identityId);
        Task<ProposalResponse> AddUserIdentityAsync(AddUserIdentityRequest identity);
        Task<UserInvitationsResponse> ListUserInvitationsAsync();
        Task<UserInvitationResponse> GetUserInvitationAsync(string invitationId);
        Task AcceptInvitationAsync(string invitationId);
        Task<InvitationProposalResponse> ProposeInvitationAsync(InvitationProposalInput invitation);
        Task<ProposalResponse> CreateUserProposalAsync(UserProposalRequest proposal);
        Task<UserProposalResponse> GetUserProposalAsync(string proposalId);
        Task<ProposalStatusResponse> GetUserProposalStatusAsync(string proposalId);
        Task<WithdrawResponse> WithdrawUserProposalAsync(string proposalId);
        Task<VoteResponse> VoteAcceptUserProposalAsync(string proposalId);
        Task<VoteResponse> VoteRejectUserProposalAsync(string proposalId);
        Task<UsersListResponse> ListUsersAsync();
        Task<UserResponse> GetUserAsync(string userId);
        Task<UserActiveResponse> IsUserActiveAsync(string authToken);
        Task<ReadyResponse> CheckReadyAsync();
        Task<string> ConfigureAsync(WorkspaceConfigurationModel config);
        Task<AccessTokenResponse> GetAccessTokenAsync();
        Task<WorkspaceConfiguration> ShowConfigurationAsync(bool? signingKey);
        Task<string> GetConstitutionAsync();
        Task<string> GetServiceInfoAsync();
        Task<string> GetJsAppEndpointsAsync();
        Task<JsonNode> GetJsAppModulesAsync();
        Task<JsonNode> ListJsAppModulesAsync();
        Task<string> GetJsAppModuleAsync(string moduleName);
        Task<JsonNode> GetJsAppBundleAsync();

    }
}
