// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Member operations
    ///</summary>
    public interface IMembers
    {
        Task<MembersResponse> ListMembersAsync();
        Task<StateDigestResponse> UpdateStateDigestAsync();
        Task<string> AcknowledgeStateDigestAsync();

    }
}
