// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Member Document operations
    ///</summary>
    public interface IMemberDocuments
    {
        Task<MemberDocumentsList> ListMemberDocumentsAsync();
        Task<GetMemberDocumentResponse> GetMemberDocumentAsync(string documentId);
        Task UpdateMemberDocumentAsync(string documentId, DocumentData document);
        Task<ProposalResponse> ProposeMemberDocumentChangeAsync(string documentId, DocumentProposal proposal);
        Task<VoteResponse> VoteAcceptMemberDocumentAsync(string documentId, ProposalVote vote);
        Task<VoteResponse> VoteRejectMemberDocumentAsync(string documentId, ProposalVote vote);
        Task<VoteResponse> VoteOnMemberDocumentAsync(string documentId, CustomBallotVote vote);
        Task<EncryptedResponse> GetMemberDocumentWithAttestationAsync(string documentId);

    }
}
