// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// OAuth operations
    ///</summary>
    public interface IOAuth
    {
        Task<TokenSubjectPolicyResponse> GetTokenSubjectPolicyAsync(string contractId, string subjectName);
        Task<EncryptedResponse> GetTokenWithAttestationAsync(string sub, string tenantId, string aud, string? iss);

    }
}
