// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Proposal operations
    ///</summary>
    public interface IProposals
    {
        Task<ProposalsListResponse> ListProposalsAsync();
        Task<ProposalDetailsResponse> GetProposalAsync(string proposalId);
        Task<VotesListResponse> GetProposalVotesAsync(string proposalId);
        Task<ProposalHistoricalResponse> GetProposalHistoricalAsync(string proposalId, string? queryString);
        Task<ProposalActionsResponse> GetProposalActionsAsync(string proposalId);
        Task<WithdrawResponse> WithdrawProposalAsync(string proposalId);
        Task<ProposalResponse> CreateProposalAsync(CreateProposalRequest proposal);
        Task<VoteResponse> VoteAcceptProposalAsync(string proposalId);
        Task<VoteResponse> VoteRejectProposalAsync(string proposalId);
        Task<VoteResponse> VoteOnProposalAsync(string proposalId, CustomBallot vote);

    }
}
