// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Runtime Options operations
    ///</summary>
    public interface IRuntimeOptions
    {
        Task<ProposalResponse> ProposeRuntimeOptionAsync(string option, string action);
        Task<RuntimeOptionStatusResponse> CheckRuntimeOptionStatusAsync(string option);

    }
}
