// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Secret operations
    ///</summary>
    public interface ISecrets
    {
        Task<SecretsListResponse> ListSecretsAsync(string contractId);
        Task<SecretStoreResponse> StoreSecretAsync(string contractId, string secretName, SecretData secret);
        Task<SecretPolicyResponse> GetSecretPolicyAsync(string contractId, string secretId);
        Task<EncryptedResponse> GetSecretWithAttestationAsync(string secretId);
        Task<SecretStoreResponse> StoreSecretWithAttestationAsync(string secretName, AttestedRequest request);
        Task SetSecretPolicyWithAttestationAsync(string secretId, AttestedRequest request);

    }
}
