// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// User Invitation operations
    ///</summary>
    public interface IUserInvitations
    {
        Task<UserInvitationsResponse> ListUserInvitationsAsync();
        Task<UserInvitationResponse> GetUserInvitationAsync(string invitationId);
        Task AcceptInvitationAsync(string invitationId);
        Task<InvitationProposalResponse> ProposeInvitationAsync(InvitationProposalInput invitation);

    }
}
