// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// User Identity operations
    ///</summary>
    public interface IUserIdentities
    {
        Task<UserIdentitiesResponse> ListUserIdentitiesAsync();
        Task<UserIdentityResponse> GetUserIdentityAsync(string identityId);
        Task<ProposalResponse> AddUserIdentityAsync(AddUserIdentityRequest identity);

    }
}
