// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// User Document operations
    ///</summary>
    public interface IUserDocuments
    {
        Task<UserDocumentsListResponse> ListUserDocumentsAsync(string? labelSelector);
        Task<UserDocumentResponse> GetUserDocumentAsync(string documentId);
        Task UpdateUserDocumentAsync(string documentId, PutUserDocumentRequest document);
        Task<ProposalResponse> ProposeUserDocumentChangeAsync(string documentId, UserDocumentProposal proposal);
        Task<VoteResponse> VoteAcceptUserDocumentAsync(string documentId, ProposalVote vote);
        Task<VoteResponse> VoteRejectUserDocumentAsync(string documentId, ProposalVote vote);
        Task<VoteResponse> VoteOnUserDocumentAsync(string documentId, CustomBallotVote vote);
        Task EnableUserDocumentRuntimeOptionAsync(string documentId, string runtimeOption);
        Task DisableUserDocumentRuntimeOptionAsync(string documentId, string runtimeOption);
        Task<RuntimeOptionStatusResponse> CheckUserDocumentRuntimeOptionStatusAsync(string documentId, string runtimeOption);
        Task<EncryptedResponse> GetUserDocumentWithAttestationAsync(string documentId);
        Task<ConsentCheckResponse> CheckUserDocumentExecutionConsentAsync(string documentId);
        Task<ConsentCheckResponse> CheckUserDocumentTelemetryConsentAsync(string documentId);

    }
}
