// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// User operations
    ///</summary>
    public interface IUsers
    {
        Task<UsersListResponse> ListUsersAsync();
        Task<UserResponse> GetUserAsync(string userId);
        Task<UserActiveResponse> IsUserActiveAsync(string authToken);

    }
}
