// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// User Proposal operations
    ///</summary>
    public interface IUserProposals
    {
        Task<ProposalResponse> CreateUserProposalAsync(UserProposalRequest proposal);
        Task<UserProposalResponse> GetUserProposalAsync(string proposalId);
        Task<ProposalStatusResponse> GetUserProposalStatusAsync(string proposalId);
        Task<WithdrawResponse> WithdrawUserProposalAsync(string proposalId);
        Task<VoteResponse> VoteAcceptUserProposalAsync(string proposalId);
        Task<VoteResponse> VoteRejectUserProposalAsync(string proposalId);

    }
}
