// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;
using System.Text.Json.Nodes;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Workspace operations
    ///</summary>
    public interface IWorkspace
    {
        Task<ReadyResponse> CheckReadyAsync();
        Task<string> ConfigureAsync(WorkspaceConfigurationModel config);
        Task<AccessTokenResponse> GetAccessTokenAsync();
        Task<WorkspaceConfiguration> ShowConfigurationAsync(bool? signingKey);
        Task<string> GetConstitutionAsync();
        Task<string> GetServiceInfoAsync();
        Task<string> GetJsAppEndpointsAsync();
        Task<JsonNode> GetJsAppModulesAsync();
        Task<JsonNode> ListJsAppModulesAsync();
        Task<string> GetJsAppModuleAsync(string moduleName);
        Task<JsonNode> GetJsAppBundleAsync();

    }
}
