# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import (
        AccessPolicyEntry,
        Action,
        Attributes,
        CheckMhsmNameAvailabilityParameters,
        CheckMhsmNameAvailabilityResult,
        CheckNameAvailabilityResult,
        CloudErrorBody,
        DeletedManagedHsm,
        DeletedManagedHsmListResult,
        DeletedManagedHsmProperties,
        DeletedVault,
        DeletedVaultListResult,
        DeletedVaultProperties,
        DimensionProperties,
        Error,
        IPRule,
        Key,
        KeyAttributes,
        KeyCreateParameters,
        KeyListResult,
        KeyProperties,
        KeyReleasePolicy,
        KeyRotationPolicyAttributes,
        LifetimeAction,
        LogSpecification,
        ManagedHsm,
        ManagedHsmAction,
        ManagedHsmError,
        ManagedHsmKey,
        ManagedHsmKeyAttributes,
        ManagedHsmKeyCreateParameters,
        ManagedHsmKeyListResult,
        ManagedHsmKeyProperties,
        ManagedHsmKeyReleasePolicy,
        ManagedHsmKeyRotationPolicyAttributes,
        ManagedHsmLifetimeAction,
        ManagedHsmListResult,
        ManagedHsmProperties,
        ManagedHsmResource,
        ManagedHsmRotationPolicy,
        ManagedHSMSecurityDomainProperties,
        ManagedHsmSku,
        ManagedHsmTrigger,
        ManagedServiceIdentity,
        MetricSpecification,
        MHSMGeoReplicatedRegion,
        MHSMIPRule,
        MHSMNetworkRuleSet,
        MHSMPrivateEndpoint,
        MHSMPrivateEndpointConnection,
        MHSMPrivateEndpointConnectionItem,
        MHSMPrivateEndpointConnectionsListResult,
        MHSMPrivateLinkResource,
        MHSMPrivateLinkResourceListResult,
        MHSMPrivateLinkServiceConnectionState,
        MHSMRegionsListResult,
        MHSMVirtualNetworkRule,
        NetworkRuleSet,
        Operation,
        OperationDisplay,
        OperationListResult,
        Permissions,
        PrivateEndpoint,
        PrivateEndpointConnection,
        PrivateEndpointConnectionItem,
        PrivateEndpointConnectionListResult,
        PrivateLinkResource,
        PrivateLinkResourceListResult,
        PrivateLinkServiceConnectionState,
        ProxyResourceWithoutSystemData,
        Resource,
        ResourceListResult,
        RotationPolicy,
        Secret,
        SecretAttributes,
        SecretCreateOrUpdateParameters,
        SecretListResult,
        SecretPatchParameters,
        SecretPatchProperties,
        SecretProperties,
        ServiceSpecification,
        Sku,
        SystemData,
        Trigger,
        UserAssignedIdentity,
        Vault,
        VaultAccessPolicyParameters,
        VaultAccessPolicyProperties,
        VaultCheckNameAvailabilityParameters,
        VaultCreateOrUpdateParameters,
        VaultListResult,
        VaultPatchParameters,
        VaultPatchProperties,
        VaultProperties,
        VirtualNetworkRule,
    )
except (SyntaxError, ImportError):
    from ._models import AccessPolicyEntry  # type: ignore
    from ._models import Action  # type: ignore
    from ._models import Attributes  # type: ignore
    from ._models import CheckMhsmNameAvailabilityParameters  # type: ignore
    from ._models import CheckMhsmNameAvailabilityResult  # type: ignore
    from ._models import CheckNameAvailabilityResult  # type: ignore
    from ._models import CloudErrorBody  # type: ignore
    from ._models import DeletedManagedHsm  # type: ignore
    from ._models import DeletedManagedHsmListResult  # type: ignore
    from ._models import DeletedManagedHsmProperties  # type: ignore
    from ._models import DeletedVault  # type: ignore
    from ._models import DeletedVaultListResult  # type: ignore
    from ._models import DeletedVaultProperties  # type: ignore
    from ._models import DimensionProperties  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import IPRule  # type: ignore
    from ._models import Key  # type: ignore
    from ._models import KeyAttributes  # type: ignore
    from ._models import KeyCreateParameters  # type: ignore
    from ._models import KeyListResult  # type: ignore
    from ._models import KeyProperties  # type: ignore
    from ._models import KeyReleasePolicy  # type: ignore
    from ._models import KeyRotationPolicyAttributes  # type: ignore
    from ._models import LifetimeAction  # type: ignore
    from ._models import LogSpecification  # type: ignore
    from ._models import MHSMGeoReplicatedRegion  # type: ignore
    from ._models import MHSMIPRule  # type: ignore
    from ._models import MHSMNetworkRuleSet  # type: ignore
    from ._models import MHSMPrivateEndpoint  # type: ignore
    from ._models import MHSMPrivateEndpointConnection  # type: ignore
    from ._models import MHSMPrivateEndpointConnectionItem  # type: ignore
    from ._models import MHSMPrivateEndpointConnectionsListResult  # type: ignore
    from ._models import MHSMPrivateLinkResource  # type: ignore
    from ._models import MHSMPrivateLinkResourceListResult  # type: ignore
    from ._models import MHSMPrivateLinkServiceConnectionState  # type: ignore
    from ._models import MHSMRegionsListResult  # type: ignore
    from ._models import MHSMVirtualNetworkRule  # type: ignore
    from ._models import ManagedHSMSecurityDomainProperties  # type: ignore
    from ._models import ManagedHsm  # type: ignore
    from ._models import ManagedHsmAction  # type: ignore
    from ._models import ManagedHsmError  # type: ignore
    from ._models import ManagedHsmKey  # type: ignore
    from ._models import ManagedHsmKeyAttributes  # type: ignore
    from ._models import ManagedHsmKeyCreateParameters  # type: ignore
    from ._models import ManagedHsmKeyListResult  # type: ignore
    from ._models import ManagedHsmKeyProperties  # type: ignore
    from ._models import ManagedHsmKeyReleasePolicy  # type: ignore
    from ._models import ManagedHsmKeyRotationPolicyAttributes  # type: ignore
    from ._models import ManagedHsmLifetimeAction  # type: ignore
    from ._models import ManagedHsmListResult  # type: ignore
    from ._models import ManagedHsmProperties  # type: ignore
    from ._models import ManagedHsmResource  # type: ignore
    from ._models import ManagedHsmRotationPolicy  # type: ignore
    from ._models import ManagedHsmSku  # type: ignore
    from ._models import ManagedHsmTrigger  # type: ignore
    from ._models import ManagedServiceIdentity  # type: ignore
    from ._models import MetricSpecification  # type: ignore
    from ._models import NetworkRuleSet  # type: ignore
    from ._models import Operation  # type: ignore
    from ._models import OperationDisplay  # type: ignore
    from ._models import OperationListResult  # type: ignore
    from ._models import Permissions  # type: ignore
    from ._models import PrivateEndpoint  # type: ignore
    from ._models import PrivateEndpointConnection  # type: ignore
    from ._models import PrivateEndpointConnectionItem  # type: ignore
    from ._models import PrivateEndpointConnectionListResult  # type: ignore
    from ._models import PrivateLinkResource  # type: ignore
    from ._models import PrivateLinkResourceListResult  # type: ignore
    from ._models import PrivateLinkServiceConnectionState  # type: ignore
    from ._models import ProxyResourceWithoutSystemData  # type: ignore
    from ._models import Resource  # type: ignore
    from ._models import ResourceListResult  # type: ignore
    from ._models import RotationPolicy  # type: ignore
    from ._models import Secret  # type: ignore
    from ._models import SecretAttributes  # type: ignore
    from ._models import SecretCreateOrUpdateParameters  # type: ignore
    from ._models import SecretListResult  # type: ignore
    from ._models import SecretPatchParameters  # type: ignore
    from ._models import SecretPatchProperties  # type: ignore
    from ._models import SecretProperties  # type: ignore
    from ._models import ServiceSpecification  # type: ignore
    from ._models import Sku  # type: ignore
    from ._models import SystemData  # type: ignore
    from ._models import Trigger  # type: ignore
    from ._models import UserAssignedIdentity  # type: ignore
    from ._models import Vault  # type: ignore
    from ._models import VaultAccessPolicyParameters  # type: ignore
    from ._models import VaultAccessPolicyProperties  # type: ignore
    from ._models import VaultCheckNameAvailabilityParameters  # type: ignore
    from ._models import VaultCreateOrUpdateParameters  # type: ignore
    from ._models import VaultListResult  # type: ignore
    from ._models import VaultPatchParameters  # type: ignore
    from ._models import VaultPatchProperties  # type: ignore
    from ._models import VaultProperties  # type: ignore
    from ._models import VirtualNetworkRule  # type: ignore

from ._key_vault_management_client_enums import (
    AccessPolicyUpdateKind,
    ActionsRequired,
    ActivationStatus,
    CertificatePermissions,
    CreateMode,
    DeletionRecoveryLevel,
    GeoReplicationRegionProvisioningState,
    IdentityType,
    JsonWebKeyCurveName,
    JsonWebKeyOperation,
    JsonWebKeyType,
    KeyPermissions,
    KeyRotationPolicyActionType,
    ManagedHsmSkuFamily,
    ManagedHsmSkuName,
    ManagedServiceIdentityType,
    NetworkRuleAction,
    NetworkRuleBypassOptions,
    PrivateEndpointConnectionProvisioningState,
    PrivateEndpointServiceConnectionStatus,
    ProvisioningState,
    PublicNetworkAccess,
    Reason,
    SecretPermissions,
    SkuFamily,
    SkuName,
    StoragePermissions,
    VaultProvisioningState,
)

__all__ = [
    'AccessPolicyEntry',
    'Action',
    'Attributes',
    'CheckMhsmNameAvailabilityParameters',
    'CheckMhsmNameAvailabilityResult',
    'CheckNameAvailabilityResult',
    'CloudErrorBody',
    'DeletedManagedHsm',
    'DeletedManagedHsmListResult',
    'DeletedManagedHsmProperties',
    'DeletedVault',
    'DeletedVaultListResult',
    'DeletedVaultProperties',
    'DimensionProperties',
    'Error',
    'IPRule',
    'Key',
    'KeyAttributes',
    'KeyCreateParameters',
    'KeyListResult',
    'KeyProperties',
    'KeyReleasePolicy',
    'KeyRotationPolicyAttributes',
    'LifetimeAction',
    'LogSpecification',
    'MHSMGeoReplicatedRegion',
    'MHSMIPRule',
    'MHSMNetworkRuleSet',
    'MHSMPrivateEndpoint',
    'MHSMPrivateEndpointConnection',
    'MHSMPrivateEndpointConnectionItem',
    'MHSMPrivateEndpointConnectionsListResult',
    'MHSMPrivateLinkResource',
    'MHSMPrivateLinkResourceListResult',
    'MHSMPrivateLinkServiceConnectionState',
    'MHSMRegionsListResult',
    'MHSMVirtualNetworkRule',
    'ManagedHSMSecurityDomainProperties',
    'ManagedHsm',
    'ManagedHsmAction',
    'ManagedHsmError',
    'ManagedHsmKey',
    'ManagedHsmKeyAttributes',
    'ManagedHsmKeyCreateParameters',
    'ManagedHsmKeyListResult',
    'ManagedHsmKeyProperties',
    'ManagedHsmKeyReleasePolicy',
    'ManagedHsmKeyRotationPolicyAttributes',
    'ManagedHsmLifetimeAction',
    'ManagedHsmListResult',
    'ManagedHsmProperties',
    'ManagedHsmResource',
    'ManagedHsmRotationPolicy',
    'ManagedHsmSku',
    'ManagedHsmTrigger',
    'ManagedServiceIdentity',
    'MetricSpecification',
    'NetworkRuleSet',
    'Operation',
    'OperationDisplay',
    'OperationListResult',
    'Permissions',
    'PrivateEndpoint',
    'PrivateEndpointConnection',
    'PrivateEndpointConnectionItem',
    'PrivateEndpointConnectionListResult',
    'PrivateLinkResource',
    'PrivateLinkResourceListResult',
    'PrivateLinkServiceConnectionState',
    'ProxyResourceWithoutSystemData',
    'Resource',
    'ResourceListResult',
    'RotationPolicy',
    'Secret',
    'SecretAttributes',
    'SecretCreateOrUpdateParameters',
    'SecretListResult',
    'SecretPatchParameters',
    'SecretPatchProperties',
    'SecretProperties',
    'ServiceSpecification',
    'Sku',
    'SystemData',
    'Trigger',
    'UserAssignedIdentity',
    'Vault',
    'VaultAccessPolicyParameters',
    'VaultAccessPolicyProperties',
    'VaultCheckNameAvailabilityParameters',
    'VaultCreateOrUpdateParameters',
    'VaultListResult',
    'VaultPatchParameters',
    'VaultPatchProperties',
    'VaultProperties',
    'VirtualNetworkRule',
    'AccessPolicyUpdateKind',
    'ActionsRequired',
    'ActivationStatus',
    'CertificatePermissions',
    'CreateMode',
    'DeletionRecoveryLevel',
    'GeoReplicationRegionProvisioningState',
    'IdentityType',
    'JsonWebKeyCurveName',
    'JsonWebKeyOperation',
    'JsonWebKeyType',
    'KeyPermissions',
    'KeyRotationPolicyActionType',
    'ManagedHsmSkuFamily',
    'ManagedHsmSkuName',
    'ManagedServiceIdentityType',
    'NetworkRuleAction',
    'NetworkRuleBypassOptions',
    'PrivateEndpointConnectionProvisioningState',
    'PrivateEndpointServiceConnectionStatus',
    'ProvisioningState',
    'PublicNetworkAccess',
    'Reason',
    'SecretPermissions',
    'SkuFamily',
    'SkuName',
    'StoragePermissions',
    'VaultProvisioningState',
]
