# https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/tls#step-2-test-proxying-https-http
# https://www.funnel-labs.io/2022/10/19/envoyproxy-5-securing-connections-with-https/
# https://github.com/envoyproxy/envoy/issues/5514#issuecomment-2162805034 (for redirecting http to https)
static_resources:
  listeners:
  - address:
      socket_address:
        address: $CCR_ENVOY_LISTENER_HTTPS_ENDPOINT
        port_value: $CCR_ENVOY_LISTENER_HTTPS_PORT
    listener_filters:
      name: envoy.filters.listener.tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    - filter_chain_match:
        transport_protocol: raw_buffer
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_redirect
            virtual_hosts:
            - name: local_route
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                redirect: { https_redirect: true }
    - filter_chain_match:
        transport_protocol: tls
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config: 
          '@type': "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service1
                  timeout: 360s # Default is 15s
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: certs/server-cert.pem
              private_key:
                filename: keys/server-key.pem
  clusters:
  - name: service1
    type: $CCR_ENVOY_CLUSTER_TYPE
    connect_timeout: 0.25s
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: $CCR_ENVOY_DESTINATION_ENDPOINT
                port_value: $CCR_ENVOY_DESTINATION_PORT
