allow-other: true

logging:
  type: base
  level: log_info

components:
  - libfuse
  - block_cache
  - encryptor

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

block_cache:
  block-size-mb: 
  mem-size-mb: 256
  disk-size-mb: 2048
  # Setting prefetch explicitly to 0. Otherwise, blobfuse tries to determine prefetch using 
  # the container CPUs and memory size instead of honoring the mem-size-mb limits and fails to start.
  prefetch: 0
  path: /tmp/blobfuse_temp
  parallelism: 128

encryptor:
  block-size-mb: 
  encrypted-mount-path: 