// Generated by Microsoft TypeSpec

import {
  CheckExecutionStatusResult,
  CheckLoggingStatusResult,
  CheckTelemetryStatusResult,
  ConsentCheckExecutionResult,
  ConsentCheckLoggingResult,
  ConsentCheckTelemetryResult,
  GetOptions,
  GetResult,
  ListDelegatesResult,
  GetDelegateResult,
  GetSpecResult,
  GetInfoResult,
  GetTokenResult,
  GenerateEndorsedCertResult,
  ListResult,
  IsActiveResult,
  ListOptions,
  ConsentCheckResult,
  CheckStatusResult,
  GetHistoricalResult,
  GetStatusResult,
  GetConfigurationResult,
  GetJwksResult,
  SetIssuerUrlRequestBody,
  GetIssuerInfoResult,
} from "../../synthetic.js";

/**
 * List contracts response
 */
export interface ListContractsResponse {
  /**
   * Array of contracts
   */
  value: ListContractResponse[];
}

/**
 * List contract response
 */
export interface ListContractResponse {
  /**
   * Contract ID
   */
  id: string;
}

/**
 * Put contract request
 */
export interface PutContractRequest {
  /**
   * Contract version
   */
  version: string;

  /**
   * Contract data
   */
  data: unknown;
}

/**
 * Get contract response
 */
export interface GetContractResponse {
  /**
   * Contract ID
   */
  id: string;

  /**
   * Contract version
   */
  version: string;

  /**
   * Contract data
   */
  data: unknown;

  /**
   * Contract state
   */
  state: string;

  /**
   * Proposal ID
   */
  proposalId: string;

  /**
   * Final votes
   */
  finalVotes?: MemberVote[];
}

/**
 * Member vote
 */
export interface MemberVote {
  /**
   * Member ID
   */
  memberId: string;

  /**
   * Vote value
   */
  vote: boolean;
}

/**
 * Get events response
 */
export interface GetEventsResponse {
  /**
   * Next link for pagination
   */
  nextLink?: string;

  /**
   * Array of events
   */
  value: Event[];
}

/**
 * Event
 */
export interface Event {
  /**
   * Event timestamp
   */
  timestamp: string;

  /**
   * Event timestamp ISO format
   */
  timestampIso: string;

  /**
   * Event scope
   */
  scope: string;

  /**
   * Event ID
   */
  id: string;

  /**
   * Sequence number
   */
  seqno: number;

  /**
   * Event data
   */
  data: unknown;
}

/**
 * Put event request
 */
export interface PutEventRequest {
  /**
   * Event timestamp
   */
  timestamp: string;

  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Signature
   */
  sign: Sign;

  /**
   * Event data
   */
  data: unknown;
}

/**
 * SNP attestation evidence
 */
export interface SnpEvidence {
  /**
   * Base64 encoded evidence
   */
  evidence: string;

  /**
   * Base64 encoded endorsements
   */
  endorsements: string;

  /**
   * Base64 encoded UVM endorsements
   */
  uvmEndorsements: string;

  /**
   * Endorsed TCB version
   */
  endorsedTcb?: string;
}

/**
 * Digital signature information
 */
export interface Sign {
  /**
   * Signature value
   */
  signature: string;

  /**
   * PEM encoded public key
   */
  publicKey: string;
}

/**
 * List secrets response
 */
export interface ListSecretsResponse {
  /**
   * Array of secrets
   */
  value: ListSecretResponse[];
}

/**
 * List secret response
 */
export interface ListSecretResponse {
  /**
   * Secret ID
   */
  secretId: string;
}

/**
 * Put secret by member/user request
 */
export interface PutSecretByMemberUserRequest {
  /**
   * Secret value
   */
  value: string;
}

/**
 * Put secret by clean room request
 */
export interface PutSecretByCleanRoomRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Encryption info
   */
  encrypt: Encrypt;

  /**
   * Signature
   */
  sign: Sign;

  /**
   * Encrypted data
   */
  data: string;
}

/**
 * Put secret response
 */
export interface PutSecretResponse {
  /**
   * Secret ID
   */
  secretId: string;
}

/**
 * Encryption information
 */
export interface Encrypt {
  /**
   * PEM encoded public key
   */
  publicKey: string;
}

/**
 * Get secret request
 */
export interface GetSecretRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Encryption info
   */
  encrypt: Encrypt;
}

/**
 * Get secret response
 */
export interface GetSecretResponse {
  /**
   * Secret value
   */
  value: string;
}

/**
 * Generate endorsed cert request
 */
export interface GenerateEndorsedCertRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Encryption info
   */
  encrypt: Encrypt;

  /**
   * Signature
   */
  sign: Sign;

  /**
   * Encrypted request data
   */
  data: string;
}

/**
 * CA info
 */
export interface CaInfo {
  /**
   * CA enabled
   */
  enabled: boolean;

  /**
   * CA certificate
   */
  caCert?: string;

  /**
   * Public key
   */
  publicKey?: string;

  /**
   * Proposal IDs
   */
  proposalIds: string[];
}

/**
 * List member document response
 */
export interface ListMemberDocumentResponse {
  /**
   * Document ID
   */
  id: string;
}

/**
 * Put member document request
 */
export interface PutMemberDocumentRequest {
  /**
   * Document version
   */
  version: string;

  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Document data
   */
  data: unknown;
}

/**
 * Get member document response
 */
export interface GetMemberDocumentResponse {
  /**
   * Document ID
   */
  id: string;

  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Document version
   */
  version: string;

  /**
   * Document data
   */
  data: unknown;

  /**
   * Document state
   */
  state: string;

  /**
   * Proposal ID
   */
  proposalId: string;

  /**
   * Final votes
   */
  finalVotes?: MemberVote[];
}

/**
 * Get accepted member document request
 */
export interface GetAcceptedMemberDocumentRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Encryption info
   */
  encrypt: Encrypt;
}

/**
 * Get accepted member document response
 */
export interface GetAcceptedMemberDocumentResponse {
  /**
   * Encrypted GetDocumentResponse content
   */
  value: string;
}

/**
 * List user documents response
 */
export interface ListUserDocumentsResponse {
  /**
   * Array of user documents
   */
  value: ListUserDocumentResponse[];
}

/**
 * List user document response
 */
export interface ListUserDocumentResponse {
  /**
   * Document ID
   */
  id: string;

  /**
   * Labels
   */
  labels: Record<string, string>;
}

/**
 * Put user document request
 */
export interface PutUserDocumentRequest {
  /**
   * Document version
   */
  version: string;

  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Approvers
   */
  approvers?: UserProposalApprover[];

  /**
   * Document data
   */
  data: unknown;

  /**
   * Labels
   */
  labels: Record<string, string>;
}

/**
 * User proposal approver
 */
export interface UserProposalApprover {
  /**
   * Approver ID
   */
  approverId: string;

  /**
   * Approver ID type
   */
  approverIdType: string;
}

/**
 * Get user document response
 */
export interface GetUserDocumentResponse {
  /**
   * Document ID
   */
  id: string;

  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Document version
   */
  version: string;

  /**
   * Approvers
   */
  approvers?: UserProposalApprover[];

  /**
   * Document data
   */
  data: unknown;

  /**
   * Labels
   */
  labels: Record<string, string>;

  /**
   * Document state
   */
  state: string;

  /**
   * Proposal ID
   */
  proposalId: string;

  /**
   * Proposer ID
   */
  proposerId: string;

  /**
   * Final votes
   */
  finalVotes?: UserVote[];
}

/**
 * User vote
 */
export interface UserVote {
  /**
   * Approver ID
   */
  approverId: string;

  /**
   * Ballot value
   */
  ballot: string;
}

/**
 * Get accepted user document request
 */
export interface GetAcceptedUserDocumentRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Encryption info
   */
  encrypt: Encrypt;
}

/**
 * Get accepted user document response
 */
export interface GetAcceptedUserDocumentResponse {
  /**
   * Encrypted GetUserDocumentResponse content
   */
  value: string;
}

/**
 * Get user proposal response
 */
export interface GetUserProposalResponse {
  /**
   * Proposal ID
   */
  proposalId: string;

  /**
   * Proposal name
   */
  name: string;

  /**
   * Approvers
   */
  approvers: UserProposalApprover[];

  /**
   * Proposal arguments
   */
  args: unknown;
}

/**
 * Create user proposal request
 */
export interface CreateUserProposalRequest {
  /**
   * Proposal name
   */
  name: string;

  /**
   * Approvers
   */
  approvers?: UserProposalApprover[];

  /**
   * Proposal arguments
   */
  args: unknown;
}

/**
 * Create user proposal response
 */
export interface CreateUserProposalResponse {
  /**
   * Proposal ID
   */
  proposalId: string;
}

/**
 * User proposal
 */
export interface UserProposal {
  /**
   * Sequence number
   */
  seqno: number;

  /**
   * Proposal state
   */
  proposalState: string;

  /**
   * Proposal ID
   */
  proposalId: string;
}

/**
 * Submit user proposal ballot request
 */
export interface SubmitUserProposalBallotRequest {
  /**
   * Ballot value
   */
  ballot: string;
}

export interface Contracts<Context = unknown> {
  /**
   * List all contracts
   */
  list(ctx: Context): Promise<ListContractsResponse>;

  /**
   * Create or update a contract
   */
  put(
    ctx: Context,
    contractId: string,
    contract: PutContractRequest,
  ): Promise<void>;

  /**
   * Get a contract by ID
   */
  get(ctx: Context, contractId: string): Promise<GetContractResponse>;
}

export interface ContractRuntimeOptions<Context = unknown> {
  /**
   * Check contract execution status
   */
  checkExecutionStatus(
    ctx: Context,
    contractId: string,
  ): Promise<CheckExecutionStatusResult>;

  /**
   * Check contract logging status
   */
  checkLoggingStatus(
    ctx: Context,
    contractId: string,
  ): Promise<CheckLoggingStatusResult>;

  /**
   * Check contract telemetry status
   */
  checkTelemetryStatus(
    ctx: Context,
    contractId: string,
  ): Promise<CheckTelemetryStatusResult>;

  /**
   * Consent check for execution
   */
  consentCheckExecution(
    ctx: Context,
    contractId: string,
  ): Promise<ConsentCheckExecutionResult>;

  /**
   * Consent check for logging
   */
  consentCheckLogging(
    ctx: Context,
    contractId: string,
  ): Promise<ConsentCheckLoggingResult>;

  /**
   * Consent check for telemetry
   */
  consentCheckTelemetry(
    ctx: Context,
    contractId: string,
  ): Promise<ConsentCheckTelemetryResult>;

  /**
   * Enable a contract
   */
  enable(ctx: Context, contractId: string): Promise<void>;

  /**
   * Disable a contract
   */
  disable(ctx: Context, contractId: string): Promise<void>;
}

export interface Events<Context = unknown> {
  /**
   * Get events for a contract
   */
  get(
    ctx: Context,
    contractId: string,
    options?: GetOptions,
  ): Promise<GetEventsResponse>;

  /**
   * Put an event
   */
  put(ctx: Context, contractId: string, event: PutEventRequest): Promise<void>;
}

export interface Secrets<Context = unknown> {
  /**
   * List all secrets for a contract
   */
  list(ctx: Context, contractId: string): Promise<ListSecretsResponse>;

  /**
   * Create or update a secret
   */
  put(
    ctx: Context,
    contractId: string,
    secretName: string,
    request: PutSecretByMemberUserRequest | PutSecretByCleanRoomRequest,
  ): Promise<PutSecretResponse>;

  /**
   * Get a secret
   */
  get(
    ctx: Context,
    contractId: string,
    secretName: string,
    request: GetSecretRequest,
  ): Promise<GetSecretResponse>;
}

export interface CleanRoomPolicy<Context = unknown> {
  /**
   * Get clean room policy for a contract
   */
  get(ctx: Context, contractId: string): Promise<GetResult>;

  /**
   * List delegate policies
   */
  listDelegates(ctx: Context, contractId: string): Promise<ListDelegatesResult>;

  /**
   * Get delegate clean room policy
   */
  getDelegate(
    ctx: Context,
    contractId: string,
    delegateType: string,
    delegateId: string,
  ): Promise<GetDelegateResult>;

  /**
   * Set delegate clean room policy
   */
  setDelegate(
    ctx: Context,
    contractId: string,
    delegateType: string,
    delegateId: string,
    policy: unknown,
  ): Promise<void>;
}

export interface Deployment<Context = unknown> {
  /**
   * Get deployment specification
   */
  getSpec(ctx: Context, contractId: string): Promise<GetSpecResult>;

  /**
   * Get deployment information
   */
  getInfo(ctx: Context, contractId: string): Promise<GetInfoResult>;
}

export interface OAuth<Context = unknown> {
  /**
   * Get OAuth token
   */
  getToken(
    ctx: Context,
    contractId: string,
    request: unknown,
  ): Promise<GetTokenResult>;
}

export interface CertificateAuthority<Context = unknown> {
  /**
   * Generate CA signing key
   */
  generateSigningKey(ctx: Context, contractId: string): Promise<void>;

  /**
   * Generate endorsed certificate
   */
  generateEndorsedCert(
    ctx: Context,
    contractId: string,
    request: GenerateEndorsedCertRequest,
  ): Promise<GenerateEndorsedCertResult>;

  /**
   * Get CA information
   */
  getInfo(ctx: Context, contractId: string): Promise<CaInfo>;
}

export interface MemberDocuments<Context = unknown> {
  /**
   * List all member documents
   */
  list(ctx: Context): Promise<ListResult>;

  /**
   * Create or update a member document
   */
  put(
    ctx: Context,
    documentId: string,
    document: PutMemberDocumentRequest,
  ): Promise<void>;

  /**
   * Get a member document
   */
  get(ctx: Context, documentId: string): Promise<GetMemberDocumentResponse>;
}

export interface AcceptedMemberDocuments<Context = unknown> {
  /**
   * Get accepted member document
   */
  get(
    ctx: Context,
    contractId: string,
    documentId: string,
    request: GetAcceptedMemberDocumentRequest,
  ): Promise<GetAcceptedMemberDocumentResponse>;
}

export interface UserIdentities<Context = unknown> {
  /**
   * List all user identities
   */
  list(ctx: Context): Promise<ListResult>;

  /**
   * Get a user identity
   */
  get(ctx: Context, identityId: string): Promise<GetResult>;
}

export interface ContractUsers<Context = unknown> {
  /**
   * Check if user is active
   */
  isActive(ctx: Context, contractId: string): Promise<IsActiveResult>;
}

export interface UserInvitations<Context = unknown> {
  /**
   * List all user invitations
   */
  list(ctx: Context): Promise<ListResult>;

  /**
   * Get a user invitation
   */
  get(ctx: Context, invitationId: string): Promise<GetResult>;

  /**
   * Accept a user invitation
   */
  accept(ctx: Context, invitationId: string): Promise<void>;
}

export interface UserDocuments<Context = unknown> {
  /**
   * List all user documents
   */
  list(ctx: Context, options?: ListOptions): Promise<ListUserDocumentsResponse>;

  /**
   * Create or update a user document
   */
  put(
    ctx: Context,
    documentId: string,
    document: PutUserDocumentRequest,
  ): Promise<void>;

  /**
   * Get a user document
   */
  get(ctx: Context, documentId: string): Promise<GetUserDocumentResponse>;
}

export interface AcceptedUserDocuments<Context = unknown> {
  /**
   * Get accepted user document
   */
  get(
    ctx: Context,
    contractId: string,
    documentId: string,
    request: GetAcceptedUserDocumentRequest,
  ): Promise<GetAcceptedUserDocumentResponse>;
}

export interface UserDocumentRuntimeOptionsConsent<Context = unknown> {
  /**
   * Consent check for user document runtime option
   */
  consentCheck(
    ctx: Context,
    contractId: string,
    documentId: string,
    option: string,
  ): Promise<ConsentCheckResult>;
}

export interface UserDocumentRuntimeOptions<Context = unknown> {
  /**
   * Check user document runtime option status
   */
  checkStatus(
    ctx: Context,
    documentId: string,
    option: string,
  ): Promise<CheckStatusResult>;

  /**
   * Enable user document runtime option
   */
  enable(ctx: Context, documentId: string, option: string): Promise<void>;

  /**
   * Disable user document runtime option
   */
  disable(ctx: Context, documentId: string, option: string): Promise<void>;
}

export interface Proposals<Context = unknown> {
  /**
   * Get proposal historical data
   */
  getHistorical(ctx: Context, proposalId: string): Promise<GetHistoricalResult>;
}

export interface UserProposals<Context = unknown> {
  /**
   * Get a user proposal
   */
  get(ctx: Context, proposalId: string): Promise<GetUserProposalResponse>;

  /**
   * Create or update a user proposal
   */
  put(
    ctx: Context,
    proposalId: string,
    proposal: CreateUserProposalRequest,
  ): Promise<CreateUserProposalResponse>;

  /**
   * Get user proposal status
   */
  getStatus(ctx: Context, proposalId: string): Promise<GetStatusResult>;

  /**
   * Withdraw a user proposal
   */
  withdraw(ctx: Context, proposalId: string): Promise<void>;

  /**
   * Submit ballot for user proposal
   */
  submitBallot(
    ctx: Context,
    proposalId: string,
    ballot: SubmitUserProposalBallotRequest,
  ): Promise<void>;
}

export interface Oidc<Context = unknown> {
  /**
   * Get OIDC configuration
   */
  getConfiguration(ctx: Context): Promise<GetConfigurationResult>;

  /**
   * Get JWKS (JSON Web Key Set)
   */
  getJwks(ctx: Context): Promise<GetJwksResult>;

  /**
   * Generate OIDC signing key
   */
  generateSigningKey(ctx: Context): Promise<void>;

  /**
   * Set OIDC issuer URL
   */
  setIssuerUrl(ctx: Context, request: SetIssuerUrlRequestBody): Promise<void>;

  /**
   * Get OIDC issuer information
   */
  getIssuerInfo(ctx: Context): Promise<GetIssuerInfoResult>;
}

export interface RuntimeOptions<Context = unknown> {
  /**
   * Check runtime option status
   */
  checkStatus(ctx: Context, option: string): Promise<CheckStatusResult>;
}

/**
 * TCB (Trusted Computing Base) version
 */
export interface TcbVersion {
  /**
   * Boot loader version
   */
  bootLoader: number;

  /**
   * TEE version
   */
  tee: number;

  /**
   * SNP version
   */
  snp: number;

  /**
   * Microcode version
   */
  microcode: number;
}

/**
 * SNP attestation result
 */
export interface SnpAttestationResult {
  /**
   * Attestation details
   */
  attestation: AttestationDetails;

  /**
   * UVM endorsements
   */
  uvmEndorsements?: UvmEndorsements;
}

/**
 * Attestation details
 */
export interface AttestationDetails {
  /**
   * Attestation version
   */
  version: number;

  /**
   * Guest SVN
   */
  guestSvn: number;

  /**
   * Policy configuration
   */
  policy: PolicyConfig;

  /**
   * Family ID
   */
  familyId: string;

  /**
   * Image ID
   */
  imageId: string;

  /**
   * VMPL level
   */
  vmpl: number;

  /**
   * Signature algorithm
   */
  signatureAlgo: number;

  /**
   * Platform version
   */
  platformVersion: TcbVersion;

  /**
   * Platform information
   */
  platformInfo: PlatformInfo;

  /**
   * Flags
   */
  flags: AttestationFlags;

  /**
   * Report data
   */
  reportData: string;

  /**
   * Measurement
   */
  measurement: string;

  /**
   * Host data
   */
  hostData: string;

  /**
   * ID key digest
   */
  idKeyDigest: string;

  /**
   * Author key digest
   */
  authorKeyDigest: string;

  /**
   * Report ID
   */
  reportId: string;

  /**
   * Report ID MA
   */
  reportIdMa: string;

  /**
   * Reported TCB
   */
  reportedTcb: TcbVersion;

  /**
   * Chip ID
   */
  chipId: string;

  /**
   * Committed TCB
   */
  committedTcb: TcbVersion;

  /**
   * Current minor version
   */
  currentMinor: number;

  /**
   * Current build version
   */
  currentBuild: number;

  /**
   * Current major version
   */
  currentMajor: number;

  /**
   * Committed build version
   */
  committedBuild: number;

  /**
   * Committed minor version
   */
  committedMinor: number;

  /**
   * Committed major version
   */
  committedMajor: number;

  /**
   * Launch TCB
   */
  launchTcb: TcbVersion;

  /**
   * Signature
   */
  signature: EcdsaSignature;
}

/**
 * Policy configuration
 */
export interface PolicyConfig {
  /**
   * ABI minor version
   */
  abiMinor: number;

  /**
   * ABI major version
   */
  abiMajor: number;

  /**
   * SMT enabled
   */
  smt: number;

  /**
   * Migrate MA
   */
  migrateMa: number;

  /**
   * Debug enabled
   */
  debug: number;

  /**
   * Single socket
   */
  singleSocket: number;
}

/**
 * Platform information
 */
export interface PlatformInfo {
  /**
   * SMT enabled
   */
  smtEn: number;

  /**
   * TSME enabled
   */
  tsmeEn: number;
}

/**
 * Attestation flags
 */
export interface AttestationFlags {
  /**
   * Author key enabled
   */
  authorKeyEn: number;

  /**
   * Mask chip key
   */
  maskChipKey: number;

  /**
   * Signing key
   */
  signingKey: number;
}

/**
 * ECDSA signature
 */
export interface EcdsaSignature {
  /**
   * R component
   */
  r: string;

  /**
   * S component
   */
  s: string;
}

/**
 * UVM endorsements
 */
export interface UvmEndorsements {
  /**
   * DID
   */
  did: string;

  /**
   * Feed
   */
  feed: string;

  /**
   * SVN
   */
  svn: string;
}

/**
 * CVM SNP attestation evidence collected via the vTPM path.
 */
export interface CvmSnpAttestationEvidence {
  /**
   * Base64 encoded TPM quote.
   */
  tpmQuote: string;

  /**
   * Base64 encoded HCL report.
   */
  hclReport: string;

  /**
   * Base64 encoded SNP report.
   */
  snpReport: string;

  /**
   * Base64 encoded AIK certificate.
   */
  aikCert: string;

  /**
   * PCR values as key-value pairs.
   */
  pcrs: Record<string, string>;
}

/**
 * Input for CVM SNP attestation verification.
 */
export interface CvmSnpAttestationInput {
  /**
   * The attestation evidence.
   */
  evidence: CvmSnpAttestationEvidence;

  /**
   * Nonce for replay protection.
   */
  nonce: string;
}

/**
 * Event store item
 */
export interface EventStoreItem {
  /**
   * Event timestamp
   */
  timestamp: string;

  /**
   * Event data as binary
   */
  data: Uint8Array;
}

/**
 * Accepted contract store item
 */
export interface AcceptedContractStoreItem {
  /**
   * Contract data
   */
  data: unknown;

  /**
   * Proposal ID
   */
  proposalId: string;

  /**
   * Final votes
   */
  finalVotes: unknown;
}

/**
 * Contract store item
 */
export interface ContractStoreItem {
  /**
   * Contract data
   */
  data: unknown;
}

/**
 * Contract execution status store item
 */
export interface ContractExecutionStatusStoreItem {
  /**
   * Serialized member to status map
   */
  serializedMemberToStatusMap: string;
}

/**
 * Contract logging status store item
 */
export interface ContractLoggingStatusStoreItem {
  /**
   * Status
   */
  status: string;
}

/**
 * Contract telemetry status store item
 */
export interface ContractTelemetryStatusStoreItem {
  /**
   * Status
   */
  status: string;
}

/**
 * Accepted member document store item
 */
export interface AcceptedMemberDocumentStoreItem {
  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Document data
   */
  data: unknown;

  /**
   * Proposal ID
   */
  proposalId: string;

  /**
   * Final votes
   */
  finalVotes: unknown;
}

/**
 * Document store item
 */
export interface DocumentStoreItem {
  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Document data
   */
  data: unknown;
}

/**
 * User document runtime option status store item
 */
export interface UserDocumentRuntimeOptionStatusStoreItem {
  /**
   * Serialized approver to status map
   */
  serializedApproverToStatusMap: string;
}

/**
 * Accepted user document store item
 */
export interface AcceptedUserDocumentStoreItem {
  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Document data
   */
  data: unknown;

  /**
   * Labels
   */
  labels: Record<string, string>;

  /**
   * Proposal ID
   */
  proposalId: string;

  /**
   * Proposer ID
   */
  proposerId: string;

  /**
   * Approvers
   */
  approvers?: UserProposalApprover[];

  /**
   * Final votes
   */
  finalVotes: UserVote[];
}

/**
 * User document store item
 */
export interface UserDocumentStoreItem {
  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Document data
   */
  data: unknown;

  /**
   * Labels
   */
  labels: Record<string, string>;

  /**
   * Approvers
   */
  approvers?: UserProposalApprover[];
}

/**
 * Proposal store item
 */
export interface ProposalStoreItem {
  /**
   * Actions
   */
  actions: Action[];
}

/**
 * Action
 */
export interface Action {
  /**
   * Action name
   */
  name: string;

  /**
   * Action arguments
   */
  args: unknown;
}

/**
 * Proposal info item
 */
export interface ProposalInfoItem {
  /**
   * Proposal state
   */
  state: string;
}

/**
 * User proposal store item
 */
export interface UserProposalStoreItem {
  /**
   * User actions
   */
  actions: UserAction[];
}

/**
 * User action
 */
export interface UserAction {
  /**
   * Action name
   */
  name: string;

  /**
   * Approvers
   */
  approvers?: UserProposalApprover[];

  /**
   * Action arguments
   */
  args: unknown;
}

/**
 * User proposal info item
 */
export interface UserProposalInfoItem {
  /**
   * Proposer ID
   */
  proposerId: string;

  /**
   * Proposal state
   */
  state: string;

  /**
   * Ballots
   */
  ballots: UserVote[];
}

/**
 * Secret store item
 */
export interface SecretStoreItem {
  /**
   * Secret value
   */
  value: string;
}

/**
 * Delegate policy info item
 */
export interface DelegatePolicyInfoItem {
  /**
   * Delegate type
   */
  delegateType: string;

  /**
   * Delegate ID
   */
  delegateId: string;
}

/**
 * Signing key item
 */
export interface SigningKeyItem {
  /**
   * Key ID
   */
  kid: string;

  /**
   * Request ID
   */
  reqId: string;

  /**
   * Public key
   */
  publicKey: string;

  /**
   * Private key
   */
  privateKey: string;
}

/**
 * Deployment spec item
 */
export interface DeploymentSpecItem {
  /**
   * Deployment specification data
   */
  data: unknown;
}

/**
 * Deployment info item
 */
export interface DeploymentInfoItem {
  /**
   * Deployment information data
   */
  data: unknown;
}

/**
 * Runtime option store item
 */
export interface RuntimeOptionStoreItem {
  /**
   * Status
   */
  status: string;
}

/**
 * User identity store item
 */
export interface UserIdentityStoreItem {
  /**
   * Account type
   */
  accountType: string;

  /**
   * Invitation ID
   */
  invitationId: string;

  /**
   * User data
   */
  data: unknown;
}

/**
 * User invitation store item
 */
export interface UserInvitationStoreItem {
  /**
   * Account type
   */
  accountType: string;
}

/**
 * User invitation info store item
 */
export interface UserInvitationInfoStoreItem {
  /**
   * Invitation status
   */
  status: string;

  /**
   * User information
   */
  userInfo: UserInfo;
}

/**
 * User information
 */
export interface UserInfo {
  /**
   * User ID
   */
  userId: string;

  /**
   * User data
   */
  data: UserData;
}

/**
 * User data
 */
export interface UserData {
  /**
   * Tenant ID
   */
  tenantId?: string;
}

/**
 * Accepted user invitation store item
 */
export interface AcceptedUserInvitationStoreItem {}

/**
 * Set contract args
 */
export interface SetContractArgs {
  /**
   * Contract ID
   */
  contractId: string;

  /**
   * Contract
   */
  contract: PutContractRequest;
}

/**
 * Put secret by clean room request data
 */
export interface PutSecretByCleanRoomRequestData {
  /**
   * Secret value
   */
  value: string;
}

/**
 * Set member document args
 */
export interface SetMemberDocumentArgs {
  /**
   * Document ID
   */
  documentId: string;

  /**
   * Document
   */
  document: PutMemberDocumentRequest;
}

/**
 * Set user document args
 */
export interface SetUserDocumentArgs {
  /**
   * Document ID
   */
  documentId: string;

  /**
   * Document
   */
  document: PutUserDocumentRequest;
}

/**
 * CA config item
 */
export interface CaConfigItem {
  /**
   * CA enabled status
   */
  enabled: string;

  /**
   * Request ID
   */
  requestId: string;
}

/**
 * CA key item
 */
export interface CaKeyItem {
  /**
   * Request ID
   */
  requestId: string;

  /**
   * Public key
   */
  publicKey: string;

  /**
   * Private key
   */
  privateKey: string;

  /**
   * CA certificate
   */
  caCert: string;
}

/**
 * Generate endorsed cert request data
 */
export interface GenerateEndorsedCertRequestData {
  /**
   * Public key
   */
  publicKey: string;

  /**
   * Subject name
   */
  subjectName: string;

  /**
   * Subject alternate names
   */
  subjectAlternateNames?: string[];

  /**
   * Validity period in days
   */
  validityPeriodDays: number;
}

/**
 * Error response
 */
export interface ErrorResponse {
  /**
   * Error details
   */
  error: ErrorDetails;
}

/**
 * Error details
 */
export interface ErrorDetails {
  /**
   * Error code
   */
  code: string;

  /**
   * Error message
   */
  message: string;
}

/**
 * Get token request
 */
export interface GetTokenRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Encryption info
   */
  encrypt: Encrypt;
}

/**
 * Get token response
 */
export interface GetTokenResponse {
  /**
   * Token value
   */
  value: string;
}

/**
 * Set subject policy request
 */
export interface SetSubjectPolicyRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Encryption info
   */
  encrypt: Encrypt;

  /**
   * Signature
   */
  sign: Sign;

  /**
   * Encrypted request data
   */
  data: string;
}

/**
 * Set subject policy request data
 */
export interface SetSubjectPolicyRequestData {
  /**
   * Policy type
   */
  _type: string;

  /**
   * Policy claims
   */
  claims: unknown;
}

/**
 * Discovery response
 */
export interface DiscoveryResponse {
  /**
   * Supported response types
   */
  response_TypesSupported: string[];

  /**
   * Supported ID token signing algorithms
   */
  id_TokenSigningAlgValuesSupported: string[];

  /**
   * Issuer URL
   */
  issuer: string;

  /**
   * JWKS URI
   */
  jwks_Uri: string;

  /**
   * Supported claims
   */
  claims_Supported?: string[];
}

/**
 * JWKS response
 */
export interface JwksResponse {
  /**
   * Array of JWK keys
   */
  keys: Jwk[];
}

/**
 * JSON Web Key
 */
export interface Jwk {
  /**
   * Algorithm
   */
  alg: string;

  /**
   * Usage
   */
  use: string;

  /**
   * Exponent
   */
  e: string;

  /**
   * Modulus
   */
  n: string;

  /**
   * Key ID
   */
  kid: string;

  /**
   * Key type
   */
  kty: string;

  /**
   * X.509 certificate chain
   */
  x5c?: string[];

  /**
   * X.509 certificate SHA-1 thumbprint
   */
  x5t?: string;
}

/**
 * OIDC issuer info
 */
export interface OidcIssuerInfo {
  /**
   * Issuer enabled
   */
  enabled: boolean;

  /**
   * Issuer URL
   */
  issuerUrl?: string;

  /**
   * Tenant data
   */
  tenantData?: TenantData;
}

/**
 * Tenant data
 */
export interface TenantData {
  /**
   * Tenant ID
   */
  tenantId: string;

  /**
   * Issuer URL
   */
  issuerUrl: string;
}

/**
 * Get proposal response
 */
export interface GetProposalResponse {
  /**
   * Next link for pagination
   */
  nextLink?: string;

  /**
   * Array of proposals
   */
  value: Proposal[];
}

/**
 * Proposal
 */
export interface Proposal {
  /**
   * Sequence number
   */
  seqno: number;

  /**
   * Proposal state
   */
  proposalState: string;

  /**
   * Proposal ID
   */
  proposalId: string;
}

/**
 * Member info
 */
export interface MemberInfo {
  /**
   * Member data
   */
  memberData: MemberData;
}

/**
 * Member data
 */
export interface MemberData {
  /**
   * Is operator
   */
  isOperator: boolean;

  /**
   * Tenant ID
   */
  tenantId: string;
}

/**
 * List user identities response
 */
export interface ListUserIdentitiesResponse {
  /**
   * Array of user identities
   */
  value: GetUserIdentityResponse[];
}

/**
 * Get user identity response
 */
export interface GetUserIdentityResponse {
  /**
   * User ID
   */
  id: string;

  /**
   * Account type
   */
  accountType: string;

  /**
   * Invitation ID
   */
  invitationId: string;

  /**
   * User data
   */
  data: unknown;
}

/**
 * List user invitations response
 */
export interface ListUserInvitationsResponse {
  /**
   * Array of user invitations
   */
  value: GetUserInvitationResponse[];
}

/**
 * Get user invitation response
 */
export interface GetUserInvitationResponse {
  /**
   * Invitation ID
   */
  invitationId: string;

  /**
   * Account type
   */
  accountType: string;

  /**
   * Tenant ID
   */
  tenantId?: string;

  /**
   * Claims
   */
  claims: unknown;

  /**
   * Invitation status
   */
  status?: string;

  /**
   * User information
   */
  userInfo?: UserInfo;
}

/**
 * Get clean room policy response
 */
export interface GetCleanRoomPolicyResponse {
  /**
   * Proposal IDs
   */
  proposalIds: string[];

  /**
   * Policy data
   */
  policy: unknown;
}

/**
 * Set clean room policy args
 */
export interface SetCleanRoomPolicyArgs {
  /**
   * Contract ID
   */
  contractId: string;
}

/**
 * Set delegate clean room policy request
 */
export interface SetDelegateCleanRoomPolicyRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;

  /**
   * Encryption info
   */
  encrypt: Encrypt;

  /**
   * Signature
   */
  sign: Sign;

  /**
   * Encrypted request data
   */
  data: string;
}

/**
 * Set delegate clean room policy request data
 */
export interface SetDelegateCleanRoomPolicyRequestData {
  /**
   * Delegate type
   */
  delegateType: string;

  /**
   * Delegate claims
   */
  claims: unknown;

  /**
   * Policy type that identifies the set of claims
   */
  policyType: string;
}

/**
 * List delegate policies response
 */
export interface ListDelegatePoliciesResponse {
  /**
   * Array of delegate policies
   */
  value: ListDelegatePolicyResponse[];
}

/**
 * List delegate policy response
 */
export interface ListDelegatePolicyResponse {
  /**
   * Delegate type
   */
  delegateType: string;

  /**
   * Delegate ID
   */
  delegateId: string;
}

/**
 * Get runtime option response
 */
export interface GetRuntimeOptionResponse {
  /**
   * Runtime option status
   */
  status: string;

  /**
   * Error reason
   */
  reason?: ErrorReason;

  /**
   * Proposal IDs
   */
  proposalIds?: string[];
}

/**
 * Error reason
 */
export interface ErrorReason {
  /**
   * Error code
   */
  code: string;

  /**
   * Error message
   */
  message: string;
}

/**
 * Consent check request
 */
export interface ConsentCheckRequest {
  /**
   * Attestation evidence
   */
  attestation: SnpEvidence;
}

/**
 * Get deployment info response
 */
export interface GetDeploymentInfoResponse {
  /**
   * Proposal IDs
   */
  proposalIds: string[];

  /**
   * Deployment info data
   */
  data: unknown;
}

/**
 * Set deployment info args
 */
export interface SetDeploymentInfoArgs {
  /**
   * Contract ID
   */
  contractId: string;
}

/**
 * Get deployment spec response
 */
export interface GetDeploymentSpecResponse {
  /**
   * Proposal IDs
   */
  proposalIds: string[];

  /**
   * Deployment spec data
   */
  data: unknown;
}

/**
 * Set deployment spec args
 */
export interface SetDeploymentSpecArgs {
  /**
   * Contract ID
   */
  contractId: string;
}

export const GetEventsResponse = {
  toJsonObject(input: GetEventsResponse): any {
    return {
      nextLink: input.nextLink,
      value: input.value?.map((item) => Event.toJsonObject(item)),
    };
  },
  fromJsonObject(input: any): GetEventsResponse {
    return {
      nextLink: input.nextLink,
      value: input.value?.map((item: any) => Event.fromJsonObject(item)),
    };
  },
} as const;

export const PutEventRequest = {
  toJsonObject(input: PutEventRequest): any {
    return {
      timestamp: input.timestamp,
      attestation: SnpEvidence.toJsonObject(input.attestation),
      sign: input.sign,
      data: input.data,
    };
  },
  fromJsonObject(input: any): PutEventRequest {
    return {
      timestamp: input.timestamp,
      attestation: SnpEvidence.fromJsonObject(input.attestation),
      sign: input.sign as Sign,
      data: input.data,
    };
  },
} as const;

export const GetSecretRequest = {
  toJsonObject(input: GetSecretRequest): any {
    return {
      attestation: SnpEvidence.toJsonObject(input.attestation),
      encrypt: input.encrypt,
    };
  },
  fromJsonObject(input: any): GetSecretRequest {
    return {
      attestation: SnpEvidence.fromJsonObject(input.attestation),
      encrypt: input.encrypt as Encrypt,
    };
  },
} as const;

export const GenerateEndorsedCertRequest = {
  toJsonObject(input: GenerateEndorsedCertRequest): any {
    return {
      attestation: SnpEvidence.toJsonObject(input.attestation),
      encrypt: input.encrypt,
      sign: input.sign,
      data: input.data,
    };
  },
  fromJsonObject(input: any): GenerateEndorsedCertRequest {
    return {
      attestation: SnpEvidence.fromJsonObject(input.attestation),
      encrypt: input.encrypt as Encrypt,
      sign: input.sign as Sign,
      data: input.data,
    };
  },
} as const;

export const GetAcceptedMemberDocumentRequest = {
  toJsonObject(input: GetAcceptedMemberDocumentRequest): any {
    return {
      attestation: SnpEvidence.toJsonObject(input.attestation),
      encrypt: input.encrypt,
    };
  },
  fromJsonObject(input: any): GetAcceptedMemberDocumentRequest {
    return {
      attestation: SnpEvidence.fromJsonObject(input.attestation),
      encrypt: input.encrypt as Encrypt,
    };
  },
} as const;

export const GetAcceptedUserDocumentRequest = {
  toJsonObject(input: GetAcceptedUserDocumentRequest): any {
    return {
      attestation: SnpEvidence.toJsonObject(input.attestation),
      encrypt: input.encrypt,
    };
  },
  fromJsonObject(input: any): GetAcceptedUserDocumentRequest {
    return {
      attestation: SnpEvidence.fromJsonObject(input.attestation),
      encrypt: input.encrypt as Encrypt,
    };
  },
} as const;

export const Event = {
  toJsonObject(input: Event): any {
    return {
      timestamp: input.timestamp,
      timestamp_iso: input.timestampIso,
      scope: input.scope,
      id: input.id,
      seqno: input.seqno,
      data: input.data,
    };
  },
  fromJsonObject(input: any): Event {
    return {
      timestamp: input.timestamp,
      timestampIso: input.timestamp_iso,
      scope: input.scope,
      id: input.id,
      seqno: input.seqno,
      data: input.data,
    };
  },
} as const;

export const SnpEvidence = {
  toJsonObject(input: SnpEvidence): any {
    return {
      evidence: input.evidence,
      endorsements: input.endorsements,
      uvm_endorsements: input.uvmEndorsements,
      endorsed_tcb: input.endorsedTcb,
    };
  },
  fromJsonObject(input: any): SnpEvidence {
    return {
      evidence: input.evidence,
      endorsements: input.endorsements,
      uvmEndorsements: input.uvm_endorsements,
      endorsedTcb: input.endorsed_tcb,
    };
  },
} as const;
