"""
Auto-generated operational events file.
DO NOT EDIT THIS FILE MANUALLY - it is generated by generator.py
"""

import enum

from .operational_event import OperationalEvent


class OperationalEventType(enum.Enum):
    """Enum for operational event types."""

    DATASET_LOAD_COMPLETED = "DATASET_LOAD_COMPLETED"
    DATASET_LOAD_FAILED = "DATASET_LOAD_FAILED"
    DATASET_LOAD_STARTED = "DATASET_LOAD_STARTED"
    DATASET_WRITE_COMPLETED = "DATASET_WRITE_COMPLETED"
    DATASET_WRITE_FAILED = "DATASET_WRITE_FAILED"
    DATASET_WRITE_STARTED = "DATASET_WRITE_STARTED"
    QUERY_EXECUTION_COMPLETED = "QUERY_EXECUTION_COMPLETED"
    QUERY_EXECUTION_FAILED = "QUERY_EXECUTION_FAILED"
    QUERY_EXECUTION_STARTED = "QUERY_EXECUTION_STARTED"
    QUERY_SEGMENT_EXECUTION_COMPLETED = "QUERY_SEGMENT_EXECUTION_COMPLETED"
    QUERY_SEGMENT_EXECUTION_FAILED = "QUERY_SEGMENT_EXECUTION_FAILED"
    QUERY_SEGMENT_EXECUTION_STARTED = "QUERY_SEGMENT_EXECUTION_STARTED"


class OperationalEventFactory:
    """Factory class for OperationalEvent instances."""

    @staticmethod
    def DatasetLoadCompleted(
        dataset_name: str, dataset_path: str, row_count: str
    ) -> OperationalEvent:
        """
        Create DATASET_LOAD_COMPLETED event.

        Message: Dataset {dataset_name} loaded successfully from {dataset_path} with {row_count} rows
        """
        return OperationalEvent(
            id=1002,
            name=OperationalEventType.DATASET_LOAD_COMPLETED.value,
            message="Dataset {dataset_name} loaded successfully from {dataset_path} with {row_count} rows",
            parameters={
                "dataset_name": dataset_name,
                "dataset_path": dataset_path,
                "row_count": row_count,
            },
        )

    @staticmethod
    def DatasetLoadFailed(
        dataset_name: str, dataset_path: str, error: str
    ) -> OperationalEvent:
        """
        Create DATASET_LOAD_FAILED event.

        Message: Failed to load dataset {dataset_name} from {dataset_path}: {error}
        """
        return OperationalEvent(
            id=1003,
            name=OperationalEventType.DATASET_LOAD_FAILED.value,
            message="Failed to load dataset {dataset_name} from {dataset_path}: {error}",
            parameters={
                "dataset_name": dataset_name,
                "dataset_path": dataset_path,
                "error": error,
            },
        )

    @staticmethod
    def DatasetLoadStarted(
        dataset_name: str, dataset_path: str, end_date: str, start_date: str
    ) -> OperationalEvent:
        """
        Create DATASET_LOAD_STARTED event.

        Message: Started loading dataset {dataset_name} from {dataset_path} for start_date: {start_date}, end_date: {end_date}
        """
        return OperationalEvent(
            id=1001,
            name=OperationalEventType.DATASET_LOAD_STARTED.value,
            message="Started loading dataset {dataset_name} from {dataset_path} for start_date: {start_date}, end_date: {end_date}",
            parameters={
                "dataset_name": dataset_name,
                "dataset_path": dataset_path,
                "end_date": end_date,
                "start_date": start_date,
            },
        )

    @staticmethod
    def DatasetWriteCompleted(
        dataset_name: str, output_path: str, row_count: str
    ) -> OperationalEvent:
        """
        Create DATASET_WRITE_COMPLETED event.

        Message: Output to datasink {dataset_name} written successfully at {output_path} with {row_count} rows
        """
        return OperationalEvent(
            id=1005,
            name=OperationalEventType.DATASET_WRITE_COMPLETED.value,
            message="Output to datasink {dataset_name} written successfully at {output_path} with {row_count} rows",
            parameters={
                "dataset_name": dataset_name,
                "output_path": output_path,
                "row_count": row_count,
            },
        )

    @staticmethod
    def DatasetWriteFailed(
        dataset_name: str, error: str, output_path: str
    ) -> OperationalEvent:
        """
        Create DATASET_WRITE_FAILED event.

        Message: Failed to write dataset {dataset_name} to {output_path}: {error}
        """
        return OperationalEvent(
            id=1006,
            name=OperationalEventType.DATASET_WRITE_FAILED.value,
            message="Failed to write dataset {dataset_name} to {output_path}: {error}",
            parameters={
                "dataset_name": dataset_name,
                "error": error,
                "output_path": output_path,
            },
        )

    @staticmethod
    def DatasetWriteStarted(dataset_name: str, output_path: str) -> OperationalEvent:
        """
        Create DATASET_WRITE_STARTED event.

        Message: Started writing dataset {dataset_name} to {output_path}
        """
        return OperationalEvent(
            id=1004,
            name=OperationalEventType.DATASET_WRITE_STARTED.value,
            message="Started writing dataset {dataset_name} to {output_path}",
            parameters={"dataset_name": dataset_name, "output_path": output_path},
        )

    @staticmethod
    def QueryExecutionCompleted(duration_sec: str) -> OperationalEvent:
        """
        Create QUERY_EXECUTION_COMPLETED event.

        Message: Query execution completed successfully in {duration_sec} seconds
        """
        return OperationalEvent(
            id=1011,
            name=OperationalEventType.QUERY_EXECUTION_COMPLETED.value,
            message="Query execution completed successfully in {duration_sec} seconds",
            parameters={"duration_sec": duration_sec},
        )

    @staticmethod
    def QueryExecutionFailed(error: str) -> OperationalEvent:
        """
        Create QUERY_EXECUTION_FAILED event.

        Message: Query execution failed: {error}
        """
        return OperationalEvent(
            id=1012,
            name=OperationalEventType.QUERY_EXECUTION_FAILED.value,
            message="Query execution failed: {error}",
            parameters={"error": error},
        )

    @staticmethod
    def QueryExecutionStarted() -> OperationalEvent:
        """
        Create QUERY_EXECUTION_STARTED event.

        Message: Query execution started
        """
        return OperationalEvent(
            id=1010,
            name=OperationalEventType.QUERY_EXECUTION_STARTED.value,
            message="Query execution started",
            parameters={},
        )

    @staticmethod
    def QuerySegmentExecutionCompleted(
        row_count: str, step_number: str
    ) -> OperationalEvent:
        """
        Create QUERY_SEGMENT_EXECUTION_COMPLETED event.

        Message: Query segment in step {step_number} completed with {row_count} rows
        """
        return OperationalEvent(
            id=1008,
            name=OperationalEventType.QUERY_SEGMENT_EXECUTION_COMPLETED.value,
            message="Query segment in step {step_number} completed with {row_count} rows",
            parameters={"row_count": row_count, "step_number": step_number},
        )

    @staticmethod
    def QuerySegmentExecutionFailed(error: str, step_number: str) -> OperationalEvent:
        """
        Create QUERY_SEGMENT_EXECUTION_FAILED event.

        Message: Query segment in step {step_number} failed with error: {error}
        """
        return OperationalEvent(
            id=1009,
            name=OperationalEventType.QUERY_SEGMENT_EXECUTION_FAILED.value,
            message="Query segment in step {step_number} failed with error: {error}",
            parameters={"error": error, "step_number": step_number},
        )

    @staticmethod
    def QuerySegmentExecutionStarted(step_number: str) -> OperationalEvent:
        """
        Create QUERY_SEGMENT_EXECUTION_STARTED event.

        Message: Started executing query segment in step {step_number}
        """
        return OperationalEvent(
            id=1007,
            name=OperationalEventType.QUERY_SEGMENT_EXECUTION_STARTED.value,
            message="Started executing query segment in step {step_number}",
            parameters={"step_number": step_number},
        )
