openapi: '3.0.3'
info:
  title: Cleanroom Spark Specification
  description: Cleanroom Spark Specification
  version: '1.0'

paths: {}

components:
  schemas:
    SparkApplicationSpecification:
      type: object
      properties:
        name:
          type: string
        application:
          oneOf:
            - $ref: "#/components/schemas/SparkSQLApplication"
            - $ref: "#/components/schemas/SparkMLApplication"
          discriminator:
            propertyName: applicationType
            mapping:
              Spark-SQL: "#/components/schemas/SparkSQLApplication"
              Spark-ML: "#/components/schemas/SparkMLApplication"
      required:
      - name
      - application

    SparkApplicationType:
      type: string
      enum:
      - Spark-SQL
      - Spark-ML

    SparkSQLApplication:
      allOf:
        - $ref: "#/components/schemas/SparkApplicationBase"
        - type: object
          properties:
            query:
              type: string
      required:
      - query

    SparkMLApplication:
      allOf:
        - $ref: "#/components/schemas/SparkApplicationBase"
        - type: object
          properties:
            payload:
              type: string
      required:
      - payload

    SparkApplicationBase:
      type: object
      properties:
        applicationType:
          $ref: "#/components/schemas/SparkApplicationType"
        inputDataset:
          title: Dataset(s) to be presented to the Spark application for reading. 
          type: array
          items:
            $ref: "#/components/schemas/SparkApplicationDatasetDescriptor"
        outputDataset:
          title: Dataset to be presented to the Spark application for writing.
          $ref: "#/components/schemas/SparkApplicationDatasetDescriptor"
      required:
      - applicationType
      - inputDataset
      - outputDataset

    SparkApplicationDatasetDescriptor:
      type: object
      properties:
        specification:
          title: Specification of the dataset to be presented to the Spark application.
          description: |
            ID of document capturing the dataset specification.

            [Specification](dataset.yaml#//components/schemas/DatasetSpecification)
          type: string
        view:
          title: Name of the view to be generated by the Spark application for accessing the dataset.
          type: string
      required:
      - specification
      - view

