name: Release governance client containers
description: Release governance client containers
inputs:
  tag:
    description: The tag
    required: true
  environment:
    description: The environment being released to
    required: true
  registry-name:
    description: The registry to which the images need to be pushed
    required: true
  client-id:
    description: The client ID to connect to the registry
    required: true
  tenant-id:
    description: The tenant ID of the registry
    required: true
  subscription-id:
    description: The subscription ID of the registry
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/release-container
      with:
        name: cgs-client
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: cgs-client
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}

    - uses: ./.github/actions/release-container
      with:
        name: cgs-ui
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: cgs-ui
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}