name: Test Encrypted Storage scenario
description: Test Encrypted Storage scenario
runs:
  using: composite
  steps:
  - name: Delete huge unnecessary tools folder # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    shell: bash
    run: rm -rf /opt/hostedtoolcache

  - name: Add docker user
    shell: bash
    run: sudo usermod -aG docker $USER

  - shell: pwsh
    run: Install-Module -Name powershell-yaml -Force

  - name: Login to Azure and refresh token
    uses: ./.github/actions/login-to-azure
    env:
      CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
      TENANT_ID: ${{ env.AZURE_TENANT_ID }}
      SUBSCRIPTION_ID: ${{ env.SUBSCRIPTION_ID }}

  - name: Login to Cleanroom Build ACR
    shell: bash
    run: az acr login --name cleanroombuild

  - name: Deploy Kind cluster
    shell: bash
    run: bash ./test/onebox/kind-up.sh

  - name: Build clean room containers
    shell: pwsh
    run: ./build/onebox/build-local-cleanroom-containers.ps1

  - name: Run collab scenario on Kind
    shell: pwsh
    run: ./test/onebox/multi-party-collab/encrypted-storage/run-collab.ps1 -registry local

  - name: Dump ob-consumer-client logs
    if: ${{ !cancelled() }}
    shell: pwsh
    run: docker logs ob-consumer-client-cgs-client-1

  - name: Dump ob-publisher-client logs
    if: ${{ !cancelled() }}
    shell: pwsh
    run: docker logs ob-publisher-client-cgs-client-1

  - name: Dump ccf logs
    if: ${{ !cancelled() }}
    shell: pwsh
    run: docker logs ob-ccf-ccf-1

  - name: Dump virtual-cleanroom logs
    if: ${{ !cancelled() }}
    shell: pwsh
    run: kubectl logs -l app=virtual-cleanroom --tail=-1 --all-containers --ignore-errors --prefix

  - name: Delete resource groups
    if: success()
    shell: pwsh
    run: ./test/onebox/multi-party-collab/remove-resources.ps1 -tag "github_actions=multi-party-collab-${{ env.JOB_ID }}-${{ env.RUN_ID }}"