name: Test Encrypted Storage scenario with Cleanroom Client
description: Test Encrypted Storage scenario with Cleanroom Client
inputs:
  repo:
    description: The registry URL
    required: true
  tag:
    description: The tag for the built image
    required: true
runs:
  using: composite
  steps:
    - name: Login to Azure and refresh token
      uses: ./.github/actions/login-to-azure
      env:
        CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        TENANT_ID: ${{ env.AZURE_TENANT_ID }}
        SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Kind cluster
      shell: bash
      run: bash ./test/onebox/kind-up.sh

    - name: Install az cleanroom extension
      shell: bash
      run: |
        oras pull ${{ inputs.repo }}/cli/cleanroom-whl:${{ inputs.tag }}
        az extension add --allow-preview true --source ./cleanroom-*-py2.py3-none-any.whl -y

    - name: Run collab scenario on Kind
      shell: pwsh
      run: ./test/onebox/multi-party-collab/encrypted-storage/cleanroom-client/run-collab.ps1 -registry acr -repo ${{ inputs.repo }} -tag ${{ inputs.tag }}

    - name: Dump credentials-proxy logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: docker logs credentials-proxy

    - name: Dump cleanroom-client logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: docker logs cleanroom-client

    - name: Dump ob-consumer-client logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: docker logs ob-consumer-client-cgs-client-1

    - name: Dump ob-publisher-client logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: docker logs ob-publisher-client-cgs-client-1

    - name: Dump ccf logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: docker logs ob-ccf-encrypted-storage-cl-client-ccf-1

    - name: Dump virtual-cleanroom logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: kubectl logs -l app=virtual-cleanroom --tail=-1 --all-containers --ignore-errors --prefix

    - name: Dump ccr-client-proxy logs
      shell: pwsh
      if: ${{ !cancelled() }}
      run: kubectl logs -l app=ccr-client-proxy --tail=-1 --all-containers --ignore-errors --prefix

    - uses: actions/upload-artifact@v4
      with:
          name: results-encrypted-storage-cleanroom-client
          path: ./test/onebox/multi-party-collab/encrypted-storage/cleanroom-client/generated/results
          overwrite: true
      if: ${{ !cancelled() }}

    - uses: actions/upload-artifact@v4
      with:
          name: configurations-encrypted-storage-cleanroom-client
          path: ./test/onebox/multi-party-collab/encrypted-storage/cleanroom-client/generated/configurations
          overwrite: true
      if: ${{ !cancelled() }}

    - uses: actions/upload-artifact@v4
      with:
          name: deployments-encrypted-storage-cleanroom-client
          path: ./test/onebox/multi-party-collab/encrypted-storage/cleanroom-client/generated/deployments
          overwrite: true
      if: ${{ !cancelled() }}

    - uses: actions/upload-artifact@v4
      with:
          name: ccf-encrypted-storage-cleanroom-client
          path: ./test/onebox/multi-party-collab/encrypted-storage/cleanroom-client/generated/ccf
          overwrite: true
      if: ${{ !cancelled() }}

    - name: Delete resource groups
      shell: pwsh
      if: success()
      run: ./test/onebox/multi-party-collab/remove-resources.ps1 -tag "github_actions=multi-party-collab-${{ env.JOB_ID }}-${{ env.RUN_ID }}"