receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 0
    send_batch_size: 90
    send_batch_max_size: 100

exporters:
  file/traces:
    path: /mnt/telemetry/infrastructure/*.traces
    group_by:
      enabled: true
      resource_attribute: service.name
  file/metrics:
    path: /mnt/telemetry/infrastructure/*.metrics
    group_by:
      enabled: true
      resource_attribute: service.name
  file/logs:
    path: /mnt/telemetry/infrastructure/*.log
    group_by:
      enabled: true
      resource_attribute: service.name
  debug:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200
  debug/noop:
    verbosity: basic
    sampling_initial: 0
    sampling_thereafter: 0

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug, file/traces]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug, file/metrics]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug, file/logs]