{
 "title": "Cleanroom Spark Frontend",
 "description": "Dashboard for Cleanroom Spark Frontend",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "metrics()" } }
  ]
 },
 "panels": [
  {
   "title": "Webhook latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, webhook_name, success) (\r\n    webhook_request_duration_seconds_bucket\r\n  )\r\n)",
     "legendFormat": "0.95-{{webhook_name}}-{{success}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, webhook_name, success) (\r\n    webhook_request_duration_seconds_bucket\r\n  )\r\n)",
     "legendFormat": "0.5-{{webhook_name}}-{{success}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, webhook_name, success) (\r\n    webhook_request_duration_seconds_bucket\r\n  )\r\n)",
     "legendFormat": "0.99-{{webhook_name}}-{{success}}"
    }
   ]
  },
  {
   "title": "Web hook requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (webhook_name, success) (webhook_requests_total)",
     "legendFormat": "{{webhook_name}}-{{success}}"
    }
   ]
  },
  {
   "title": "HTTP metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentile representations of HTTP Request Processing times by Job Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path!~\"/analytics/status/.+\"}[15m])) by (le, path))",
       "legendFormat": "95 percentile - {{path}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{path!~\"/analytics/status/.+\"}[15m])) by (le, path))",
       "legendFormat": "99 percentile - {{path}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{path!~\"/analytics/status/.+\"}[15m])) by (le, path))",
       "legendFormat": "50 percentile - {{path}}"
      }
     ]
    },
    {
     "title": "HTTP Request in past 15 minutes by Path",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (category) (\r\n  label_replace(\r\n    rate(http_requests_total{job=\"cleanroom-spark-frontend\", path=~\"^/analytics/status/.+\"}[15m]),\r\n    \"category\",\r\n    \"/analytics/status\",\r\n    \"path\",\r\n    \"^/analytics/status/.+\"\r\n  )\r\n  or\r\n  label_replace(\r\n    rate(http_requests_total{job=\"cleanroom-spark-frontend\", path!~\"^/analytics/status/.+\"}[15m]),\r\n    \"category\",\r\n    \"$1\",\r\n    \"path\",\r\n    \"^(.*)$\"\r\n  )\r\n)",
       "legendFormat": "{{category}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spark Applications submitted by Job Type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (job_type) (spark_job_submissions_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Spark Applications submitted by Job Type in the last 15 min",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (job_type) (sum(increase(spark_job_submissions_total[15m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentile representations of Spark Job durations by Job Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(spark_job_duration_seconds_bucket[15m])) by (le, job_type))",
       "legendFormat": "95 percentile - {{job_type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(spark_job_duration_seconds_bucket[15m])) by (le, job_type))",
       "legendFormat": "99 percentile - {{job_type}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(spark_job_duration_seconds_bucket[15m])) by (le, job_type))",
       "legendFormat": "50 percentile - {{job_type}}"
      }
     ]
    },
    {
     "title": "Percentile representations of Spark Job submission times by Job Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(spark_job_submission_duration_seconds_bucket[15m])) by (le, job_type))",
       "legendFormat": "95 percentile - {{job_type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(spark_job_submission_duration_seconds_bucket[15m])) by (le, job_type))",
       "legendFormat": "99 percentile - {{job_type}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(spark_job_submission_duration_seconds_bucket[15m])) by (le, job_type))",
       "legendFormat": "50 percentile - {{job_type}}"
      }
     ]
    },
    {
     "title": "HTTP Request Errors in past 15 minutes by Path",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (category, status_code) (\r\n  label_replace(\r\n    rate(http_requests_total{job=\"cleanroom-spark-frontend\", status_code!~\"2..\"}[15m]),\r\n    \"category\",\r\n    \"/analytics/status\",\r\n    \"path\",\r\n    \"^/analytics/status/.+\"\r\n  )\r\n  or\r\n  label_replace(\r\n    rate(http_requests_total{job=\"cleanroom-spark-frontend\", path!~\"^/analytics/status/.+\", status_code!~\"2..\"}[15m]),\r\n    \"category\",\r\n    \"$1\",\r\n    \"path\",\r\n    \"^(.*)$\"\r\n  )\r\n)",
       "legendFormat": "{{category}} - {{ status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Containers View",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "container_cpu_usage_seconds_total{pod=~\"cleanroom-spark-frontend-.*\", job=\"kubernetes-kubelet\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Memory Containers View",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~\"cleanroom-spark-frontend-.*\", job=\"kubernetes-kubelet\"}",
       "legendFormat": "Memory Working Set - {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pod_cpu_usage_seconds_total{pod=~\"cleanroom-spark-frontend-.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pod_memory_working_set_bytes{pod=~\"cleanroom-spark-frontend-.*\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network- Inbound",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_network_receive_bytes_total{pod=~\"cleanroom-spark-frontend-.*\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "container_network_receive_errors_total{pod=~\"cleanroom-spark-frontend-.*\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Network - Outbound",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_network_transmit_bytes_total{pod=~\"cleanroom-spark-frontend-.*\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "container_network_transmit_errors_total{pod=~\"cleanroom-spark-frontend-.*\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  { "title": "Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } }
 ]
}