{
 "title": "Spark-Operator Dashboard",
 "description": "Dashboard with metrics from spark-operator and Kubernetes metrics for visibility into the operator's performance.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Spark-operator Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (vCPU)",
   "type": "timeseries",
   "description": "CPU used by the spark operator and webhook pods",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum((irate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"spark-operator\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory working set used by the spark operator and webhook containers ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"spark-operator\"}) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "description": "Bars show the number of items in the work, the red line shows the rate of change in the queue depth per min",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "workqueue_depth{job=\"kubernetes-pods\", controller=\"spark-application-controller\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(workqueue_depth{job=\"kubernetes-pods\", controller=\"spark-application-controller\"}[1m])) by (name) > 0",
     "legendFormat": "1m rate {{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bytes",
   "type": "timeseries",
   "description": "Amount of data transmitted via the network for the spark operator and webhook",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"spark-operator\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive Bytes",
   "type": "timeseries",
   "description": "Amount of data received via the network for the spark operator and webhook",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"spark-operator\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue - Add Rate",
   "type": "timeseries",
   "description": "Rate of additions to the work queue per min",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"kubernetes-pods\", name=\"spark-application-controller\"}[10m])) by (name)  > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue - Work Latency by Percentile",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes, broken down by percentiles 99%, 90%, and 50%",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(workqueue_work_duration_seconds_bucket{job=\"kubernetes-pods\", name=\"spark-application-controller\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P99"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(workqueue_work_duration_seconds_bucket{job=\"kubernetes-pods\", name=\"spark-application-controller\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P90"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(workqueue_work_duration_seconds_bucket{job=\"kubernetes-pods\", name=\"spark-application-controller\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P50"
    }
   ]
  },
  {
   "title": "Work Queue - Queue Latency by Percentile",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested in percentiles 99%, 95%, and 50%",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kubernetes-pods\", name=\"spark-application-controller\"}[5m])) by (name, le)) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P90"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P50"
    }
   ]
  },
  {
   "title": "Work Queue - Total Retries",
   "type": "timeseries",
   "description": "Total number of retries handled by work queue.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=\"kubernetes-pods\", name=\"spark-application-controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue - Longest Running Controller Thread",
   "type": "timeseries",
   "description": "How many seconds has the longest running processor for workqueue been running.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{job=\"kubernetes-pods\", controller=\"spark-application-controller\"}",
     "legendFormat": "Longest Running Controller Thread"
    }
   ]
  },
  {
   "title": "Work Queue - Unfinished Work",
   "type": "timeseries",
   "description": "How many seconds of work has been done that is in progress and hasn’t been observed by work_duration. Large values indicate stuck threads.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(workqueue_unfinished_work_seconds{job=\"kubernetes-pods\", controller=\"spark-application-controller\"}[5m])) by (name) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Spark Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Start Latency Percentiles",
   "type": "timeseries",
   "description": "Start latency of SparkApplication, broken down by percentiles 99%, 90%, and 50%",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(spark_application_start_latency_seconds_histogram_bucket{job=\"kubernetes-pods\", controller=\"spark-application-controller\"}[5m])) by (pod,le))",
     "legendFormat": "{{pod}} P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(spark_application_start_latency_seconds_histogram_bucket{job=\"spark-operator\"}[5m])) by (pod,le))",
     "legendFormat": "{{pod}} P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(spark_application_start_latency_seconds_histogram_bucket{job=\"spark-operator\"}[5m])) by (pod,le))",
     "legendFormat": "{{pod}} P50"
    }
   ]
  },
  {
   "title": "Spark Jobs Count",
   "type": "gauge",
   "description": "Counters for spark jobs, these are cumulative over the lifetime of the spark-operator pod",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_count) by (pod)",
     "legendFormat": "Total Spark Jobs Created"
    },
    {
     "expr": "sum(spark_application_failure_count) by (pod)",
     "legendFormat": "Total Failed Spark Jobs"
    },
    {
     "expr": "sum(spark_application_success_count) by (pod)",
     "legendFormat": "Total Succesful Spark Jobs"
    },
    {
     "expr": "sum(spark_application_running_count) by (pod)",
     "legendFormat": "Spark Jobs Running"
    },
    {
     "expr": "sum(increase(spark_application_submit_count[5m])) by (pod)",
     "legendFormat": "Jobs Submitted in Last 5min"
    }
   ]
  },
  {
   "title": "Spark Executor Health",
   "type": "piechart",
   "description": "Total number of successful and failed executors",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_success_count)",
     "legendFormat": "Executor Success Count"
    },
    {
     "expr": "sum(spark_executor_failure_count)",
     "legendFormat": "Executor Failure Count"
    }
   ]
  },
  {
   "title": "Spark-submit Rate",
   "type": "timeseries",
   "description": "Total number of SparkApplication spark-submitted by the Operator per min",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(spark_application_submit_count[10m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Running Rate ",
   "type": "timeseries",
   "description": "Percentage of Spark jobs with Running status out of the total submitted jobs.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spark_application_running_count) / sum(spark_application_submit_count) ",
     "legendFormat": "% of Jobs Running"
    }
   ]
  },
  {
   "title": "Job Success Rate ",
   "type": "timeseries",
   "description": "Percentage of Spark jobs with Success status out of the total submitted jobs.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spark_application_success_count) / sum(spark_application_submit_count) ",
     "legendFormat": "% of Jobs completed Successfully"
    }
   ]
  },
  {
   "title": "Job Failure Rate ",
   "type": "timeseries",
   "description": "Percentage of Spark jobs with Failed status out of the total submitted jobs.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spark_application_failure_count) / sum(spark_application_submit_count) ",
     "legendFormat": "% of Jobs Failed"
    }
   ]
  }
 ]
}