{
 "title": "Tempo",
 "description": "Dashboard for Tempo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "metrics()" } }
  ]
 },
 "panels": [
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pod_cpu_usage_seconds_total{pod=\"cleanroom-tempo-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pod_memory_working_set_bytes{pod=\"cleanroom-tempo-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network- Inbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{pod=\"cleanroom-tempo-0\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_network_receive_errors_total{pod=\"cleanroom-tempo-0\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Network - Outbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{pod=\"cleanroom-tempo-0\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_network_transmit_errors_total{pod=\"cleanroom-tempo-0\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Container View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Containers View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=\"cleanroom-tempo-0\", container=\"tempo\", job=\"kubernetes-cadvisor\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Containers View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=\"cleanroom-tempo-0\", container=\"tempo\", job=\"kubernetes-cadvisor\"}",
     "legendFormat": "Memory Working Set - {{container}}"
    }
   ]
  }
 ]
}