version: '3.8'
name: governance-acme
services:
  cgs-client-member0:
    image: cgs-client:latest
    container_name: acme-cgs-client-member0
    ports:
      - "7090:8080"
  ccr-governance:
    image: ccr-governance-virtual:latest
    container_name: acme-ccr-governance
    ports:
      - "7990:8300"
    environment:
      - ccrgovEndpoint=$ccfEndpoint
    volumes:
      - ./sandbox_common:/app/sandbox_common:ro
