// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    public partial class EventsGetEventsRequest
    {
        public string ContractId { get; set; }

        public string Id { get; set; }

        public string Scope { get; set; }

        [JsonPropertyName("from_seqno")]
        public long? FromSeqno { get; set; }

        [JsonPropertyName("to_seqno")]
        public long? ToSeqno { get; set; }

        [JsonPropertyName("max_seqno_per_page")]
        public int? MaxSeqnoPerPage { get; set; }


    }
}
