// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    public partial class GovernanceClientProposeMemberDocumentChangeRequest
    {
        public string DocumentId { get; set; }

        public DocumentProposal Proposal { get; set; }


    }
}
