// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    public partial class GovernanceClientStoreEventRequest
    {
        public string Id { get; set; }

        public string Scope { get; set; }

        [JsonPropertyName("event")]
        public AttestedEventRequest EventName { get; set; }


    }
}
