// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    public partial class OAuthGetTokenWithAttestationRequest
    {
        public string Sub { get; set; }

        public string TenantId { get; set; }

        public string Aud { get; set; }

        public string Iss { get; set; }


    }
}
