// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    public partial class ProposalsVoteOnProposalRequest
    {
        public string ProposalId { get; set; }

        public CustomBallot Vote { get; set; }


    }
}
