# DO NOT EDIT. AUTO-GENERATED CODE.
# Please run tools/generate_models.ps1 to re-generate the file after editing openapi/spark.yaml.


# generated by datamodel-codegen:
#   filename:  spark.yaml

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Union

from pydantic import BaseModel, Field


class SparkApplicationType(Enum):
    Spark_SQL = "Spark-SQL"
    Spark_ML = "Spark-ML"


class SparkApplicationDatasetDescriptor(BaseModel):
    specification: str = Field(
        ...,
        description="ID of document capturing the dataset specification.\n\n[Specification](cleanroom_sparkdataset.yaml#//components/schemas/DatasetSpecification)\n",
        title="Specification of the dataset to be presented to the Spark application.",
    )
    view: str = Field(
        ...,
        title="Name of the view to be generated by the Spark application for accessing the dataset.",
    )


class SparkApplicationBase(BaseModel):
    applicationType: SparkApplicationType
    inputDataset: List[SparkApplicationDatasetDescriptor] = Field(
        ..., title="Dataset(s) to be presented to the Spark application for reading."
    )
    outputDataset: SparkApplicationDatasetDescriptor = Field(
        ..., title="Dataset to be presented to the Spark application for writing."
    )


class SparkSQLApplication(SparkApplicationBase):
    query: str
    applicationType: Literal["Spark-SQL"]


class SparkMLApplication(SparkApplicationBase):
    payload: str
    applicationType: Literal["Spark-ML"]


class SparkApplicationSpecification(BaseModel):
    name: str
    application: Union[SparkSQLApplication, SparkMLApplication] = Field(
        ..., discriminator="applicationType"
    )
