// Generated by Microsoft TypeSpec

import { HttpContext } from "../../helpers/router.js";

import {
  isHttpResponder as __isHttpResponder_0,
  HTTP_RESPONDER as __httpResponderSymbol_1,
} from "../../helpers/http.js";

import {
  Contracts,
  ListContractsResponse,
  PutContractRequest,
  GetContractResponse,
  ContractRuntimeOptions,
  Events,
  GetEventsResponse,
  PutEventRequest,
  Secrets,
  ListSecretsResponse,
  PutSecretByMemberUserRequest,
  PutSecretByCleanRoomRequest,
  PutSecretResponse,
  GetSecretRequest,
  GetSecretResponse,
  CleanRoomPolicy,
  Deployment,
  OAuth,
  CertificateAuthority,
  GenerateEndorsedCertRequest,
  CaInfo,
  MemberDocuments,
  PutMemberDocumentRequest,
  GetMemberDocumentResponse,
  AcceptedMemberDocuments,
  GetAcceptedMemberDocumentRequest,
  GetAcceptedMemberDocumentResponse,
  UserIdentities,
  ContractUsers,
  UserInvitations,
  UserDocuments,
  ListUserDocumentsResponse,
  PutUserDocumentRequest,
  GetUserDocumentResponse,
  AcceptedUserDocuments,
  GetAcceptedUserDocumentRequest,
  GetAcceptedUserDocumentResponse,
  UserDocumentRuntimeOptionsConsent,
  UserDocumentRuntimeOptions,
  Proposals,
  UserProposals,
  GetUserProposalResponse,
  CreateUserProposalRequest,
  CreateUserProposalResponse,
  SubmitUserProposalBallotRequest,
  Oidc,
  RuntimeOptions,
} from "../../models/all/cleanroom/governance.js";

import { parseHeaderValueParameters } from "../../helpers/header.js";

import {
  CheckExecutionStatusResult,
  CheckLoggingStatusResult,
  CheckTelemetryStatusResult,
  ConsentCheckExecutionResult,
  ConsentCheckLoggingResult,
  ConsentCheckTelemetryResult,
  GetResult,
  ListDelegatesResult,
  GetDelegateResult,
  GetSpecResult,
  GetInfoResult,
  GetTokenResult,
  GenerateEndorsedCertResult,
  ListResult,
  IsActiveResult,
  ConsentCheckResult,
  CheckStatusResult,
  GetHistoricalResult,
  GetStatusResult,
  GetConfigurationResult,
  GetJwksResult,
  SetIssuerUrlRequestBody,
  GetIssuerInfoResult,
} from "../../models/synthetic.js";

export async function contracts_list(
  __ctx_2: HttpContext,
  __operations_4: Contracts,
): Promise<void> {
  let __result_3: ListContractsResponse;

  try {
    __result_3 = await __operations_4.list(__ctx_2);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_2);
    } else throw e;
  }

  __ctx_2.response.setHeader("content-type", "application/json");
  __ctx_2.response.end(globalThis.JSON.stringify(__result_3));
}

export async function contracts_put(
  __ctx_6: HttpContext,
  __operations_8: Contracts,
  contractId: string,
): Promise<void> {
  const __contentType_11 = parseHeaderValueParameters(
    __ctx_6.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_11?.value !== "application/json") {
    return __ctx_6.errorHandlers.onInvalidRequest(
      __ctx_6,
      "/contracts/{contractId}",
      `unexpected "content-type": '${__contentType_11?.value}', expected '"application/json"'`,
    );
  }

  const __contract_10 = (await new Promise(function parseContract(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_6.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_6.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_6.errorHandlers.onInvalidRequest(
          __ctx_6,
          "/contracts/{contractId}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_6.request.on("error", reject);
  })) as PutContractRequest;

  let __result_7: void;

  try {
    __result_7 = await __operations_8.put(__ctx_6, contractId, __contract_10);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_6);
    } else throw e;
  }

  __ctx_6.response.statusCode = 204;
  __ctx_6.response.end();
}

export async function contracts_get(
  __ctx_12: HttpContext,
  __operations_14: Contracts,
  contractId: string,
): Promise<void> {
  let __result_13: GetContractResponse;

  try {
    __result_13 = await __operations_14.get(__ctx_12, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_12);
    } else throw e;
  }

  __ctx_12.response.setHeader("content-type", "application/json");
  __ctx_12.response.end(globalThis.JSON.stringify(__result_13));
}

export async function contract_runtime_options_check_execution_status(
  __ctx_16: HttpContext,
  __operations_18: ContractRuntimeOptions,
  contractId: string,
): Promise<void> {
  let __result_17: CheckExecutionStatusResult;

  try {
    __result_17 = await __operations_18.checkExecutionStatus(
      __ctx_16,
      contractId,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_16);
    } else throw e;
  }

  __ctx_16.response.setHeader("content-type", "application/json");
  __ctx_16.response.end(globalThis.JSON.stringify(__result_17));
}

export async function contract_runtime_options_check_logging_status(
  __ctx_20: HttpContext,
  __operations_22: ContractRuntimeOptions,
  contractId: string,
): Promise<void> {
  let __result_21: CheckLoggingStatusResult;

  try {
    __result_21 = await __operations_22.checkLoggingStatus(
      __ctx_20,
      contractId,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_20);
    } else throw e;
  }

  __ctx_20.response.setHeader("content-type", "application/json");
  __ctx_20.response.end(globalThis.JSON.stringify(__result_21));
}

export async function contract_runtime_options_check_telemetry_status(
  __ctx_24: HttpContext,
  __operations_26: ContractRuntimeOptions,
  contractId: string,
): Promise<void> {
  let __result_25: CheckTelemetryStatusResult;

  try {
    __result_25 = await __operations_26.checkTelemetryStatus(
      __ctx_24,
      contractId,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_24);
    } else throw e;
  }

  __ctx_24.response.setHeader("content-type", "application/json");
  __ctx_24.response.end(globalThis.JSON.stringify(__result_25));
}

export async function contract_runtime_options_consent_check_execution(
  __ctx_28: HttpContext,
  __operations_30: ContractRuntimeOptions,
  contractId: string,
): Promise<void> {
  let __result_29: ConsentCheckExecutionResult;

  try {
    __result_29 = await __operations_30.consentCheckExecution(
      __ctx_28,
      contractId,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_28);
    } else throw e;
  }

  __ctx_28.response.setHeader("content-type", "application/json");
  __ctx_28.response.end(globalThis.JSON.stringify(__result_29));
}

export async function contract_runtime_options_consent_check_logging(
  __ctx_32: HttpContext,
  __operations_34: ContractRuntimeOptions,
  contractId: string,
): Promise<void> {
  let __result_33: ConsentCheckLoggingResult;

  try {
    __result_33 = await __operations_34.consentCheckLogging(
      __ctx_32,
      contractId,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_32);
    } else throw e;
  }

  __ctx_32.response.setHeader("content-type", "application/json");
  __ctx_32.response.end(globalThis.JSON.stringify(__result_33));
}

export async function contract_runtime_options_consent_check_telemetry(
  __ctx_36: HttpContext,
  __operations_38: ContractRuntimeOptions,
  contractId: string,
): Promise<void> {
  let __result_37: ConsentCheckTelemetryResult;

  try {
    __result_37 = await __operations_38.consentCheckTelemetry(
      __ctx_36,
      contractId,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_36);
    } else throw e;
  }

  __ctx_36.response.setHeader("content-type", "application/json");
  __ctx_36.response.end(globalThis.JSON.stringify(__result_37));
}

export async function contract_runtime_options_enable(
  __ctx_40: HttpContext,
  __operations_42: ContractRuntimeOptions,
  contractId: string,
): Promise<void> {
  let __result_41: void;

  try {
    __result_41 = await __operations_42.enable(__ctx_40, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_40);
    } else throw e;
  }

  __ctx_40.response.statusCode = 204;
  __ctx_40.response.end();
}

export async function contract_runtime_options_disable(
  __ctx_44: HttpContext,
  __operations_46: ContractRuntimeOptions,
  contractId: string,
): Promise<void> {
  let __result_45: void;

  try {
    __result_45 = await __operations_46.disable(__ctx_44, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_44);
    } else throw e;
  }

  __ctx_44.response.statusCode = 204;
  __ctx_44.response.end();
}

export async function events_get(
  __ctx_48: HttpContext,
  __operations_50: Events,
  contractId: string,
): Promise<void> {
  const __queryParams_51 = new URLSearchParams(
    __ctx_48.request.url!.split("?", 2)[1] ?? "",
  );

  const nextLink = __queryParams_51.get("nextLink") ?? undefined;
  let __result_49: GetEventsResponse;

  try {
    __result_49 = await __operations_50.get(__ctx_48, contractId, {
      nextLink: nextLink,
    });
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_48);
    } else throw e;
  }

  __ctx_48.response.setHeader("content-type", "application/json");
  __ctx_48.response.end(
    globalThis.JSON.stringify(
      GetEventsResponse.toJsonObject(__result_49 as GetEventsResponse),
    ),
  );
}

export async function events_put(
  __ctx_52: HttpContext,
  __operations_54: Events,
  contractId: string,
): Promise<void> {
  const __contentType_57 = parseHeaderValueParameters(
    __ctx_52.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_57?.value !== "application/json") {
    return __ctx_52.errorHandlers.onInvalidRequest(
      __ctx_52,
      "/contracts/{contractId}/events",
      `unexpected "content-type": '${__contentType_57?.value}', expected '"application/json"'`,
    );
  }

  const __event_56 = (await new Promise(function parseEvent(resolve, reject) {
    const chunks: Array<Buffer> = [];
    __ctx_52.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_52.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(PutEventRequest.fromJsonObject(globalThis.JSON.parse(body)));
      } catch {
        __ctx_52.errorHandlers.onInvalidRequest(
          __ctx_52,
          "/contracts/{contractId}/events",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_52.request.on("error", reject);
  })) as PutEventRequest;

  let __result_53: void;

  try {
    __result_53 = await __operations_54.put(__ctx_52, contractId, __event_56);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_52);
    } else throw e;
  }

  __ctx_52.response.statusCode = 204;
  __ctx_52.response.end();
}

export async function secrets_list(
  __ctx_58: HttpContext,
  __operations_60: Secrets,
  contractId: string,
): Promise<void> {
  let __result_59: ListSecretsResponse;

  try {
    __result_59 = await __operations_60.list(__ctx_58, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_58);
    } else throw e;
  }

  __ctx_58.response.setHeader("content-type", "application/json");
  __ctx_58.response.end(globalThis.JSON.stringify(__result_59));
}

export async function secrets_put(
  __ctx_62: HttpContext,
  __operations_64: Secrets,
  contractId: string,
  secretName: string,
): Promise<void> {
  const __contentType_67 = parseHeaderValueParameters(
    __ctx_62.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_67?.value !== "application/json") {
    return __ctx_62.errorHandlers.onInvalidRequest(
      __ctx_62,
      "/contracts/{contractId}/secrets/{secretName}",
      `unexpected "content-type": '${__contentType_67?.value}', expected '"application/json"'`,
    );
  }

  const __request_66 = (await new Promise(function parseRequest(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_62.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_62.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_62.errorHandlers.onInvalidRequest(
          __ctx_62,
          "/contracts/{contractId}/secrets/{secretName}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_62.request.on("error", reject);
  })) as PutSecretByMemberUserRequest | PutSecretByCleanRoomRequest;

  let __result_63: PutSecretResponse;

  try {
    __result_63 = await __operations_64.put(
      __ctx_62,
      contractId,
      secretName,
      __request_66,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_62);
    } else throw e;
  }

  __ctx_62.response.setHeader("content-type", "application/json");
  __ctx_62.response.end(globalThis.JSON.stringify(__result_63));
}

export async function secrets_get(
  __ctx_68: HttpContext,
  __operations_70: Secrets,
  contractId: string,
  secretName: string,
): Promise<void> {
  const __contentType_73 = parseHeaderValueParameters(
    __ctx_68.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_73?.value !== "application/json") {
    return __ctx_68.errorHandlers.onInvalidRequest(
      __ctx_68,
      "/contracts/{contractId}/secrets/{secretName}",
      `unexpected "content-type": '${__contentType_73?.value}', expected '"application/json"'`,
    );
  }

  const __request_72 = (await new Promise(function parseRequest(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_68.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_68.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(GetSecretRequest.fromJsonObject(globalThis.JSON.parse(body)));
      } catch {
        __ctx_68.errorHandlers.onInvalidRequest(
          __ctx_68,
          "/contracts/{contractId}/secrets/{secretName}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_68.request.on("error", reject);
  })) as GetSecretRequest;

  let __result_69: GetSecretResponse;

  try {
    __result_69 = await __operations_70.get(
      __ctx_68,
      contractId,
      secretName,
      __request_72,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_68);
    } else throw e;
  }

  __ctx_68.response.setHeader("content-type", "application/json");
  __ctx_68.response.end(globalThis.JSON.stringify(__result_69));
}

export async function clean_room_policy_get(
  __ctx_74: HttpContext,
  __operations_76: CleanRoomPolicy,
  contractId: string,
): Promise<void> {
  let __result_75: GetResult;

  try {
    __result_75 = await __operations_76.get(__ctx_74, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_74);
    } else throw e;
  }

  __ctx_74.response.setHeader("content-type", "application/json");
  __ctx_74.response.end(globalThis.JSON.stringify(__result_75));
}

export async function clean_room_policy_list_delegates(
  __ctx_78: HttpContext,
  __operations_80: CleanRoomPolicy,
  contractId: string,
): Promise<void> {
  let __result_79: ListDelegatesResult;

  try {
    __result_79 = await __operations_80.listDelegates(__ctx_78, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_78);
    } else throw e;
  }

  __ctx_78.response.setHeader("content-type", "application/json");
  __ctx_78.response.end(globalThis.JSON.stringify(__result_79));
}

export async function clean_room_policy_get_delegate(
  __ctx_82: HttpContext,
  __operations_84: CleanRoomPolicy,
  contractId: string,
  delegateType: string,
  delegateId: string,
): Promise<void> {
  let __result_83: GetDelegateResult;

  try {
    __result_83 = await __operations_84.getDelegate(
      __ctx_82,
      contractId,
      delegateType,
      delegateId,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_82);
    } else throw e;
  }

  __ctx_82.response.setHeader("content-type", "application/json");
  __ctx_82.response.end(globalThis.JSON.stringify(__result_83));
}

export async function clean_room_policy_set_delegate(
  __ctx_86: HttpContext,
  __operations_88: CleanRoomPolicy,
  contractId: string,
  delegateType: string,
  delegateId: string,
): Promise<void> {
  const __contentType_91 = parseHeaderValueParameters(
    __ctx_86.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_91?.value !== "application/json") {
    return __ctx_86.errorHandlers.onInvalidRequest(
      __ctx_86,
      "/contracts/{contractId}/cleanroompolicy/delegates/{delegateType}/{delegateId}",
      `unexpected "content-type": '${__contentType_91?.value}', expected '"application/json"'`,
    );
  }

  const __policy_90 = (await new Promise(function parsePolicy(resolve, reject) {
    const chunks: Array<Buffer> = [];
    __ctx_86.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_86.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_86.errorHandlers.onInvalidRequest(
          __ctx_86,
          "/contracts/{contractId}/cleanroompolicy/delegates/{delegateType}/{delegateId}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_86.request.on("error", reject);
  })) as unknown;

  let __result_87: void;

  try {
    __result_87 = await __operations_88.setDelegate(
      __ctx_86,
      contractId,
      delegateType,
      delegateId,
      __policy_90,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_86);
    } else throw e;
  }

  __ctx_86.response.statusCode = 204;
  __ctx_86.response.end();
}

export async function deployment_get_spec(
  __ctx_92: HttpContext,
  __operations_94: Deployment,
  contractId: string,
): Promise<void> {
  let __result_93: GetSpecResult;

  try {
    __result_93 = await __operations_94.getSpec(__ctx_92, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_92);
    } else throw e;
  }

  __ctx_92.response.setHeader("content-type", "application/json");
  __ctx_92.response.end(globalThis.JSON.stringify(__result_93));
}

export async function deployment_get_info(
  __ctx_96: HttpContext,
  __operations_98: Deployment,
  contractId: string,
): Promise<void> {
  let __result_97: GetInfoResult;

  try {
    __result_97 = await __operations_98.getInfo(__ctx_96, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_96);
    } else throw e;
  }

  __ctx_96.response.setHeader("content-type", "application/json");
  __ctx_96.response.end(globalThis.JSON.stringify(__result_97));
}

export async function o_auth_get_token(
  __ctx_100: HttpContext,
  __operations_102: OAuth,
  contractId: string,
): Promise<void> {
  const __contentType_105 = parseHeaderValueParameters(
    __ctx_100.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_105?.value !== "application/json") {
    return __ctx_100.errorHandlers.onInvalidRequest(
      __ctx_100,
      "/contracts/{contractId}/oauth/token",
      `unexpected "content-type": '${__contentType_105?.value}', expected '"application/json"'`,
    );
  }

  const __request_104 = (await new Promise(function parseRequest(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_100.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_100.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_100.errorHandlers.onInvalidRequest(
          __ctx_100,
          "/contracts/{contractId}/oauth/token",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_100.request.on("error", reject);
  })) as unknown;

  let __result_101: GetTokenResult;

  try {
    __result_101 = await __operations_102.getToken(
      __ctx_100,
      contractId,
      __request_104,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_100);
    } else throw e;
  }

  __ctx_100.response.setHeader("content-type", "application/json");
  __ctx_100.response.end(globalThis.JSON.stringify(__result_101));
}

export async function certificate_authority_generate_signing_key(
  __ctx_106: HttpContext,
  __operations_108: CertificateAuthority,
  contractId: string,
): Promise<void> {
  let __result_107: void;

  try {
    __result_107 = await __operations_108.generateSigningKey(
      __ctx_106,
      contractId,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_106);
    } else throw e;
  }

  __ctx_106.response.statusCode = 204;
  __ctx_106.response.end();
}

export async function certificate_authority_generate_endorsed_cert(
  __ctx_110: HttpContext,
  __operations_112: CertificateAuthority,
  contractId: string,
): Promise<void> {
  const __contentType_115 = parseHeaderValueParameters(
    __ctx_110.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_115?.value !== "application/json") {
    return __ctx_110.errorHandlers.onInvalidRequest(
      __ctx_110,
      "/contracts/{contractId}/ca/generateEndorsedCert",
      `unexpected "content-type": '${__contentType_115?.value}', expected '"application/json"'`,
    );
  }

  const __request_114 = (await new Promise(function parseRequest(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_110.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_110.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(
          GenerateEndorsedCertRequest.fromJsonObject(
            globalThis.JSON.parse(body),
          ),
        );
      } catch {
        __ctx_110.errorHandlers.onInvalidRequest(
          __ctx_110,
          "/contracts/{contractId}/ca/generateEndorsedCert",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_110.request.on("error", reject);
  })) as GenerateEndorsedCertRequest;

  let __result_111: GenerateEndorsedCertResult;

  try {
    __result_111 = await __operations_112.generateEndorsedCert(
      __ctx_110,
      contractId,
      __request_114,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_110);
    } else throw e;
  }

  __ctx_110.response.setHeader("content-type", "application/json");
  __ctx_110.response.end(globalThis.JSON.stringify(__result_111));
}

export async function certificate_authority_get_info(
  __ctx_116: HttpContext,
  __operations_118: CertificateAuthority,
  contractId: string,
): Promise<void> {
  let __result_117: CaInfo;

  try {
    __result_117 = await __operations_118.getInfo(__ctx_116, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_116);
    } else throw e;
  }

  __ctx_116.response.setHeader("content-type", "application/json");
  __ctx_116.response.end(globalThis.JSON.stringify(__result_117));
}

export async function member_documents_list(
  __ctx_120: HttpContext,
  __operations_122: MemberDocuments,
): Promise<void> {
  let __result_121: ListResult;

  try {
    __result_121 = await __operations_122.list(__ctx_120);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_120);
    } else throw e;
  }

  __ctx_120.response.setHeader("content-type", "application/json");
  __ctx_120.response.end(globalThis.JSON.stringify(__result_121));
}

export async function member_documents_put(
  __ctx_124: HttpContext,
  __operations_126: MemberDocuments,
  documentId: string,
): Promise<void> {
  const __contentType_129 = parseHeaderValueParameters(
    __ctx_124.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_129?.value !== "application/json") {
    return __ctx_124.errorHandlers.onInvalidRequest(
      __ctx_124,
      "/memberdocuments/{documentId}",
      `unexpected "content-type": '${__contentType_129?.value}', expected '"application/json"'`,
    );
  }

  const __document_128 = (await new Promise(function parseDocument(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_124.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_124.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_124.errorHandlers.onInvalidRequest(
          __ctx_124,
          "/memberdocuments/{documentId}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_124.request.on("error", reject);
  })) as PutMemberDocumentRequest;

  let __result_125: void;

  try {
    __result_125 = await __operations_126.put(
      __ctx_124,
      documentId,
      __document_128,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_124);
    } else throw e;
  }

  __ctx_124.response.statusCode = 204;
  __ctx_124.response.end();
}

export async function member_documents_get(
  __ctx_130: HttpContext,
  __operations_132: MemberDocuments,
  documentId: string,
): Promise<void> {
  let __result_131: GetMemberDocumentResponse;

  try {
    __result_131 = await __operations_132.get(__ctx_130, documentId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_130);
    } else throw e;
  }

  __ctx_130.response.setHeader("content-type", "application/json");
  __ctx_130.response.end(globalThis.JSON.stringify(__result_131));
}

export async function accepted_member_documents_get(
  __ctx_134: HttpContext,
  __operations_136: AcceptedMemberDocuments,
  contractId: string,
  documentId: string,
): Promise<void> {
  const __contentType_139 = parseHeaderValueParameters(
    __ctx_134.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_139?.value !== "application/json") {
    return __ctx_134.errorHandlers.onInvalidRequest(
      __ctx_134,
      "/contracts/{contractId}/acceptedMemberDocuments/{documentId}",
      `unexpected "content-type": '${__contentType_139?.value}', expected '"application/json"'`,
    );
  }

  const __request_138 = (await new Promise(function parseRequest(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_134.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_134.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(
          GetAcceptedMemberDocumentRequest.fromJsonObject(
            globalThis.JSON.parse(body),
          ),
        );
      } catch {
        __ctx_134.errorHandlers.onInvalidRequest(
          __ctx_134,
          "/contracts/{contractId}/acceptedMemberDocuments/{documentId}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_134.request.on("error", reject);
  })) as GetAcceptedMemberDocumentRequest;

  let __result_135: GetAcceptedMemberDocumentResponse;

  try {
    __result_135 = await __operations_136.get(
      __ctx_134,
      contractId,
      documentId,
      __request_138,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_134);
    } else throw e;
  }

  __ctx_134.response.setHeader("content-type", "application/json");
  __ctx_134.response.end(globalThis.JSON.stringify(__result_135));
}

export async function user_identities_list(
  __ctx_140: HttpContext,
  __operations_142: UserIdentities,
): Promise<void> {
  let __result_141: ListResult;

  try {
    __result_141 = await __operations_142.list(__ctx_140);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_140);
    } else throw e;
  }

  __ctx_140.response.setHeader("content-type", "application/json");
  __ctx_140.response.end(globalThis.JSON.stringify(__result_141));
}

export async function user_identities_get(
  __ctx_144: HttpContext,
  __operations_146: UserIdentities,
  identityId: string,
): Promise<void> {
  let __result_145: GetResult;

  try {
    __result_145 = await __operations_146.get(__ctx_144, identityId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_144);
    } else throw e;
  }

  __ctx_144.response.setHeader("content-type", "application/json");
  __ctx_144.response.end(globalThis.JSON.stringify(__result_145));
}

export async function contract_users_is_active(
  __ctx_148: HttpContext,
  __operations_150: ContractUsers,
  contractId: string,
): Promise<void> {
  let __result_149: IsActiveResult;

  try {
    __result_149 = await __operations_150.isActive(__ctx_148, contractId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_148);
    } else throw e;
  }

  __ctx_148.response.setHeader("content-type", "application/json");
  __ctx_148.response.end(globalThis.JSON.stringify(__result_149));
}

export async function user_invitations_list(
  __ctx_152: HttpContext,
  __operations_154: UserInvitations,
): Promise<void> {
  let __result_153: ListResult;

  try {
    __result_153 = await __operations_154.list(__ctx_152);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_152);
    } else throw e;
  }

  __ctx_152.response.setHeader("content-type", "application/json");
  __ctx_152.response.end(globalThis.JSON.stringify(__result_153));
}

export async function user_invitations_get(
  __ctx_156: HttpContext,
  __operations_158: UserInvitations,
  invitationId: string,
): Promise<void> {
  let __result_157: GetResult;

  try {
    __result_157 = await __operations_158.get(__ctx_156, invitationId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_156);
    } else throw e;
  }

  __ctx_156.response.setHeader("content-type", "application/json");
  __ctx_156.response.end(globalThis.JSON.stringify(__result_157));
}

export async function user_invitations_accept(
  __ctx_160: HttpContext,
  __operations_162: UserInvitations,
  invitationId: string,
): Promise<void> {
  let __result_161: void;

  try {
    __result_161 = await __operations_162.accept(__ctx_160, invitationId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_160);
    } else throw e;
  }

  __ctx_160.response.statusCode = 204;
  __ctx_160.response.end();
}

export async function user_documents_list(
  __ctx_164: HttpContext,
  __operations_166: UserDocuments,
): Promise<void> {
  const __queryParams_167 = new URLSearchParams(
    __ctx_164.request.url!.split("?", 2)[1] ?? "",
  );

  const labels = __queryParams_167.get("labels") ?? undefined;
  let __result_165: ListUserDocumentsResponse;

  try {
    __result_165 = await __operations_166.list(__ctx_164, { labels });
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_164);
    } else throw e;
  }

  __ctx_164.response.setHeader("content-type", "application/json");
  __ctx_164.response.end(globalThis.JSON.stringify(__result_165));
}

export async function user_documents_put(
  __ctx_168: HttpContext,
  __operations_170: UserDocuments,
  documentId: string,
): Promise<void> {
  const __contentType_173 = parseHeaderValueParameters(
    __ctx_168.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_173?.value !== "application/json") {
    return __ctx_168.errorHandlers.onInvalidRequest(
      __ctx_168,
      "/userdocuments/{documentId}",
      `unexpected "content-type": '${__contentType_173?.value}', expected '"application/json"'`,
    );
  }

  const __document_172 = (await new Promise(function parseDocument(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_168.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_168.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_168.errorHandlers.onInvalidRequest(
          __ctx_168,
          "/userdocuments/{documentId}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_168.request.on("error", reject);
  })) as PutUserDocumentRequest;

  let __result_169: void;

  try {
    __result_169 = await __operations_170.put(
      __ctx_168,
      documentId,
      __document_172,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_168);
    } else throw e;
  }

  __ctx_168.response.statusCode = 204;
  __ctx_168.response.end();
}

export async function user_documents_get(
  __ctx_174: HttpContext,
  __operations_176: UserDocuments,
  documentId: string,
): Promise<void> {
  let __result_175: GetUserDocumentResponse;

  try {
    __result_175 = await __operations_176.get(__ctx_174, documentId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_174);
    } else throw e;
  }

  __ctx_174.response.setHeader("content-type", "application/json");
  __ctx_174.response.end(globalThis.JSON.stringify(__result_175));
}

export async function accepted_user_documents_get(
  __ctx_178: HttpContext,
  __operations_180: AcceptedUserDocuments,
  contractId: string,
  documentId: string,
): Promise<void> {
  const __contentType_183 = parseHeaderValueParameters(
    __ctx_178.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_183?.value !== "application/json") {
    return __ctx_178.errorHandlers.onInvalidRequest(
      __ctx_178,
      "/contracts/{contractId}/acceptedUserDocuments/{documentId}",
      `unexpected "content-type": '${__contentType_183?.value}', expected '"application/json"'`,
    );
  }

  const __request_182 = (await new Promise(function parseRequest(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_178.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_178.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(
          GetAcceptedUserDocumentRequest.fromJsonObject(
            globalThis.JSON.parse(body),
          ),
        );
      } catch {
        __ctx_178.errorHandlers.onInvalidRequest(
          __ctx_178,
          "/contracts/{contractId}/acceptedUserDocuments/{documentId}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_178.request.on("error", reject);
  })) as GetAcceptedUserDocumentRequest;

  let __result_179: GetAcceptedUserDocumentResponse;

  try {
    __result_179 = await __operations_180.get(
      __ctx_178,
      contractId,
      documentId,
      __request_182,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_178);
    } else throw e;
  }

  __ctx_178.response.setHeader("content-type", "application/json");
  __ctx_178.response.end(globalThis.JSON.stringify(__result_179));
}

export async function user_document_runtime_options_consent_consent_check(
  __ctx_184: HttpContext,
  __operations_186: UserDocumentRuntimeOptionsConsent,
  contractId: string,
  documentId: string,
  option: string,
): Promise<void> {
  let __result_185: ConsentCheckResult;

  try {
    __result_185 = await __operations_186.consentCheck(
      __ctx_184,
      contractId,
      documentId,
      option,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_184);
    } else throw e;
  }

  __ctx_184.response.setHeader("content-type", "application/json");
  __ctx_184.response.end(globalThis.JSON.stringify(__result_185));
}

export async function user_document_runtime_options_check_status(
  __ctx_188: HttpContext,
  __operations_190: UserDocumentRuntimeOptions,
  documentId: string,
  option: string,
): Promise<void> {
  let __result_189: CheckStatusResult;

  try {
    __result_189 = await __operations_190.checkStatus(
      __ctx_188,
      documentId,
      option,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_188);
    } else throw e;
  }

  __ctx_188.response.setHeader("content-type", "application/json");
  __ctx_188.response.end(globalThis.JSON.stringify(__result_189));
}

export async function user_document_runtime_options_enable(
  __ctx_192: HttpContext,
  __operations_194: UserDocumentRuntimeOptions,
  documentId: string,
  option: string,
): Promise<void> {
  let __result_193: void;

  try {
    __result_193 = await __operations_194.enable(__ctx_192, documentId, option);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_192);
    } else throw e;
  }

  __ctx_192.response.statusCode = 204;
  __ctx_192.response.end();
}

export async function user_document_runtime_options_disable(
  __ctx_196: HttpContext,
  __operations_198: UserDocumentRuntimeOptions,
  documentId: string,
  option: string,
): Promise<void> {
  let __result_197: void;

  try {
    __result_197 = await __operations_198.disable(
      __ctx_196,
      documentId,
      option,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_196);
    } else throw e;
  }

  __ctx_196.response.statusCode = 204;
  __ctx_196.response.end();
}

export async function proposals_get_historical(
  __ctx_200: HttpContext,
  __operations_202: Proposals,
  proposalId: string,
): Promise<void> {
  let __result_201: GetHistoricalResult;

  try {
    __result_201 = await __operations_202.getHistorical(__ctx_200, proposalId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_200);
    } else throw e;
  }

  __ctx_200.response.setHeader("content-type", "application/json");
  __ctx_200.response.end(globalThis.JSON.stringify(__result_201));
}

export async function user_proposals_get(
  __ctx_204: HttpContext,
  __operations_206: UserProposals,
  proposalId: string,
): Promise<void> {
  let __result_205: GetUserProposalResponse;

  try {
    __result_205 = await __operations_206.get(__ctx_204, proposalId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_204);
    } else throw e;
  }

  __ctx_204.response.setHeader("content-type", "application/json");
  __ctx_204.response.end(globalThis.JSON.stringify(__result_205));
}

export async function user_proposals_put(
  __ctx_208: HttpContext,
  __operations_210: UserProposals,
  proposalId: string,
): Promise<void> {
  const __contentType_213 = parseHeaderValueParameters(
    __ctx_208.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_213?.value !== "application/json") {
    return __ctx_208.errorHandlers.onInvalidRequest(
      __ctx_208,
      "/users/proposals/{proposalId}",
      `unexpected "content-type": '${__contentType_213?.value}', expected '"application/json"'`,
    );
  }

  const __proposal_212 = (await new Promise(function parseProposal(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_208.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_208.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_208.errorHandlers.onInvalidRequest(
          __ctx_208,
          "/users/proposals/{proposalId}",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_208.request.on("error", reject);
  })) as CreateUserProposalRequest;

  let __result_209: CreateUserProposalResponse;

  try {
    __result_209 = await __operations_210.put(
      __ctx_208,
      proposalId,
      __proposal_212,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_208);
    } else throw e;
  }

  __ctx_208.response.setHeader("content-type", "application/json");
  __ctx_208.response.end(globalThis.JSON.stringify(__result_209));
}

export async function user_proposals_get_status(
  __ctx_214: HttpContext,
  __operations_216: UserProposals,
  proposalId: string,
): Promise<void> {
  let __result_215: GetStatusResult;

  try {
    __result_215 = await __operations_216.getStatus(__ctx_214, proposalId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_214);
    } else throw e;
  }

  __ctx_214.response.setHeader("content-type", "application/json");
  __ctx_214.response.end(globalThis.JSON.stringify(__result_215));
}

export async function user_proposals_withdraw(
  __ctx_218: HttpContext,
  __operations_220: UserProposals,
  proposalId: string,
): Promise<void> {
  let __result_219: void;

  try {
    __result_219 = await __operations_220.withdraw(__ctx_218, proposalId);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_218);
    } else throw e;
  }

  __ctx_218.response.statusCode = 204;
  __ctx_218.response.end();
}

export async function user_proposals_submit_ballot(
  __ctx_222: HttpContext,
  __operations_224: UserProposals,
  proposalId: string,
): Promise<void> {
  const __contentType_227 = parseHeaderValueParameters(
    __ctx_222.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_227?.value !== "application/json") {
    return __ctx_222.errorHandlers.onInvalidRequest(
      __ctx_222,
      "/users/proposals/{proposalId}/ballots/submit",
      `unexpected "content-type": '${__contentType_227?.value}', expected '"application/json"'`,
    );
  }

  const __ballot_226 = (await new Promise(function parseBallot(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_222.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_222.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_222.errorHandlers.onInvalidRequest(
          __ctx_222,
          "/users/proposals/{proposalId}/ballots/submit",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_222.request.on("error", reject);
  })) as SubmitUserProposalBallotRequest;

  let __result_223: void;

  try {
    __result_223 = await __operations_224.submitBallot(
      __ctx_222,
      proposalId,
      __ballot_226,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_222);
    } else throw e;
  }

  __ctx_222.response.statusCode = 204;
  __ctx_222.response.end();
}

export async function oidc_get_configuration(
  __ctx_228: HttpContext,
  __operations_230: Oidc,
): Promise<void> {
  let __result_229: GetConfigurationResult;

  try {
    __result_229 = await __operations_230.getConfiguration(__ctx_228);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_228);
    } else throw e;
  }

  __ctx_228.response.setHeader("content-type", "application/json");
  __ctx_228.response.end(globalThis.JSON.stringify(__result_229));
}

export async function oidc_get_jwks(
  __ctx_232: HttpContext,
  __operations_234: Oidc,
): Promise<void> {
  let __result_233: GetJwksResult;

  try {
    __result_233 = await __operations_234.getJwks(__ctx_232);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_232);
    } else throw e;
  }

  __ctx_232.response.setHeader("content-type", "application/json");
  __ctx_232.response.end(globalThis.JSON.stringify(__result_233));
}

export async function oidc_generate_signing_key(
  __ctx_236: HttpContext,
  __operations_238: Oidc,
): Promise<void> {
  let __result_237: void;

  try {
    __result_237 = await __operations_238.generateSigningKey(__ctx_236);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_236);
    } else throw e;
  }

  __ctx_236.response.statusCode = 204;
  __ctx_236.response.end();
}

export async function oidc_set_issuer_url(
  __ctx_240: HttpContext,
  __operations_242: Oidc,
): Promise<void> {
  const __contentType_245 = parseHeaderValueParameters(
    __ctx_240.request.headers["content-type"] as string | undefined,
  );
  if (__contentType_245?.value !== "application/json") {
    return __ctx_240.errorHandlers.onInvalidRequest(
      __ctx_240,
      "/oidc/setIssuerUrl",
      `unexpected "content-type": '${__contentType_245?.value}', expected '"application/json"'`,
    );
  }

  const __request_244 = (await new Promise(function parseRequest(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    __ctx_240.request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    __ctx_240.request.on("end", function finalize() {
      try {
        const body = Buffer.concat(chunks).toString();
        resolve(JSON.parse(body));
      } catch {
        __ctx_240.errorHandlers.onInvalidRequest(
          __ctx_240,
          "/oidc/setIssuerUrl",
          "invalid JSON in request body",
        );
        reject();
      }
    });
    __ctx_240.request.on("error", reject);
  })) as SetIssuerUrlRequestBody;

  let __result_241: void;

  try {
    __result_241 = await __operations_242.setIssuerUrl(
      __ctx_240,
      __request_244,
    );
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_240);
    } else throw e;
  }

  __ctx_240.response.statusCode = 204;
  __ctx_240.response.end();
}

export async function oidc_get_issuer_info(
  __ctx_246: HttpContext,
  __operations_248: Oidc,
): Promise<void> {
  let __result_247: GetIssuerInfoResult;

  try {
    __result_247 = await __operations_248.getIssuerInfo(__ctx_246);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_246);
    } else throw e;
  }

  __ctx_246.response.setHeader("content-type", "application/json");
  __ctx_246.response.end(globalThis.JSON.stringify(__result_247));
}

export async function runtime_options_check_status(
  __ctx_250: HttpContext,
  __operations_252: RuntimeOptions,
  option: string,
): Promise<void> {
  let __result_251: CheckStatusResult;

  try {
    __result_251 = await __operations_252.checkStatus(__ctx_250, option);
  } catch (e) {
    if (__isHttpResponder_0(e)) {
      return e[__httpResponderSymbol_1](__ctx_250);
    } else throw e;
  }

  __ctx_250.response.setHeader("content-type", "application/json");
  __ctx_250.response.end(globalThis.JSON.stringify(__result_251));
}
