name: Build CCF consortium manager
description: Build CCF consortium manager

inputs:
  tag:
    required: true
    description: The tag

runs:
  using: composite
  steps:
    - uses: ./.github/actions/build-container-and-artefacts
      with:
        name: ccf-consortium-manager
        tag: ${{ inputs.tag }}
        dockerfile: build/docker/Dockerfile.ccf-consortium-manager
        context: ${{ github.workspace }}
