# From https://black.readthedocs.io/en/stable/integrations/github_actions.html
name: Black Formatter Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    - release
  push:

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ["self-hosted", "1ES.Pool=azure-cleanroom-public"]
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable