name: Cleanup stale resources created by BVTs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0"

permissions:
  id-token: write
  contents: read  # This is required for actions/checkout

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  cleanup-stale-resources:
    runs-on: ["self-hosted", "1ES.Pool=ubuntu2204-pool"]
    environment: test
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.BVT_SUBSCRIPTION_ID }}

    - name: Execute cleanup
      env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      run: pwsh ./.github/scripts/cleanup.ps1 -environment "bvt"