name: "PR Validation: CGS Sample App Validation"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release

permissions:
  id-token: write
  contents: read  # This is required for actions/checkout
  checks: write   # This is required to generate the test report

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cgs-sample:
    runs-on: ["self-hosted", "1ES.Pool=ubuntu2204-pool"]
    environment: pr
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to Azure and refresh token
        uses: ./.github/actions/login-to-azure
        env:
          CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

      - name: Deploy CGS sample
        run: pwsh ./samples/governance/deploy-cgs.ps1