name: "PR Validation"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - release
      - main

permissions:
  id-token: write
  contents: read  # This is required for actions/checkout
  checks: write   # This is required to generate the test report


# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/pr_build_all.yml

  test-cgs:
    uses: ./.github/workflows/pr_cgs_tests.yml

  test-ccf:
    needs: [build]
    uses: ./.github/workflows/pr_ccf.yml

  test-cleanroom-cluster:
    needs: [build]
    uses: ./.github/workflows/pr_cleanroom_cluster.yml

  test-multi-party-collab:
    needs: [build]
    uses: ./.github/workflows/pr_multi_party_collab_samples.yml
